import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { assignCompanyTrainingProgram, createCompanyDepartment, createCompanyEmployeeLifecycleEvent, createCompanyJobDesignation, createCompanyTrainingProgram, listCompanyDepartments, listCompanyEmployeeEmergencyContacts, listCompanyEmployeeLifecycleEvents, listCompanyEmployees, listCompanyJobDesignations, listCompanyTrainingAssignments, listCompanyTrainingPrograms, recordAuditEvent, saveCompanyDepartmentManager, saveCompanyEmployeeEmergencyContact, saveEmployeeProfile } from "../db";
import { protectedProcedure, router } from "../_core/trpc";

const directoryRoles = ["admin", "manager", "hr"] as const;
const employeeStatus = z.enum(["active", "on_leave", "inactive"]);
const lifecycleEventType = z.enum(["joined", "profile_updated", "status_changed", "role_changed", "department_changed", "designation_changed", "manager_changed", "offboarding_started", "offboarding_completed"]);

function ensureDirectoryAccess(role: string) {
  if (!directoryRoles.includes(role as typeof directoryRoles[number])) throw new TRPCError({ code: "FORBIDDEN", message: "لا تملك صلاحية إدارة دليل الموظفين" });
}

function ensureLifecycleAccess(role: string) {
  if (!["admin", "hr"].includes(role)) throw new TRPCError({ code: "FORBIDDEN", message: "لا تملك صلاحية إدارة دورة حياة الموظفين" });
}

export const employeesRouter = router({
  list: protectedProcedure.query(async ({ ctx }) => { ensureDirectoryAccess(ctx.user.role); return listCompanyEmployees(ctx.user.companyId); }),
  departments: protectedProcedure.query(async ({ ctx }) => { ensureDirectoryAccess(ctx.user.role); return listCompanyDepartments(ctx.user.companyId); }),
  designations: protectedProcedure.query(async ({ ctx }) => { ensureDirectoryAccess(ctx.user.role); return listCompanyJobDesignations(ctx.user.companyId); }),
  lifecycle: protectedProcedure.query(async ({ ctx }) => { ensureLifecycleAccess(ctx.user.role); const [employees, events] = await Promise.all([listCompanyEmployees(ctx.user.companyId), listCompanyEmployeeLifecycleEvents(ctx.user.companyId)]); return { employees, events }; }),
  emergencyContacts: protectedProcedure.query(async ({ ctx }) => { ensureLifecycleAccess(ctx.user.role); return listCompanyEmployeeEmergencyContacts(ctx.user.companyId); }),
  training: protectedProcedure.query(async ({ ctx }) => { ensureLifecycleAccess(ctx.user.role); const [employees, programs, assignments] = await Promise.all([listCompanyEmployees(ctx.user.companyId), listCompanyTrainingPrograms(ctx.user.companyId), listCompanyTrainingAssignments(ctx.user.companyId)]); return { employees, programs, assignments }; }),
  createDepartment: protectedProcedure.input(z.object({ name: z.string().trim().min(2).max(120), code: z.string().trim().max(32).optional() })).mutation(async ({ ctx, input }) => { ensureDirectoryAccess(ctx.user.role); return createCompanyDepartment({ companyId: ctx.user.companyId, ...input }); }),
  saveDepartmentManager: protectedProcedure.input(z.object({ departmentId: z.number().int().positive(), managerUserId: z.number().int().positive().optional() })).mutation(async ({ ctx, input }) => { ensureDirectoryAccess(ctx.user.role); return saveCompanyDepartmentManager({ companyId: ctx.user.companyId, ...input }); }),
  createDesignation: protectedProcedure.input(z.object({ title: z.string().trim().min(2).max(160), code: z.string().trim().max(32).optional() })).mutation(async ({ ctx, input }) => { ensureDirectoryAccess(ctx.user.role); return createCompanyJobDesignation({ companyId: ctx.user.companyId, createdByUserId: ctx.user.id, ...input }); }),
  saveProfile: protectedProcedure.input(z.object({ userId: z.number().int().positive(), employeeNumber: z.string().trim().max(40).optional(), jobTitle: z.string().trim().max(160).optional(), designationId: z.number().int().positive().optional(), departmentId: z.number().int().positive().optional(), region: z.string().trim().max(120).optional(), workLocation: z.string().trim().max(160).optional(), managerUserId: z.number().int().positive().optional(), employmentStatus: employeeStatus, joinedAt: z.date().optional() })).mutation(async ({ ctx, input }) => { ensureDirectoryAccess(ctx.user.role); return saveEmployeeProfile({ companyId: ctx.user.companyId, updatedByUserId: ctx.user.id, ...input }); }),
  saveEmergencyContact: protectedProcedure.input(z.object({ employeeUserId: z.number().int().positive(), contactName: z.string().trim().min(2).max(160), relationship: z.string().trim().min(2).max(80), phone: z.string().trim().min(7).max(48) })).mutation(async ({ ctx, input }) => { ensureLifecycleAccess(ctx.user.role); const contact = await saveCompanyEmployeeEmergencyContact({ companyId: ctx.user.companyId, createdByUserId: ctx.user.id, ...input }); await createCompanyEmployeeLifecycleEvent({ companyId: ctx.user.companyId, employeeUserId: input.employeeUserId, eventType: "profile_updated", effectiveAt: new Date(), note: "تحديث بيانات ملف الموظف", createdByUserId: ctx.user.id }); return contact; }),
  createLifecycleEvent: protectedProcedure.input(z.object({ employeeUserId: z.number().int().positive(), eventType: lifecycleEventType, effectiveAt: z.date(), note: z.string().trim().max(500).optional() })).mutation(async ({ ctx, input }) => { ensureLifecycleAccess(ctx.user.role); return createCompanyEmployeeLifecycleEvent({ companyId: ctx.user.companyId, createdByUserId: ctx.user.id, ...input }); }),
  createTrainingProgram: protectedProcedure.input(z.object({ title: z.string().trim().min(2).max(180), description: z.string().trim().max(800).optional(), durationMinutes: z.number().int().min(0).max(100000) })).mutation(async ({ ctx, input }) => { ensureLifecycleAccess(ctx.user.role); const program = await createCompanyTrainingProgram({ companyId: ctx.user.companyId, createdByUserId: ctx.user.id, ...input }); try { await recordAuditEvent({ companyId: ctx.user.companyId, actorUserId: ctx.user.id, category: "training", action: "training_program_created", entityType: "training_program", entityId: program.id, summary: "إنشاء مسار تدريب" }); } catch (error) { console.error("[Audit] تعذر حفظ حدث التدريب", error); } return program; }),
  assignTrainingProgram: protectedProcedure.input(z.object({ employeeUserId: z.number().int().positive(), trainingProgramId: z.number().int().positive(), dueAt: z.date().optional() })).mutation(async ({ ctx, input }) => { ensureLifecycleAccess(ctx.user.role); const assignment = await assignCompanyTrainingProgram({ companyId: ctx.user.companyId, assignedByUserId: ctx.user.id, ...input }); try { await recordAuditEvent({ companyId: ctx.user.companyId, actorUserId: ctx.user.id, category: "training", action: "training_assigned", entityType: "employee_training_assignment", entityId: assignment.id, summary: "تعيين مسار تدريب" }); } catch (error) { console.error("[Audit] تعذر حفظ حدث تعيين التدريب", error); } return assignment; }),
});
