import { beforeEach, describe, expect, it, vi } from "vitest";

const dbMocks = vi.hoisted(() => ({
  archiveInternalMessagingChannel: vi.fn(), createInternalMessagingChannel: vi.fn(), getInternalMessagingChannelDetail: vi.fn(), getInternalMessagingChannelDetailForAdmin: vi.fn(), listCompanyEmployees: vi.fn(), listInternalMessagingChannelsForAdmin: vi.fn(), listInternalMessagingChannelsForUser: vi.fn(), listInternalMessagingMessages: vi.fn(), markInternalMessagingChannelRead: vi.fn(), replaceInternalMessagingChannelMembers: vi.fn(), sendInternalMessagingMessage: vi.fn(),
}));
vi.mock("../db", () => dbMocks);
import { messagingRouter } from "./messaging";
import type { TrpcContext } from "../_core/context";

function context(role: "user" | "hr" | "government" | "manager" | "admin" = "user", accountStatus: "active" | "pending" = "active"): TrpcContext {
  return { user: { id: 9, openId: "messaging-user", name: "موظف المراسلات", email: "messaging@example.com", loginMethod: "oauth", companyId: 7, role, accountStatus, createdAt: new Date(), updatedAt: new Date(), lastSignedIn: new Date() }, req: {} as TrpcContext["req"], res: {} as TrpcContext["res"] };
}

describe("messaging router", () => {
  beforeEach(() => { vi.clearAllMocks(); dbMocks.listInternalMessagingChannelsForUser.mockResolvedValue([]); dbMocks.listInternalMessagingChannelsForAdmin.mockResolvedValue([]); dbMocks.listCompanyEmployees.mockResolvedValue([]); dbMocks.getInternalMessagingChannelDetail.mockResolvedValue({ channel: { id: 21 }, members: [] }); dbMocks.getInternalMessagingChannelDetailForAdmin.mockResolvedValue({ channel: { id: 21 }, members: [] }); dbMocks.listInternalMessagingMessages.mockResolvedValue([]); dbMocks.createInternalMessagingChannel.mockResolvedValue({ id: 21 }); dbMocks.replaceInternalMessagingChannelMembers.mockResolvedValue({ id: 21 }); dbMocks.archiveInternalMessagingChannel.mockResolvedValue({ success: true }); dbMocks.markInternalMessagingChannelRead.mockResolvedValue({ success: true }); dbMocks.sendInternalMessagingMessage.mockResolvedValue({ success: true }); });
  it("reads only channels scoped to the signed-in user and company", async () => { const caller = messagingRouter.createCaller(context("user")); await expect(caller.myChannels()).resolves.toEqual([]); expect(dbMocks.listInternalMessagingChannelsForUser).toHaveBeenCalledWith({ companyId: 7, userId: 9 }); });
  it("passes company, channel and sender identity to protected message operations", async () => { const caller = messagingRouter.createCaller(context("manager")); await expect(caller.messages({ channelId: 21 })).resolves.toEqual([]); await expect(caller.send({ channelId: 21, body: "تحديث داخلي" })).resolves.toEqual({ success: true }); expect(dbMocks.listInternalMessagingMessages).toHaveBeenCalledWith({ companyId: 7, channelId: 21, userId: 9 }); expect(dbMocks.sendInternalMessagingMessage).toHaveBeenCalledWith({ companyId: 7, channelId: 21, senderUserId: 9, body: "تحديث داخلي" }); });
  it("updates the read marker only with the signed-in member and company scope", async () => { const caller = messagingRouter.createCaller(context("user")); await expect(caller.markRead({ channelId: 21 })).resolves.toEqual({ success: true }); expect(dbMocks.markInternalMessagingChannelRead).toHaveBeenCalledWith({ companyId: 7, channelId: 21, userId: 9 }); });
  it("blocks non-admin users from listing employees or creating a channel", async () => { const caller = messagingRouter.createCaller(context("hr")); await expect(caller.management.employees()).rejects.toMatchObject({ code: "FORBIDDEN" }); await expect(caller.management.create({ name: "فريق العمليات", memberUserIds: [10] })).rejects.toMatchObject({ code: "FORBIDDEN" }); expect(dbMocks.listCompanyEmployees).not.toHaveBeenCalled(); expect(dbMocks.createInternalMessagingChannel).not.toHaveBeenCalled(); });
  it("lets the facility manager create a company-scoped channel with selected employees", async () => { const caller = messagingRouter.createCaller(context("admin")); await expect(caller.management.create({ name: "فريق العمليات", description: "تنسيق داخلي", memberUserIds: [10, 12] })).resolves.toEqual({ id: 21 }); expect(dbMocks.createInternalMessagingChannel).toHaveBeenCalledWith({ companyId: 7, createdByUserId: 9, name: "فريق العمليات", description: "تنسيق داخلي", memberUserIds: [10, 12] }); });
  it("lets the facility manager replace members and archive only within the current company", async () => { const caller = messagingRouter.createCaller(context("admin")); await expect(caller.management.replaceMembers({ channelId: 21, memberUserIds: [10] })).resolves.toEqual({ id: 21 }); await expect(caller.management.archive({ channelId: 21 })).resolves.toEqual({ success: true }); expect(dbMocks.replaceInternalMessagingChannelMembers).toHaveBeenCalledWith({ companyId: 7, channelId: 21, actorUserId: 9, memberUserIds: [10] }); expect(dbMocks.archiveInternalMessagingChannel).toHaveBeenCalledWith({ companyId: 7, channelId: 21 }); });
  it("blocks a pending account before it reaches the messaging data layer", async () => { const caller = messagingRouter.createCaller(context("user", "pending")); await expect(caller.myChannels()).rejects.toMatchObject({ code: "FORBIDDEN" }); expect(dbMocks.listInternalMessagingChannelsForUser).not.toHaveBeenCalled(); });
  it("blocks a pending account before it can update a read marker", async () => { const caller = messagingRouter.createCaller(context("user", "pending")); await expect(caller.markRead({ channelId: 21 })).rejects.toMatchObject({ code: "FORBIDDEN" }); expect(dbMocks.markInternalMessagingChannelRead).not.toHaveBeenCalled(); });
});
