import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, ClipboardCheck, ShieldAlert, XCircle } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const stageLabels = { manager: "المرحلة 1 · المدير المباشر", hr: "المرحلة 2 · الموارد البشرية", government: "المرحلة 2 · العلاقات الحكومية", admin: "مرحلة إدارية" } as const;

export default function ApprovalsInbox() {
  const utils = trpc.useUtils();
  const { data, isLoading, isError, error } = trpc.approvals.inbox.useQuery();
  const [notes, setNotes] = useState<Record<number, string>>({});
  const decide = trpc.approvals.decide.useMutation({ onSuccess: () => { toast.success("تم تسجيل قرار الموافقة"); utils.approvals.inbox.invalidate(); utils.requests.operations.invalidate(); }, onError: issue => toast.error("تعذر تسجيل القرار", { description: issue.message }) });
  return <DashboardLayout><div dir="rtl" className="mx-auto max-w-5xl"><div><p className="text-xs font-bold text-[#5d8d70]">قرارات العمل</p><h1 className="mt-2 text-3xl font-bold text-[#1d4532]">صندوق الموافقات</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-[#748178]">كل قرار هنا مرتبط بطلب من شركتك وبالدور المخول له، ويُحفظ مع اسم صاحب القرار وملاحظته.</p></div>{isLoading ? <div className="mt-8 space-y-4">{[1, 2, 3].map(item => <Skeleton key={item} className="h-44 rounded-3xl" />)}</div> : isError ? <State title="تعذر تحميل الموافقات" text={error.message} error /> : data?.length ? <div className="mt-8 space-y-4">{data.map(({ task, request, employee }) => <article key={task.id} className="rounded-3xl border border-[#dfe9e1] bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-[#f2f6ed] px-3 py-1 text-xs font-bold text-[#4b7257]">{stageLabels[task.approverRole]}</span><span className={`rounded-full px-3 py-1 text-xs font-bold ${request.type === "hr" ? "bg-[#e7f3e9] text-[#347650]" : "bg-[#edf3f6] text-[#426b78]"}`}>{request.type === "hr" ? "الموارد البشرية" : "العلاقات الحكومية"}</span><span className="text-xs text-[#839087]">{request.reference}</span></div><h2 className="mt-3 font-bold text-[#294535]">{request.subject}</h2><p className="mt-2 text-sm text-[#6f7f75]">مقدم الطلب: {employee.name || employee.email || "موظف"}</p></div><span className="rounded-xl bg-[#f8f1df] px-3 py-2 text-xs font-bold text-[#967224]">بانتظار القرار</span></div><p className="mt-4 rounded-2xl bg-[#f7faf7] p-4 text-sm leading-7 text-[#596d60]">{request.details}</p><Textarea value={notes[task.id] || ""} onChange={event => setNotes(current => ({ ...current, [task.id]: event.target.value }))} placeholder="ملاحظة القرار (اختيارية عند الموافقة، ومفضلة عند الرفض)" className="mt-4 min-h-20 rounded-xl" maxLength={2500} /><div className="mt-4 flex flex-wrap justify-end gap-2"><Button variant="outline" onClick={() => decide.mutate({ id: task.id, decision: "rejected", ...(notes[task.id]?.trim() ? { note: notes[task.id] } : {}) })} disabled={decide.isPending} className="rounded-xl border-[#efd2cf] text-[#a54d47]"><XCircle className="ml-2 size-4" />رفض</Button><Button onClick={() => decide.mutate({ id: task.id, decision: "approved", ...(notes[task.id]?.trim() ? { note: notes[task.id] } : {}) })} disabled={decide.isPending} className="rounded-xl bg-[#1f5b45] hover:bg-[#174735]"><CheckCircle2 className="ml-2 size-4" />موافقة</Button></div></article>)}</div> : <State title="لا توجد موافقات معلقة" text="ستظهر هنا الطلبات التي تتطلب قراراً من دورك داخل الشركة." />}</div></DashboardLayout>;
}
function State({ title, text, error = false }: { title: string; text: string; error?: boolean }) { return <div className="mt-8 flex min-h-72 flex-col items-center justify-center rounded-3xl border border-[#dfe9e1] bg-white px-6 text-center"><span className={`flex size-14 items-center justify-center rounded-3xl ${error ? "bg-[#fdecea] text-[#a94e48]" : "bg-[#eaf3eb] text-[#357b53]"}`}>{error ? <ShieldAlert className="size-6" /> : <ClipboardCheck className="size-6" />}</span><h2 className="mt-5 font-bold text-[#294535]">{title}</h2><p className="mt-2 max-w-md text-sm leading-6 text-[#748178]">{text}</p></div>; }
