import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Laptop, PackageCheck, Plus, RotateCcw, ShieldAlert } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { FormField } from "@/components/design-system";

const statusLabels = { available: "متاحة", assigned: "مُسلّمة تشغيلياً", returned: "مستعادة", retired: "موقوفة" } as const;
type AssetStatus = keyof typeof statusLabels;

export default function Assets() {
  const utils = trpc.useUtils();
  const { data, isLoading, isError, error } = trpc.assets.overview.useQuery();
  const [createOpen, setCreateOpen] = useState(false);
  const [selectedAssetId, setSelectedAssetId] = useState<number | null>(null);
  const [assetName, setAssetName] = useState(""); const [assetTag, setAssetTag] = useState(""); const [assetType, setAssetType] = useState(""); const [notes, setNotes] = useState(""); const [assignedEmployeeId, setAssignedEmployeeId] = useState("none");
  const [nextStatus, setNextStatus] = useState<AssetStatus>("available"); const [nextEmployeeId, setNextEmployeeId] = useState("none");
  const selectedAsset = data?.assets.find(asset => asset.id === selectedAssetId);
  const createAsset = trpc.assets.create.useMutation({ onSuccess: () => { toast.success("تم حفظ سجل العهدة"); setCreateOpen(false); setAssetName(""); setAssetTag(""); setAssetType(""); setNotes(""); setAssignedEmployeeId("none"); utils.assets.overview.invalidate(); }, onError: issue => toast.error("تعذر حفظ العهدة", { description: issue.message }) });
  const updateAsset = trpc.assets.update.useMutation({ onSuccess: () => { toast.success("تم تحديث حالة العهدة"); setSelectedAssetId(null); utils.assets.overview.invalidate(); }, onError: issue => toast.error("تعذر تحديث العهدة", { description: issue.message }) });
  const openUpdate = (asset: NonNullable<typeof data>["assets"][number]) => { setSelectedAssetId(asset.id); setNextStatus(asset.status); setNextEmployeeId(asset.assignedEmployeeUserId ? String(asset.assignedEmployeeUserId) : "none"); };
  return <DashboardLayout><main dir="rtl" className="mx-auto max-w-6xl"><section className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold text-ds-brand-400">HR Core · عمليات داخلية</p><h1 className="mt-2 text-3xl font-bold text-ds-brand-950">العهد والأجهزة</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-ds-neutral-600">سجل تشغيلي داخلي لتعيين الأجهزة والعهد للموظفين المفعّلين داخل الشركة. لا يتضمن قيمة مالية أو إقرار استلام أو مسؤولية قانونية.</p></div><Button onClick={() => setCreateOpen(true)} className="rounded-xl bg-ds-brand-800"><Plus className="ml-2 size-4" />عهدة أو جهاز جديد</Button></section>
    {isLoading ? <div className="mt-8 grid gap-4 md:grid-cols-2">{[1, 2, 3, 4].map(item => <Skeleton key={item} className="h-44 rounded-3xl" />)}</div> : isError ? <State title="تعذر تحميل سجل العهد" text={error.message} error /> : data?.assets.length ? <section className="mt-8 grid gap-4 md:grid-cols-2">{data.assets.map(asset => <article key={asset.id} className="rounded-3xl border border-ds-neutral-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><span className="flex size-11 items-center justify-center rounded-2xl bg-ds-brand-100 text-ds-brand-600"><Laptop className="size-5" /></span><span className="rounded-full bg-ds-brand-50 px-3 py-1 text-xs font-bold text-ds-brand-600">{statusLabels[asset.status]}</span></div><h2 className="mt-4 font-bold text-ds-neutral-950">{asset.assetName}</h2><p className="mt-1 text-sm text-ds-neutral-700">{asset.assetTag}{asset.assetType ? ` · ${asset.assetType}` : ""}</p><div className="mt-4 border-t border-ds-neutral-100 pt-4 text-xs"><p className="text-ds-neutral-500">الموظف المكلّف</p><p className="mt-1 font-bold text-ds-brand-900">{asset.assignedEmployee?.name || "غير معيّن"}</p>{asset.notes && <p className="mt-3 leading-6 text-ds-neutral-600">{asset.notes}</p>}</div><Button variant="outline" onClick={() => openUpdate(asset)} className="mt-5 h-9 w-full rounded-xl border-ds-brand-200 text-ds-brand-700"><RotateCcw className="ml-2 size-4" />تحديث الحالة</Button></article>)}</section> : <State title="لا توجد عهد أو أجهزة بعد" text="أضف سجلاً داخلياً لجهاز أو عهدة ثم عيّنه لموظف مفعّل عند الحاجة." />}
    <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent dir="rtl" className="sm:max-w-xl"><DialogHeader><DialogTitle>عهدة أو جهاز جديد</DialogTitle><DialogDescription>سجل تشغيلي داخلي، لا يحفظ قيمة مالية ولا يمثل إقرار استلام.</DialogDescription></DialogHeader><div className="grid gap-4 py-3"><div className="grid gap-4 sm:grid-cols-2"><FormField label="اسم العهدة أو الجهاز"><Input value={assetName} onChange={event => setAssetName(event.target.value)} placeholder="مثال: حاسب محمول" /></FormField><FormField label="رمز الأصل"><Input value={assetTag} onChange={event => setAssetTag(event.target.value)} placeholder="مثال: LAP-021" /></FormField></div><div className="grid gap-4 sm:grid-cols-2"><FormField label="النوع"><Input value={assetType} onChange={event => setAssetType(event.target.value)} placeholder="اختياري" /></FormField><FormField label="تعيين لموظف"><Select value={assignedEmployeeId} onValueChange={setAssignedEmployeeId}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">تظل متاحة دون تعيين</SelectItem>{data?.employees.map(employee => <SelectItem key={employee.id} value={String(employee.id)}>{employee.name || "موظف"}</SelectItem>)}</SelectContent></Select></FormField></div><FormField label="ملاحظة تشغيلية"><Textarea value={notes} onChange={event => setNotes(event.target.value)} maxLength={500} placeholder="اختياري" /></FormField></div><DialogFooter><Button variant="outline" onClick={() => setCreateOpen(false)}>إلغاء</Button><Button onClick={() => createAsset.mutate({ assetName: assetName.trim(), assetTag: assetTag.trim(), ...(assetType.trim() ? { assetType: assetType.trim() } : {}), ...(assignedEmployeeId !== "none" ? { assignedEmployeeUserId: Number(assignedEmployeeId) } : {}), ...(notes.trim() ? { notes: notes.trim() } : {}) })} disabled={createAsset.isPending || assetName.trim().length < 2 || assetTag.trim().length < 2} className="bg-ds-brand-800">حفظ السجل</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={selectedAssetId !== null} onOpenChange={open => !open && setSelectedAssetId(null)}><DialogContent dir="rtl"><DialogHeader><DialogTitle>تحديث العهدة</DialogTitle><DialogDescription>يمكن تعيينها لموظف مفعّل أو تحديث حالتها التشغيلية. لا ينشئ ذلك إقرار استلام.</DialogDescription></DialogHeader><div className="grid gap-4 py-3"><FormField label="الحالة"><Select value={nextStatus} onValueChange={value => setNextStatus(value as AssetStatus)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{Object.entries(statusLabels).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></FormField><FormField label="الموظف"><Select value={nextEmployeeId} onValueChange={setNextEmployeeId} disabled={nextStatus !== "assigned"}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">غير معيّن</SelectItem>{data?.employees.map(employee => <SelectItem key={employee.id} value={String(employee.id)}>{employee.name || "موظف"}</SelectItem>)}</SelectContent></Select></FormField></div><DialogFooter><Button variant="outline" onClick={() => setSelectedAssetId(null)}>إلغاء</Button><Button onClick={() => selectedAsset && updateAsset.mutate({ assetId: selectedAsset.id, status: nextStatus, ...(nextStatus === "assigned" && nextEmployeeId !== "none" ? { assignedEmployeeUserId: Number(nextEmployeeId) } : {}) })} disabled={updateAsset.isPending || (nextStatus === "assigned" && nextEmployeeId === "none")} className="bg-ds-brand-800">حفظ التحديث</Button></DialogFooter></DialogContent></Dialog>
  </main></DashboardLayout>;
}
function State({ title, text, error = false }: { title: string; text: string; error?: boolean }) { return <div className="mt-8 flex min-h-72 flex-col items-center justify-center rounded-3xl border border-ds-neutral-200 bg-white px-6 text-center"><span className={`flex size-14 items-center justify-center rounded-3xl ${error ? "bg-ds-danger-soft text-ds-danger" : "bg-ds-success-soft text-ds-brand-600"}`}>{error ? <ShieldAlert className="size-6" /> : <PackageCheck className="size-6" />}</span><h2 className="mt-5 font-bold text-ds-neutral-950">{title}</h2><p className="mt-2 max-w-md text-sm leading-6 text-ds-neutral-600">{text}</p></div>; }
