import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Clock3, LogIn, LogOut, MapPin, MonitorSmartphone, ShieldAlert, UsersRound } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const modeLabels = { onsite: "من مقر العمل", remote: "عن بُعد" } as const;
type WorkMode = keyof typeof modeLabels;

function formatTime(value: Date | string | null | undefined) {
  return value ? new Intl.DateTimeFormat("ar-SA", { hour: "2-digit", minute: "2-digit" }).format(new Date(value)) : "—";
}

export default function Attendance() {
  const utils = trpc.useUtils();
  const { data: mine, isLoading: isMineLoading, isError: mineError, error: mineIssue } = trpc.attendance.mine.useQuery();
  const { data: overview } = trpc.attendance.overview.useQuery({});
  const [workMode, setWorkMode] = useState<WorkMode>("onsite");
  const [note, setNote] = useState("");
  const refresh = () => { utils.attendance.mine.invalidate(); utils.attendance.overview.invalidate(); };
  const checkIn = trpc.attendance.checkIn.useMutation({ onSuccess: () => { toast.success("تم تسجيل الحضور"); setNote(""); refresh(); }, onError: issue => toast.error("تعذر تسجيل الحضور", { description: issue.message }) });
  const checkOut = trpc.attendance.checkOut.useMutation({ onSuccess: () => { toast.success("تم تسجيل الانصراف"); refresh(); }, onError: issue => toast.error("تعذر تسجيل الانصراف", { description: issue.message }) });
  const completed = overview?.filter(item => item.entry.status === "completed").length ?? 0;

  return <DashboardLayout><div dir="rtl" className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold text-[#5d8d70]">المرحلة 15 · القوى العاملة</p><h1 className="mt-2 text-3xl font-bold text-[#1d4532]">الدوام اليومي</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-[#748178]">سجل حضور مرن داخل المنصة، مع عرض شخصي للموظف ونطاق متابعة يتبع دور المسؤول أو المدير.</p></div><span className="rounded-full bg-[#e8f4eb] px-3 py-1.5 text-xs font-bold text-[#347950]">توقيت الرياض التشغيلي</span></div>
    {isMineLoading ? <div className="mt-8 grid gap-4 md:grid-cols-2"><Skeleton className="h-72 rounded-3xl" /><Skeleton className="h-72 rounded-3xl" /></div> : mineError ? <StateCard title="تعذر تحميل سجل الدوام" text={mineIssue.message} error /> : <><section className="mt-8 grid gap-4 md:grid-cols-[1.15fr_.85fr]"><article className="rounded-3xl border border-[#dfe9e1] bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><span className="flex size-11 items-center justify-center rounded-2xl bg-[#e7f3e9] text-[#337b54]"><Clock3 className="size-5" /></span><h2 className="mt-4 text-xl font-bold text-[#294535]">دوامي اليوم</h2><p className="mt-2 text-sm text-[#748178]">{mine ? mine.status === "completed" ? "تم تسجيل الحضور والانصراف." : "حضور مسجل بانتظار الانصراف." : "لم يُسجل حضور لهذا اليوم بعد."}</p></div>{mine && <span className={`rounded-full px-3 py-1 text-xs font-bold ${mine.status === "completed" ? "bg-[#e7f4ea] text-[#30774e]" : "bg-[#fff1de] text-[#a46723]"}`}>{mine.status === "completed" ? "مكتمل" : "قيد الدوام"}</span>}</div>{mine ? <div className="mt-6 grid grid-cols-3 gap-3 border-t border-[#edf1ed] pt-5"><Fact label="الحضور" value={formatTime(mine.checkInAt)} /><Fact label="الانصراف" value={formatTime(mine.checkOutAt)} /><Fact label="النمط" value={modeLabels[mine.workMode]} /></div> : <div className="mt-6 grid gap-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="نمط العمل"><Select value={workMode} onValueChange={value => setWorkMode(value as WorkMode)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="onsite">من مقر العمل</SelectItem><SelectItem value="remote">عن بُعد</SelectItem></SelectContent></Select></Field><div className="rounded-2xl bg-[#f5f8f5] p-4 text-xs leading-6 text-[#6c7c70]">يُسجل الوقت الحالي كتوقيت نظام تشغيلي، ولا يمكن إنشاء أكثر من سجل واحد لليوم.</div></div><Field label="ملاحظة اختيارية"><Textarea value={note} onChange={event => setNote(event.target.value)} placeholder="مثال: زيارة ميدانية صباحاً" /></Field><Button onClick={() => checkIn.mutate({ workMode, ...(note.trim() ? { note: note.trim() } : {}) })} disabled={checkIn.isPending} className="h-11 rounded-xl bg-[#1f5b45]"><LogIn className="ml-2 size-4" />تسجيل الحضور</Button></div>}{mine?.status === "open" && <Button onClick={() => checkOut.mutate()} disabled={checkOut.isPending} variant="outline" className="mt-6 h-10 w-full rounded-xl border-[#cfe0d2] text-[#367850]"><LogOut className="ml-2 size-4" />تسجيل الانصراف</Button>}</article>
      <article className="rounded-3xl bg-[#183f31] p-6 text-white"><div className="flex size-11 items-center justify-center rounded-2xl bg-white/10 text-[#e7c89c]"><UsersRound className="size-5" /></div><h2 className="mt-5 text-xl font-bold">متابعة اليوم</h2><p className="mt-2 text-sm leading-7 text-[#d4e4d7]">يعرض النطاق حسب الصلاحية: الشركة للمسؤول والموارد البشرية، والفريق المباشر للمدير، وسجل الموظف لنفسه.</p><div className="mt-7 grid grid-cols-2 gap-3"><Metric label="سجلات النطاق" value={overview?.length ?? 0} /><Metric label="دوام مكتمل" value={completed} /></div><div className="mt-6 rounded-2xl border border-white/10 bg-white/5 p-3 text-xs leading-6 text-[#c8dbcd]"><MapPin className="ml-1 inline size-3.5" />لا يتتبع الموقع الجغرافي أو البصمة في هذا الإصدار.</div></article></section>
      <section className="mt-6 rounded-3xl border border-[#dfe9e1] bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><span className="flex size-9 items-center justify-center rounded-xl bg-[#e9f4eb] text-[#347950]"><MonitorSmartphone className="size-4" /></span><div><h2 className="font-bold text-[#294535]">سجل الدوام ضمن نطاقك</h2><p className="mt-1 text-xs text-[#748178]">تُعرض الحقول التشغيلية الأساسية فقط.</p></div></div>{overview?.length ? <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[620px] text-right text-sm"><thead className="border-b border-[#edf1ed] text-xs text-[#7a897f]"><tr><th className="px-3 py-3">الموظف</th><th className="px-3 py-3">نمط العمل</th><th className="px-3 py-3">الحضور</th><th className="px-3 py-3">الانصراف</th><th className="px-3 py-3">الحالة</th></tr></thead><tbody>{overview.map(item => <tr key={item.entry.id} className="border-b border-[#f1f4f1] last:border-0"><td className="px-3 py-4 font-bold text-[#385545]">{item.user.name || "موظف"}</td><td className="px-3 py-4 text-[#6d7e73]">{modeLabels[item.entry.workMode]}</td><td className="px-3 py-4 text-[#6d7e73]">{formatTime(item.entry.checkInAt)}</td><td className="px-3 py-4 text-[#6d7e73]">{formatTime(item.entry.checkOutAt)}</td><td className="px-3 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${item.entry.status === "completed" ? "bg-[#e7f4ea] text-[#30774e]" : "bg-[#fff1de] text-[#a46723]"}`}>{item.entry.status === "completed" ? "مكتمل" : "قيد الدوام"}</span></td></tr>)}</tbody></table></div> : <div className="mt-5 rounded-2xl bg-[#f7f9f7] px-4 py-8 text-center text-sm text-[#758178]">لا توجد سجلات دوام في نطاقك لهذا اليوم.</div>}</section></>}
  </div></DashboardLayout>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div><label className="mb-2 block text-xs font-bold text-[#61756a]">{label}</label>{children}</div>; }
function Fact({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-[#89958d]">{label}</p><p className="mt-2 font-bold text-[#3a5646]">{value}</p></div>; }
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-2xl bg-white/10 p-3"><p className="text-[11px] text-[#b9d0c0]">{label}</p><p className="mt-2 text-2xl font-bold text-[#f4e4ca]">{value}</p></div>; }
function StateCard({ title, text, error = false }: { title: string; text: string; error?: boolean }) { return <div className="mt-8 flex min-h-72 flex-col items-center justify-center rounded-3xl border border-[#dfe9e1] bg-white px-6 text-center"><span className={`flex size-14 items-center justify-center rounded-3xl ${error ? "bg-[#fdecea] text-[#a94e48]" : "bg-[#eaf3eb] text-[#357b53]"}`}>{error ? <ShieldAlert className="size-6" /> : <Clock3 className="size-6" />}</span><h2 className="mt-5 font-bold text-[#294535]">{title}</h2><p className="mt-2 max-w-md text-sm leading-6 text-[#748178]">{text}</p></div>; }
