import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { CalendarDays, Plus, ShieldAlert, UsersRound } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { FormField } from "@/components/design-system";

const weekdays = [{ id: "sun", label: "الأحد" }, { id: "mon", label: "الاثنين" }, { id: "tue", label: "الثلاثاء" }, { id: "wed", label: "الأربعاء" }, { id: "thu", label: "الخميس" }, { id: "fri", label: "الجمعة" }, { id: "sat", label: "السبت" }] as const;
type Weekday = typeof weekdays[number]["id"];

export default function AttendanceSchedules() {
  const utils = trpc.useUtils();
  const { data, isLoading, isError, error } = trpc.attendance.schedules.useQuery();
  const [policyDialog, setPolicyDialog] = useState(false);
  const [assignmentDialog, setAssignmentDialog] = useState(false);
  const [title, setTitle] = useState(""); const [startTime, setStartTime] = useState("09:00"); const [endTime, setEndTime] = useState("17:00"); const [selectedDays, setSelectedDays] = useState<Weekday[]>(["sun", "mon", "tue", "wed", "thu"]); const [graceMinutes, setGraceMinutes] = useState("0");
  const [employeeUserId, setEmployeeUserId] = useState("none"); const [attendancePolicyId, setAttendancePolicyId] = useState("none"); const [effectiveFrom, setEffectiveFrom] = useState(""); const [effectiveTo, setEffectiveTo] = useState("");
  const refresh = () => utils.attendance.schedules.invalidate();
  const createPolicy = trpc.attendance.createPolicy.useMutation({ onSuccess: () => { toast.success("تم حفظ سياسة الدوام"); setPolicyDialog(false); setTitle(""); refresh(); }, onError: issue => toast.error("تعذر حفظ سياسة الدوام", { description: issue.message }) });
  const assignShift = trpc.attendance.assignShift.useMutation({ onSuccess: () => { toast.success("تم تعيين الوردية"); setAssignmentDialog(false); setEffectiveFrom(""); setEffectiveTo(""); refresh(); }, onError: issue => toast.error("تعذر تعيين الوردية", { description: issue.message }) });
  const toggleDay = (day: Weekday) => setSelectedDays(current => current.includes(day) ? current.filter(item => item !== day) : [...current, day]);
  const submitPolicy = () => createPolicy.mutate({ title: title.trim(), startTime, endTime, workDays: selectedDays, graceMinutes: Number(graceMinutes) });
  const submitAssignment = () => assignShift.mutate({ employeeUserId: Number(employeeUserId), attendancePolicyId: Number(attendancePolicyId), effectiveFrom, ...(effectiveTo ? { effectiveTo } : {}) });
  const policyTitle = (id: number) => data?.policies.find(policy => policy.id === id)?.title || "سياسة الدوام";

  return <DashboardLayout><div dir="rtl" className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold text-ds-brand-400">المرحلة 15 · القوى العاملة</p><h1 className="mt-2 text-3xl font-bold text-ds-brand-950">سياسات الدوام والورديات</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-ds-neutral-600">إعداد وصفي داخلي لساعات العمل وأيامه وتعييناته. لا يطبق احتساب رواتب أو تتبع موقع أو بصمة أو اتصالاً بجهاز خارجي.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => setAssignmentDialog(true)} disabled={!data?.policies.length || !data?.employees.length} className="rounded-xl border-ds-brand-200 text-ds-brand-700"><UsersRound className="ml-2 size-4" />تعيين وردية</Button><Button onClick={() => setPolicyDialog(true)} className="rounded-xl bg-ds-brand-800"><Plus className="ml-2 size-4" />سياسة جديدة</Button></div></div>
    {isLoading ? <div className="mt-8 grid gap-4 md:grid-cols-2"><Skeleton className="h-72 rounded-3xl" /><Skeleton className="h-72 rounded-3xl" /></div> : isError ? <StateCard title="تعذر تحميل سياسات الدوام" text={error.message} error /> : <><section className="mt-8 grid gap-6 xl:grid-cols-2"><Panel title="سياسات الدوام" icon={CalendarDays} action={<Button size="sm" variant="outline" onClick={() => setPolicyDialog(true)} className="rounded-xl border-ds-brand-200 text-ds-brand-700"><Plus className="ml-1 size-4" />إضافة</Button>}>{data?.policies.length ? <div className="grid gap-3">{data.policies.map(policy => <article key={policy.id} className="rounded-2xl border border-ds-neutral-200 p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold text-ds-neutral-950">{policy.title}</h2><p className="mt-1 text-xs text-ds-neutral-600">{policy.startTime} – {policy.endTime} · سماحية {policy.graceMinutes} دقيقة</p></div><span className="rounded-full bg-ds-brand-100 px-2.5 py-1 text-[11px] font-bold text-ds-brand-600">مفعّلة</span></div><p className="mt-3 text-xs text-ds-neutral-600">أيام العمل: {policy.workDays.split(",").map(day => weekdays.find(item => item.id === day)?.label || day).join("، ")}</p></article>)}</div> : <CompactEmpty text="أنشئ سياسة دوام قبل تعيين ورديات الموظفين." />}</Panel>
      <Panel title="تعيينات الورديات" icon={UsersRound} action={<Button size="sm" variant="outline" onClick={() => setAssignmentDialog(true)} disabled={!data?.policies.length || !data?.employees.length} className="rounded-xl border-ds-brand-200 text-ds-brand-700"><Plus className="ml-1 size-4" />تعيين</Button>}>{data?.assignments.length ? <div className="grid gap-3">{data.assignments.map(item => <article key={item.assignment.id} className="rounded-2xl border border-ds-neutral-200 p-4"><h2 className="font-bold text-ds-neutral-950">{item.employee.name || "موظف"}</h2><p className="mt-1 text-xs text-ds-neutral-600">{item.policy.title} · {item.policy.startTime} – {item.policy.endTime}</p><p className="mt-3 text-xs text-ds-neutral-600">ساري من {item.assignment.effectiveFrom}{item.assignment.effectiveTo ? ` إلى ${item.assignment.effectiveTo}` : ""}</p></article>)}</div> : <CompactEmpty text="عيّن وردية لموظف بعد إنشاء سياسة دوام مفعّلة." />}</Panel></section></>}
    <Dialog open={policyDialog} onOpenChange={setPolicyDialog}><DialogContent dir="rtl" className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>سياسة دوام جديدة</DialogTitle><DialogDescription>هذه السياسة وصف تشغيلي فقط، ولا تُستخدم لاحتساب الأجر أو المخالفات.</DialogDescription></DialogHeader><div className="grid gap-4 py-3"><FormField label="اسم السياسة"><Input value={title} onChange={event => setTitle(event.target.value)} placeholder="مثال: وردية المكتب" /></FormField><div className="grid gap-4 sm:grid-cols-2"><FormField label="بداية الدوام"><Input type="time" value={startTime} onChange={event => setStartTime(event.target.value)} /></FormField><FormField label="نهاية الدوام"><Input type="time" value={endTime} onChange={event => setEndTime(event.target.value)} /></FormField></div><FormField label="أيام العمل"><div className="flex flex-wrap gap-2">{weekdays.map(day => <Button key={day.id} type="button" size="sm" variant="outline" onClick={() => toggleDay(day.id)} className={selectedDays.includes(day.id) ? "border-ds-brand-600 bg-ds-brand-100 text-ds-brand-600" : "border-ds-brand-200 text-ds-neutral-700"}>{day.label}</Button>)}</div></FormField><FormField label="سماحية التأخير بالدقائق"><Input type="number" min="0" max="120" value={graceMinutes} onChange={event => setGraceMinutes(event.target.value)} /></FormField></div><DialogFooter><Button variant="outline" onClick={() => setPolicyDialog(false)}>إلغاء</Button><Button onClick={submitPolicy} disabled={createPolicy.isPending || title.trim().length < 2 || !selectedDays.length || Number(graceMinutes) < 0 || Number(graceMinutes) > 120} className="bg-ds-brand-800">حفظ السياسة</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={assignmentDialog} onOpenChange={setAssignmentDialog}><DialogContent dir="rtl"><DialogHeader><DialogTitle>تعيين وردية لموظف</DialogTitle><DialogDescription>يحفظ التعيين داخل الشركة الحالية ولا يغيّر سجل الحضور السابق.</DialogDescription></DialogHeader><div className="grid gap-4 py-3"><FormField label="الموظف"><Select value={employeeUserId} onValueChange={setEmployeeUserId}><SelectTrigger><SelectValue placeholder="اختر موظفاً" /></SelectTrigger><SelectContent>{data?.employees.map(employee => <SelectItem key={employee.id} value={String(employee.id)}>{employee.name || "موظف"}</SelectItem>)}</SelectContent></Select></FormField><FormField label="سياسة الدوام"><Select value={attendancePolicyId} onValueChange={setAttendancePolicyId}><SelectTrigger><SelectValue placeholder="اختر سياسة" /></SelectTrigger><SelectContent>{data?.policies.filter(policy => policy.isActive).map(policy => <SelectItem key={policy.id} value={String(policy.id)}>{policy.title}</SelectItem>)}</SelectContent></Select></FormField><div className="grid gap-4 sm:grid-cols-2"><FormField label="ساري من"><Input type="date" value={effectiveFrom} onChange={event => setEffectiveFrom(event.target.value)} /></FormField><FormField label="ساري حتى (اختياري)"><Input type="date" value={effectiveTo} onChange={event => setEffectiveTo(event.target.value)} /></FormField></div></div><DialogFooter><Button variant="outline" onClick={() => setAssignmentDialog(false)}>إلغاء</Button><Button onClick={submitAssignment} disabled={assignShift.isPending || employeeUserId === "none" || attendancePolicyId === "none" || !effectiveFrom || Boolean(effectiveTo && effectiveTo < effectiveFrom)} className="bg-ds-brand-800">حفظ التعيين</Button></DialogFooter></DialogContent></Dialog>
  </div></DashboardLayout>;
}

function Panel({ title, icon: Icon, action, children }: { title: string; icon: typeof CalendarDays; action: React.ReactNode; children: React.ReactNode }) { return <section className="rounded-3xl border border-ds-neutral-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><span className="flex size-9 items-center justify-center rounded-xl bg-ds-success-soft text-ds-brand-600"><Icon className="size-4" /></span><h2 className="font-bold text-ds-neutral-950">{title}</h2></div>{action}</div><div className="mt-5">{children}</div></section>; }
function CompactEmpty({ text }: { text: string }) { return <div className="rounded-2xl bg-ds-neutral-50 px-4 py-7 text-center text-sm text-ds-neutral-600">{text}</div>; }
function StateCard({ title, text, error = false }: { title: string; text: string; error?: boolean }) { return <div className="mt-8 flex min-h-72 flex-col items-center justify-center rounded-3xl border border-ds-neutral-200 bg-white px-6 text-center"><span className={`flex size-14 items-center justify-center rounded-3xl ${error ? "bg-ds-danger-soft text-ds-danger" : "bg-ds-success-soft text-ds-brand-600"}`}>{error ? <ShieldAlert className="size-6" /> : <CalendarDays className="size-6" />}</span><h2 className="mt-5 font-bold text-ds-neutral-950">{title}</h2><p className="mt-2 max-w-md text-sm leading-7 text-ds-neutral-600">{text}</p></div>; }
