import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Clock3, LogIn, LogOut, MapPin, MonitorSmartphone, ShieldAlert, UsersRound } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { FormField } from "@/components/design-system";

const modeLabels = { onsite: "من مقر العمل", remote: "عن بُعد" } as const;
type WorkMode = keyof typeof modeLabels;

function formatTime(value: Date | string | null | undefined) {
  return value ? new Intl.DateTimeFormat("ar-SA", { hour: "2-digit", minute: "2-digit" }).format(new Date(value)) : "—";
}

export default function Attendance() {
  const utils = trpc.useUtils();
  const { data: mine, isLoading: isMineLoading, isError: mineError, error: mineIssue } = trpc.attendance.mine.useQuery();
  const { data: overview } = trpc.attendance.overview.useQuery({});
  const [workMode, setWorkMode] = useState<WorkMode>("onsite");
  const [note, setNote] = useState("");
  const refresh = () => { utils.attendance.mine.invalidate(); utils.attendance.overview.invalidate(); };
  const checkIn = trpc.attendance.checkIn.useMutation({ onSuccess: () => { toast.success("تم تسجيل الحضور"); setNote(""); refresh(); }, onError: issue => toast.error("تعذر تسجيل الحضور", { description: issue.message }) });
  const checkOut = trpc.attendance.checkOut.useMutation({ onSuccess: () => { toast.success("تم تسجيل الانصراف"); refresh(); }, onError: issue => toast.error("تعذر تسجيل الانصراف", { description: issue.message }) });
  const completed = overview?.filter(item => item.entry.status === "completed").length ?? 0;

  return <DashboardLayout><div dir="rtl" className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold text-ds-brand-400">المرحلة 15 · القوى العاملة</p><h1 className="mt-2 text-3xl font-bold text-ds-brand-950">الدوام اليومي</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-ds-neutral-600">سجل حضور مرن داخل المنصة، مع عرض شخصي للموظف ونطاق متابعة يتبع دور المسؤول أو المدير.</p></div><span className="rounded-full bg-ds-success-soft px-3 py-1.5 text-xs font-bold text-ds-brand-600">توقيت الرياض التشغيلي</span></div>
    {isMineLoading ? <div className="mt-8 grid gap-4 md:grid-cols-2"><Skeleton className="h-72 rounded-3xl" /><Skeleton className="h-72 rounded-3xl" /></div> : mineError ? <StateCard title="تعذر تحميل سجل الدوام" text={mineIssue.message} error /> : <><section className="mt-8 grid gap-4 md:grid-cols-[1.15fr_.85fr]"><article className="rounded-3xl border border-ds-neutral-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><span className="flex size-11 items-center justify-center rounded-2xl bg-ds-brand-100 text-ds-brand-600"><Clock3 className="size-5" /></span><h2 className="mt-4 text-xl font-bold text-ds-neutral-950">دوامي اليوم</h2><p className="mt-2 text-sm text-ds-neutral-600">{mine ? mine.status === "completed" ? "تم تسجيل الحضور والانصراف." : "حضور مسجل بانتظار الانصراف." : "لم يُسجل حضور لهذا اليوم بعد."}</p></div>{mine && <span className={`rounded-full px-3 py-1 text-xs font-bold ${mine.status === "completed" ? "bg-ds-brand-100 text-ds-brand-600" : "bg-ds-warning-soft text-ds-warning"}`}>{mine.status === "completed" ? "مكتمل" : "قيد الدوام"}</span>}</div>{mine ? <div className="mt-6 grid grid-cols-3 gap-3 border-t border-ds-neutral-100 pt-5"><Fact label="الحضور" value={formatTime(mine.checkInAt)} /><Fact label="الانصراف" value={formatTime(mine.checkOutAt)} /><Fact label="النمط" value={modeLabels[mine.workMode]} /></div> : <div className="mt-6 grid gap-4"><div className="grid gap-4 sm:grid-cols-2"><FormField label="نمط العمل"><Select value={workMode} onValueChange={value => setWorkMode(value as WorkMode)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="onsite">من مقر العمل</SelectItem><SelectItem value="remote">عن بُعد</SelectItem></SelectContent></Select></FormField><div className="rounded-2xl bg-ds-neutral-50 p-4 text-xs leading-6 text-ds-neutral-600">يُسجل الوقت الحالي كتوقيت نظام تشغيلي، ولا يمكن إنشاء أكثر من سجل واحد لليوم.</div></div><FormField label="ملاحظة اختيارية"><Textarea value={note} onChange={event => setNote(event.target.value)} placeholder="مثال: زيارة ميدانية صباحاً" /></FormField><Button onClick={() => checkIn.mutate({ workMode, ...(note.trim() ? { note: note.trim() } : {}) })} disabled={checkIn.isPending} className="h-11 rounded-xl bg-ds-brand-800"><LogIn className="ml-2 size-4" />تسجيل الحضور</Button></div>}{mine?.status === "open" && <Button onClick={() => checkOut.mutate()} disabled={checkOut.isPending} variant="outline" className="mt-6 h-10 w-full rounded-xl border-ds-brand-200 text-ds-brand-600"><LogOut className="ml-2 size-4" />تسجيل الانصراف</Button>}</article>
      <article className="rounded-3xl bg-ds-brand-1000 p-6 text-white"><div className="flex size-11 items-center justify-center rounded-2xl bg-white/10 text-ds-gold-soft"><UsersRound className="size-5" /></div><h2 className="mt-5 text-xl font-bold">متابعة اليوم</h2><p className="mt-2 text-sm leading-7 text-ds-brand-200">يعرض النطاق حسب الصلاحية: الشركة للمسؤول والموارد البشرية، والفريق المباشر للمدير، وسجل الموظف لنفسه.</p><div className="mt-7 grid grid-cols-2 gap-3"><Metric label="سجلات النطاق" value={overview?.length ?? 0} /><Metric label="دوام مكتمل" value={completed} /></div><div className="mt-6 rounded-2xl border border-white/10 bg-white/5 p-3 text-xs leading-6 text-ds-brand-200"><MapPin className="ml-1 inline size-3.5" />لا يتتبع الموقع الجغرافي أو البصمة في هذا الإصدار.</div></article></section>
      <section className="mt-6 rounded-3xl border border-ds-neutral-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><span className="flex size-9 items-center justify-center rounded-xl bg-ds-success-soft text-ds-brand-600"><MonitorSmartphone className="size-4" /></span><div><h2 className="font-bold text-ds-neutral-950">سجل الدوام ضمن نطاقك</h2><p className="mt-1 text-xs text-ds-neutral-600">تُعرض الحقول التشغيلية الأساسية فقط.</p></div></div>{overview?.length ? <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[620px] text-right text-sm"><thead className="border-b border-ds-neutral-100 text-xs text-ds-neutral-600"><tr><th className="px-3 py-3">الموظف</th><th className="px-3 py-3">نمط العمل</th><th className="px-3 py-3">الحضور</th><th className="px-3 py-3">الانصراف</th><th className="px-3 py-3">الحالة</th></tr></thead><tbody>{overview.map(item => <tr key={item.entry.id} className="border-b border-ds-neutral-100 last:border-0"><td className="px-3 py-4 font-bold text-ds-brand-900">{item.user.name || "موظف"}</td><td className="px-3 py-4 text-ds-neutral-600">{modeLabels[item.entry.workMode]}</td><td className="px-3 py-4 text-ds-neutral-600">{formatTime(item.entry.checkInAt)}</td><td className="px-3 py-4 text-ds-neutral-600">{formatTime(item.entry.checkOutAt)}</td><td className="px-3 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${item.entry.status === "completed" ? "bg-ds-brand-100 text-ds-brand-600" : "bg-ds-warning-soft text-ds-warning"}`}>{item.entry.status === "completed" ? "مكتمل" : "قيد الدوام"}</span></td></tr>)}</tbody></table></div> : <div className="mt-5 rounded-2xl bg-ds-neutral-50 px-4 py-8 text-center text-sm text-ds-neutral-600">لا توجد سجلات دوام في نطاقك لهذا اليوم.</div>}</section></>}
  </div></DashboardLayout>;
}

function Fact({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-ds-neutral-500">{label}</p><p className="mt-2 font-bold text-ds-brand-900">{value}</p></div>; }
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-2xl bg-white/10 p-3"><p className="text-[11px] text-ds-neutral-300">{label}</p><p className="mt-2 text-2xl font-bold text-ds-warning-soft">{value}</p></div>; }
function StateCard({ title, text, error = false }: { title: string; text: string; error?: boolean }) { return <div className="mt-8 flex min-h-72 flex-col items-center justify-center rounded-3xl border border-ds-neutral-200 bg-white px-6 text-center"><span className={`flex size-14 items-center justify-center rounded-3xl ${error ? "bg-ds-danger-soft text-ds-danger" : "bg-ds-success-soft text-ds-brand-600"}`}>{error ? <ShieldAlert className="size-6" /> : <Clock3 className="size-6" />}</span><h2 className="mt-5 font-bold text-ds-neutral-950">{title}</h2><p className="mt-2 max-w-md text-sm leading-6 text-ds-neutral-600">{text}</p></div>; }
