import DashboardLayout from "@/components/DashboardLayout";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { ShieldAlert, ShieldCheck } from "lucide-react";

const categoryLabels = { recruitment: "التوظيف", attendance: "الدوام", training: "التدريب", approval: "الموافقات", account: "الحسابات", permission: "الصلاحيات", leave: "الإجازات", document: "الوثائق" } as const;

export default function AuditLog() {
  const { data, isLoading, isError, error } = trpc.audit.list.useQuery({ limit: 100 });
  return <DashboardLayout><div dir="rtl" className="mx-auto max-w-6xl"><div><p className="text-xs font-bold text-[#5d8d70]">الأمن والموثوقية</p><h1 className="mt-2 text-3xl font-bold text-[#1d4532]">سجل التدقيق</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-[#748178]">يسجل الأحداث الإدارية والتشغيلية الموجزة داخل الشركة من دون كلمات مرور أو محتوى ملاحظات داخلي حساس.</p></div>{isLoading ? <div className="mt-8 grid gap-3">{[1,2,3,4].map(item => <Skeleton key={item} className="h-20 rounded-2xl" />)}</div> : isError ? <StateCard title="تعذر تحميل سجل التدقيق" text={error.message} error /> : data?.length ? <section className="mt-8 overflow-hidden rounded-3xl border border-[#dfe9e1] bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-right text-sm"><thead className="border-b border-[#edf1ed] bg-[#f8faf8] text-xs text-[#718075]"><tr><th className="px-5 py-4">الوقت</th><th className="px-5 py-4">الفاعل</th><th className="px-5 py-4">الفئة</th><th className="px-5 py-4">الحدث</th><th className="px-5 py-4">الملخص</th></tr></thead><tbody>{data.map(item => <tr key={item.event.id} className="border-b border-[#f0f3f0] last:border-0"><td className="px-5 py-4 text-[#718075]">{new Intl.DateTimeFormat("ar-SA", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.event.createdAt))}</td><td className="px-5 py-4 font-bold text-[#385545]">{item.actor?.name || "نظام أو حساب محذوف"}</td><td className="px-5 py-4"><span className="rounded-full bg-[#e8f3e9] px-2.5 py-1 text-xs font-bold text-[#347950]">{categoryLabels[item.event.category]}</span></td><td className="px-5 py-4 text-[#52675a]">{item.event.action}</td><td className="px-5 py-4 text-[#52675a]">{item.event.summary}</td></tr>)}</tbody></table></div></section> : <StateCard title="لا توجد أحداث تدقيق بعد" text="ستظهر هنا الأحداث الجديدة المتعلقة بالتوظيف والدوام والعمليات الحساسة ضمن الشركة." />}</div></DashboardLayout>;
}

function StateCard({ title, text, error = false }: { title: string; text: string; error?: boolean }) { return <div className="mt-8 flex min-h-72 flex-col items-center justify-center rounded-3xl border border-[#dfe9e1] bg-white px-6 text-center"><span className={`flex size-14 items-center justify-center rounded-3xl ${error ? "bg-[#fdecea] text-[#a94e48]" : "bg-[#eaf3eb] text-[#357b53]"}`}>{error ? <ShieldAlert className="size-6" /> : <ShieldCheck className="size-6" />}</span><h2 className="mt-5 font-bold text-[#294535]">{title}</h2><p className="mt-2 max-w-md text-sm leading-6 text-[#748178]">{text}</p></div>; }
