import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { Eye, FileText, Plus, ShieldAlert, Upload } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

const statusLabels = { draft: "مسودة", active: "ساري تشغيلياً", ended: "منتهٍ", archived: "مؤرشف" } as const;
const categoryLabels = { contract_attachment: "مرفق عقد", employee_document: "وثيقة موظف", other: "أخرى" } as const;

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div><label className="mb-2 block text-xs font-bold text-[#61756a]">{label}</label>{children}</div>; }
function formatDate(value?: Date | null) { return value ? new Intl.DateTimeFormat("ar-SA", { dateStyle: "medium" }).format(new Date(value)) : "—"; }
function readAsDataUrl(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error("تعذر قراءة الملف")); reader.readAsDataURL(file); }); }

export default function ContractsDocuments() {
  const utils = trpc.useUtils();
  const { data, isLoading, isError, error } = trpc.contracts.overview.useQuery();
  const [contractOpen, setContractOpen] = useState(false); const [previewOpen, setPreviewOpen] = useState(false);
  const [employeeId, setEmployeeId] = useState("none"); const [contractReference, setContractReference] = useState(""); const [title, setTitle] = useState(""); const [status, setStatus] = useState<keyof typeof statusLabels>("draft"); const [supersedesContractId, setSupersedesContractId] = useState("none"); const [startAt, setStartAt] = useState(""); const [endAt, setEndAt] = useState("");
  const [documentEmployeeId, setDocumentEmployeeId] = useState("none"); const [contractId, setContractId] = useState("none"); const [category, setCategory] = useState<keyof typeof categoryLabels>("employee_document"); const [file, setFile] = useState<File | null>(null); const [previewUrl, setPreviewUrl] = useState("");
  useEffect(() => { if (!file) { setPreviewUrl(""); return; } const url = URL.createObjectURL(file); setPreviewUrl(url); return () => URL.revokeObjectURL(url); }, [file]);
  const createContract = trpc.contracts.createContract.useMutation({ onSuccess: () => { toast.success("تم حفظ سجل العقد التشغيلي"); setContractOpen(false); setContractReference(""); setTitle(""); utils.contracts.overview.invalidate(); }, onError: issue => toast.error("تعذر حفظ سجل العقد", { description: issue.message }) });
  const uploadDocument = trpc.contracts.uploadDocument.useMutation({ onSuccess: () => { toast.success("تم حفظ الوثيقة"); setPreviewOpen(false); setFile(null); setContractId("none"); utils.contracts.overview.invalidate(); }, onError: issue => toast.error("تعذر حفظ الوثيقة", { description: issue.message }) });
  const openDocument = trpc.contracts.openDocument.useMutation({ onSuccess: document => window.open(document.url, "_blank", "noopener,noreferrer"), onError: issue => toast.error("تعذر فتح الوثيقة", { description: issue.message }) });
  const saveContract = () => createContract.mutate({ employeeUserId: Number(employeeId), contractReference: contractReference.trim(), title: title.trim(), status, ...(supersedesContractId !== "none" ? { supersedesContractId: Number(supersedesContractId) } : {}), ...(startAt ? { startAt: new Date(`${startAt}T00:00:00`) } : {}), ...(endAt ? { endAt: new Date(`${endAt}T00:00:00`) } : {}) });
  const saveDocument = async () => { if (!file || documentEmployeeId === "none") return; try { const fileContentBase64 = await readAsDataUrl(file); uploadDocument.mutate({ employeeUserId: Number(documentEmployeeId), ...(contractId !== "none" ? { contractId: Number(contractId) } : {}), category, fileName: file.name, mimeType: file.type, fileContentBase64 }); } catch (issue) { toast.error("تعذر تجهيز الملف", { description: issue instanceof Error ? issue.message : "حاول مجدداً" }); } };
  const eligibleContracts = data?.contracts.filter(item => item.employeeUserId === Number(documentEmployeeId)) ?? [];
  const priorContracts = data?.contracts.filter(item => item.employeeUserId === Number(employeeId)) ?? [];
  return <DashboardLayout><main dir="rtl" className="mx-auto max-w-6xl"><section className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold text-[#5d8d70]">HR Core · إدارة الوثائق</p><h1 className="mt-2 text-3xl font-bold text-[#1d4532]">العقود والوثائق</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-[#748178]">سجلات تشغيلية وملفات PDF أو صور محفوظة داخل الشركة. لا تمثل سجلات العقود نصاً قانونياً أو توقيعاً إلكترونياً.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => setContractOpen(true)} className="rounded-xl border-[#d6e4d8] text-[#356e50]"><Plus className="ml-2 size-4" />سجل عقد</Button><Button onClick={() => document.getElementById("document-file-picker")?.click()} className="rounded-xl bg-[#1f5b45]"><Upload className="ml-2 size-4" />رفع وثيقة</Button></div></section>
    {isLoading ? <div className="mt-8 grid gap-4 md:grid-cols-3">{[1,2,3].map(item => <Skeleton key={item} className="h-40 rounded-3xl" />)}</div> : isError ? <State title="تعذر تحميل العقود والوثائق" text={error.message} error /> : <><section className="mt-8 rounded-3xl border border-[#dfe9e1] bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold text-[#294535]">سجلات العقود التشغيلية</h2><p className="mt-1 text-xs text-[#718075]">لا تشمل بنوداً قانونية أو اعتماداً إلكترونياً.</p></div><span className="rounded-full bg-[#e8f3e9] px-3 py-1 text-xs font-bold text-[#367850]">{data?.contracts.length || 0} سجل</span></div>{data?.contracts.length ? <div className="mt-5 grid gap-3 md:grid-cols-2">{data.contracts.map(contract => <article key={contract.id} className="rounded-2xl border border-[#edf1ed] p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-[#2d4938]">{contract.title}</p><p className="mt-1 text-xs text-[#718075]">{contract.contractReference} · إصدار {contract.versionNumber} · {data.employees.find(employee => employee.id === contract.employeeUserId)?.name || "موظف"}</p></div><span className="rounded-full bg-[#f2f5f1] px-2.5 py-1 text-xs font-bold text-[#617568]">{statusLabels[contract.status]}</span></div><p className="mt-3 text-xs text-[#7c8a81]">من {formatDate(contract.startAt)} إلى {formatDate(contract.endAt)}{contract.supersedesContractId ? ` · يحل محل سجل #${contract.supersedesContractId}` : ""}</p></article>)}</div> : <p className="mt-6 text-sm text-[#758278]">لا توجد سجلات عقود بعد.</p>}</section>
    <section className="mt-5 rounded-3xl border border-[#dfe9e1] bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div><h2 className="font-bold text-[#294535]">الوثائق المحفوظة</h2><p className="mt-1 text-xs text-[#718075]">يصدر رابط الفتح من الخادم بعد التحقق من الصلاحية، وتُسجل عملية الوصول.</p></div><span className="rounded-full bg-[#edf4ee] px-3 py-1 text-xs font-bold text-[#367850]">{data?.documents.length || 0} وثيقة</span></div>{data?.documents.length ? <div className="mt-5 grid gap-3 md:grid-cols-2">{data.documents.map(documentItem => <article key={documentItem.id} className="flex items-center justify-between gap-3 rounded-2xl border border-[#edf1ed] p-4"><div className="min-w-0"><p className="truncate font-bold text-[#2d4938]">{documentItem.fileName}</p><p className="mt-1 text-xs text-[#718075]">{categoryLabels[documentItem.category]} · {Math.ceil(documentItem.sizeBytes / 1024)} ك.ب</p></div><Button variant="outline" size="sm" disabled={openDocument.isPending} onClick={() => openDocument.mutate({ documentId: documentItem.id })} className="shrink-0 rounded-xl border-[#d7e4d8] text-[#356e50]"><Eye className="ml-1.5 size-3.5" />فتح</Button></article>)}</div> : <p className="mt-6 text-sm text-[#758278]">لا توجد وثائق محفوظة بعد.</p>}</section></>}
    <input id="document-file-picker" type="file" accept="application/pdf,image/png,image/jpeg" className="sr-only" onChange={event => { const picked = event.target.files?.[0] || null; if (!picked) return; if (picked.size > 5 * 1024 * 1024) { toast.error("الحد الأقصى 5 ميغابايت"); return; } if (!["application/pdf", "image/png", "image/jpeg"].includes(picked.type)) { toast.error("استخدم PDF أو PNG أو JPEG فقط"); return; } setFile(picked); setPreviewOpen(true); }} />
    <Dialog open={contractOpen} onOpenChange={setContractOpen}><DialogContent dir="rtl" className="sm:max-w-xl"><DialogHeader><DialogTitle>سجل عقد تشغيلي</DialogTitle><DialogDescription>بيانات إدارية داخلية، وليست قالباً قانونياً أو توقيعاً. الإصدار السابق اختياري ويُستخدم للتتبع التشغيلي فقط.</DialogDescription></DialogHeader><div className="grid gap-4 py-3"><Field label="الموظف"><Select value={employeeId} onValueChange={value => { setEmployeeId(value); setSupersedesContractId("none"); }}><SelectTrigger><SelectValue placeholder="اختر موظفاً" /></SelectTrigger><SelectContent>{data?.employees.map(employee => <SelectItem key={employee.id} value={String(employee.id)}>{employee.name || "موظف"}</SelectItem>)}</SelectContent></Select></Field><Field label="إصدار سابق (اختياري)"><Select value={supersedesContractId} onValueChange={setSupersedesContractId} disabled={employeeId === "none"}><SelectTrigger><SelectValue placeholder="يبدأ الإصدار من 1 إن لم يُحدد" /></SelectTrigger><SelectContent><SelectItem value="none">لا يوجد إصدار سابق</SelectItem>{priorContracts.map(contract => <SelectItem key={contract.id} value={String(contract.id)}>{contract.contractReference} · إصدار {contract.versionNumber}</SelectItem>)}</SelectContent></Select></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="مرجع العقد"><Input value={contractReference} onChange={event => setContractReference(event.target.value)} placeholder="CTR-001" /></Field><Field label="العنوان"><Input value={title} onChange={event => setTitle(event.target.value)} placeholder="سجل عقد موظف" /></Field></div><div className="grid gap-4 sm:grid-cols-3"><Field label="الحالة"><Select value={status} onValueChange={value => setStatus(value as keyof typeof statusLabels)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{Object.entries(statusLabels).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></Field><Field label="تاريخ البداية"><Input type="date" value={startAt} onChange={event => setStartAt(event.target.value)} /></Field><Field label="تاريخ النهاية"><Input type="date" value={endAt} onChange={event => setEndAt(event.target.value)} /></Field></div></div><DialogFooter><Button variant="outline" onClick={() => setContractOpen(false)}>إلغاء</Button><Button onClick={saveContract} disabled={createContract.isPending || employeeId === "none" || contractReference.trim().length < 2 || title.trim().length < 2} className="bg-[#1f5b45]">حفظ السجل</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={previewOpen} onOpenChange={setPreviewOpen}><DialogContent dir="rtl" className="max-h-[92vh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>معاينة الوثيقة قبل الحفظ</DialogTitle><DialogDescription>تحقق من الملف والموظف والتصنيف قبل الإرسال. لا يتم رفع الملف إلا بعد تأكيد الحفظ.</DialogDescription></DialogHeader>{file && <div className="grid gap-4 py-3"><div className="rounded-2xl border border-[#e1e9e2] bg-[#fafcf9] p-3 text-xs text-[#61756a]"><b>{file.name}</b> · {Math.ceil(file.size / 1024)} ك.ب · {file.type}</div>{file.type === "application/pdf" ? <iframe title="معاينة PDF" src={previewUrl} className="h-[420px] w-full rounded-2xl border border-[#dbe5dc] bg-white" /> : <img src={previewUrl} alt="معاينة الوثيقة قبل الحفظ" className="max-h-[420px] w-full rounded-2xl border border-[#dbe5dc] object-contain" />}<div className="grid gap-4 sm:grid-cols-3"><Field label="الموظف"><Select value={documentEmployeeId} onValueChange={setDocumentEmployeeId}><SelectTrigger><SelectValue placeholder="اختر موظفاً" /></SelectTrigger><SelectContent>{data?.employees.map(employee => <SelectItem key={employee.id} value={String(employee.id)}>{employee.name || "موظف"}</SelectItem>)}</SelectContent></Select></Field><Field label="التصنيف"><Select value={category} onValueChange={value => setCategory(value as keyof typeof categoryLabels)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{Object.entries(categoryLabels).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></Field><Field label="ربط بعقد (اختياري)"><Select value={contractId} onValueChange={setContractId}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">دون ربط</SelectItem>{eligibleContracts.map(contract => <SelectItem key={contract.id} value={String(contract.id)}>{contract.contractReference}</SelectItem>)}</SelectContent></Select></Field></div></div>}<DialogFooter><Button variant="outline" onClick={() => setPreviewOpen(false)}>العودة للتعديل</Button><Button onClick={saveDocument} disabled={uploadDocument.isPending || !file || documentEmployeeId === "none"} className="bg-[#1f5b45]"><Upload className="ml-2 size-4" />حفظ الوثيقة</Button></DialogFooter></DialogContent></Dialog>
  </main></DashboardLayout>;
}

function State({ title, text, error = false }: { title: string; text: string; error?: boolean }) { return <div className="mt-8 flex min-h-72 flex-col items-center justify-center rounded-3xl border border-[#dfe9e1] bg-white px-6 text-center"><span className={`flex size-14 items-center justify-center rounded-3xl ${error ? "bg-[#fdecea] text-[#a94e48]" : "bg-[#eaf3eb] text-[#357b53]"}`}>{error ? <ShieldAlert className="size-6" /> : <FileText className="size-6" />}</span><h2 className="mt-5 font-bold text-[#294535]">{title}</h2><p className="mt-2 max-w-md text-sm leading-6 text-[#748178]">{text}</p></div>; }
