import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, CircleGauge, Flag, Plus, ShieldAlert } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const statusLabels = { not_started: "لم يبدأ", in_progress: "قيد التقدم", completed: "مكتمل", cancelled: "ملغى" } as const;
function employeeName(employees: Array<{ id: number; name?: string | null }>, id: number) { return employees.find(item => item.id === id)?.name || "موظف"; }

export default function GoalsPerformance() {
  const utils = trpc.useUtils(); const { data, isLoading, isError, error } = trpc.goals.overview.useQuery();
  const [createOpen, setCreateOpen] = useState(false); const [progressOpen, setProgressOpen] = useState(false); const [selectedGoalId, setSelectedGoalId] = useState<number | null>(null);
  const [employeeId, setEmployeeId] = useState("none"); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [targetAt, setTargetAt] = useState(""); const [progress, setProgress] = useState("0"); const [note, setNote] = useState(""); const [trainingProgramId, setTrainingProgramId] = useState("none");
  const createGoal = trpc.goals.create.useMutation({ onSuccess: () => { toast.success("تم حفظ الهدف الداخلي"); setCreateOpen(false); setEmployeeId("none"); setTitle(""); setDescription(""); setTargetAt(""); utils.goals.overview.invalidate(); }, onError: issue => toast.error("تعذر حفظ الهدف", { description: issue.message }) });
  const addProgress = trpc.goals.addProgress.useMutation({ onSuccess: () => { toast.success("تم تحديث تقدم الهدف"); setProgressOpen(false); setProgress("0"); setNote(""); setTrainingProgramId("none"); utils.goals.overview.invalidate(); }, onError: issue => toast.error("تعذر تحديث التقدم", { description: issue.message }) });
  const selectedGoal = data?.goals.find(goal => goal.id === selectedGoalId) || null;
  const beginProgress = (goalId: number, current: number) => { setSelectedGoalId(goalId); setProgress(String(current)); setProgressOpen(true); };
  const create = () => createGoal.mutate({ employeeUserId: Number(employeeId), title: title.trim(), ...(description.trim() ? { description: description.trim() } : {}), ...(targetAt ? { targetAt: new Date(`${targetAt}T00:00:00`) } : {}) });
  const saveProgress = () => selectedGoalId && addProgress.mutate({ goalId: selectedGoalId, progressPercent: Number(progress), ...(note.trim() ? { note: note.trim() } : {}), ...(trainingProgramId !== "none" ? { trainingProgramId: Number(trainingProgramId) } : {}) });
  return <DashboardLayout><main dir="rtl" className="mx-auto max-w-6xl"><section className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold text-[#5d8d70]">HR Core · نمو داخلي</p><h1 className="mt-2 text-3xl font-bold text-[#1d4532]">الأهداف والأداء</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-[#748178]">أهداف تشغيلية وتحديثات تقدم مرتبطة بسياق التدريب. لا تمثل تقييماً مالياً أو قراراً وظيفياً أو بديلًا لسياسة أداء معتمدة.</p></div><Button onClick={() => setCreateOpen(true)} className="rounded-xl bg-[#1f5b45]"><Plus className="ml-2 size-4" />إضافة هدف</Button></section>
    {isLoading ? <div className="mt-8 grid gap-4 md:grid-cols-2"><div className="h-64 animate-pulse rounded-3xl bg-[#eef5ef]" /><div className="h-64 animate-pulse rounded-3xl bg-[#eef5ef]" /></div> : isError ? <State title="تعذر تحميل الأهداف" text={error.message} /> : <section className="mt-8 grid gap-5 lg:grid-cols-2">{data?.goals.length ? data.goals.map(goal => { const updates = data.updates.filter(update => update.goalId === goal.id); return <article key={goal.id} className="rounded-3xl border border-[#dfe9e1] bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-[#294535]">{goal.title}</p><p className="mt-1 text-xs text-[#718075]">{employeeName(data.employees, goal.employeeUserId)} · {goal.targetAt ? `الهدف: ${new Intl.DateTimeFormat("ar-SA", { dateStyle: "medium" }).format(new Date(goal.targetAt))}` : "دون تاريخ مستهدف"}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${goal.status === "completed" ? "bg-[#e5f4e8] text-[#367850]" : "bg-[#f2f5f1] text-[#687b6e]"}`}>{statusLabels[goal.status]}</span></div>{goal.description && <p className="mt-4 text-sm leading-6 text-[#61756a]">{goal.description}</p>}<div className="mt-5"><div className="flex items-center justify-between text-xs font-bold text-[#587162]"><span>التقدم</span><span>{goal.progressPercent}%</span></div><div className="mt-2 h-2.5 overflow-hidden rounded-full bg-[#edf3ed]"><div className="h-full rounded-full bg-[#368556]" style={{ width: `${goal.progressPercent}%` }} /></div></div><div className="mt-5 flex items-center justify-between gap-3"><p className="text-xs text-[#77867c]">{updates.length} تحديثات تقدم</p><Button size="sm" variant="outline" onClick={() => beginProgress(goal.id, goal.progressPercent)} disabled={goal.status === "cancelled"} className="rounded-xl border-[#d5e4d7] text-[#356e50]"><CircleGauge className="ml-1.5 size-3.5" />تحديث التقدم</Button></div>{updates.length ? <div className="mt-4 border-t border-[#eef2ee] pt-3 text-xs text-[#718075]">آخر تحديث: {updates[0]?.progressPercent}%{updates[0]?.trainingProgramId ? ` · ${data.programs.find(program => program.id === updates[0]?.trainingProgramId)?.title || "تدريب مرتبط"}` : ""}</div> : null}</article>; }) : <State title="لا توجد أهداف داخلية" text="أضف هدفاً مرتبطاً بموظف ثم حدّث تقدمه تدريجياً، مع إمكانية ربط التحديث بمسار تدريب." />}</section>}
    <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent dir="rtl" className="sm:max-w-lg"><DialogHeader><DialogTitle>إضافة هدف داخلي</DialogTitle><DialogDescription>هدف تشغيلي للمتابعة والتطوير فقط، وليس تقييماً مالياً أو قراراً وظيفياً.</DialogDescription></DialogHeader><div className="grid gap-4 py-3"><Field label="الموظف"><Select value={employeeId} onValueChange={setEmployeeId}><SelectTrigger><SelectValue placeholder="اختر موظفاً" /></SelectTrigger><SelectContent>{data?.employees.map(employee => <SelectItem key={employee.id} value={String(employee.id)}>{employee.name || "موظف"}</SelectItem>)}</SelectContent></Select></Field><Field label="عنوان الهدف"><Input value={title} onChange={event => setTitle(event.target.value)} placeholder="مثال: إتمام مسار تطوير داخلي" /></Field><Field label="وصف مختصر (اختياري)"><Textarea value={description} onChange={event => setDescription(event.target.value)} placeholder="نطاق تشغيلي موجز" /></Field><Field label="تاريخ مستهدف (اختياري)"><Input type="date" value={targetAt} onChange={event => setTargetAt(event.target.value)} /></Field></div><DialogFooter><Button variant="outline" onClick={() => setCreateOpen(false)}>إلغاء</Button><Button onClick={create} disabled={createGoal.isPending || employeeId === "none" || title.trim().length < 2} className="bg-[#1f5b45]">حفظ الهدف</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={progressOpen} onOpenChange={setProgressOpen}><DialogContent dir="rtl" className="sm:max-w-lg"><DialogHeader><DialogTitle>تحديث تقدم الهدف</DialogTitle><DialogDescription>{selectedGoal?.title || ""} — يسجل التحديث ضمن المتابعة الداخلية فقط.</DialogDescription></DialogHeader><div className="grid gap-4 py-3"><Field label="نسبة التقدم"><Input type="number" min="0" max="100" value={progress} onChange={event => setProgress(event.target.value)} /></Field><Field label="ربط بمسار تدريب (اختياري)"><Select value={trainingProgramId} onValueChange={setTrainingProgramId}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">دون ربط</SelectItem>{data?.programs.map(program => <SelectItem key={program.id} value={String(program.id)}>{program.title}</SelectItem>)}</SelectContent></Select></Field><Field label="ملاحظة متابعة (اختيارية)"><Textarea value={note} onChange={event => setNote(event.target.value)} placeholder="ملخص موجز للتقدم" /></Field></div><DialogFooter><Button variant="outline" onClick={() => setProgressOpen(false)}>إلغاء</Button><Button onClick={saveProgress} disabled={addProgress.isPending || !selectedGoalId || Number(progress) < 0 || Number(progress) > 100} className="bg-[#1f5b45]"><CheckCircle2 className="ml-2 size-4" />حفظ التقدم</Button></DialogFooter></DialogContent></Dialog>
  </main></DashboardLayout>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div><label className="mb-2 block text-xs font-bold text-[#61756a]">{label}</label>{children}</div>; }
function State({ title, text }: { title: string; text: string }) { return <div className="col-span-full flex min-h-64 flex-col items-center justify-center rounded-3xl border border-[#dfe9e1] bg-white px-6 text-center"><Flag className="size-8 text-[#5b8a6c]" /><h2 className="mt-4 font-bold text-[#294535]">{title}</h2><p className="mt-2 max-w-md text-sm leading-6 text-[#748178]">{text}</p></div>; }
