import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { exportGoalsCsv, exportGoalsPdf, goalExportLabels, type GoalExportColumn } from "@/lib/goalExport";
import { AlertTriangle, CalendarClock, CheckCircle2, CircleGauge, Download, Flag, Plus, Sparkles } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { FormField } from "@/components/design-system";

const statusLabels = { not_started: "لم يبدأ", in_progress: "قيد التقدم", completed: "مكتمل", cancelled: "ملغى" } as const;
function employeeName(employees: Array<{ id: number; name?: string | null }>, id: number) { return employees.find(item => item.id === id)?.name || "موظف"; }

export default function GoalsPerformance() {
  const utils = trpc.useUtils(); const { data, isLoading, isError, error } = trpc.goals.overview.useQuery();
  const [createOpen, setCreateOpen] = useState(false); const [progressOpen, setProgressOpen] = useState(false); const [exportOpen, setExportOpen] = useState(false); const [selectedGoalId, setSelectedGoalId] = useState<number | null>(null);
  const [employeeId, setEmployeeId] = useState("none"); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [targetAt, setTargetAt] = useState(""); const [progress, setProgress] = useState("0"); const [note, setNote] = useState(""); const [trainingProgramId, setTrainingProgramId] = useState("none"); const [dateFrom, setDateFrom] = useState(""); const [dateTo, setDateTo] = useState(""); const [departmentId, setDepartmentId] = useState("all"); const [columns, setColumns] = useState<Record<GoalExportColumn, boolean>>({ title: true, employee: true, department: true, status: true, progress: true, targetAt: true }); const [aiSummary, setAiSummary] = useState("");
  const createGoal = trpc.goals.create.useMutation({ onSuccess: () => { toast.success("تم حفظ الهدف الداخلي"); setCreateOpen(false); setEmployeeId("none"); setTitle(""); setDescription(""); setTargetAt(""); utils.goals.overview.invalidate(); }, onError: issue => toast.error("تعذر حفظ الهدف", { description: issue.message }) });
  const addProgress = trpc.goals.addProgress.useMutation({ onSuccess: () => { toast.success("تم تحديث تقدم الهدف"); setProgressOpen(false); setProgress("0"); setNote(""); setTrainingProgramId("none"); utils.goals.overview.invalidate(); }, onError: issue => toast.error("تعذر تحديث التقدم", { description: issue.message }) });
  const summarize = trpc.goals.summarize.useMutation({ onSuccess: result => setAiSummary(result.summary), onError: issue => toast.error("تعذر إنشاء التلخيص", { description: issue.message }) });
  const selectedGoal = data?.goals.find(goal => goal.id === selectedGoalId) || null;
  const beginProgress = (goalId: number, current: number) => { setSelectedGoalId(goalId); setProgress(String(current)); setProgressOpen(true); };
  const create = () => createGoal.mutate({ employeeUserId: Number(employeeId), title: title.trim(), ...(description.trim() ? { description: description.trim() } : {}), ...(targetAt ? { targetAt: new Date(`${targetAt}T00:00:00`) } : {}) });
  const saveProgress = () => selectedGoalId && addProgress.mutate({ goalId: selectedGoalId, progressPercent: Number(progress), ...(note.trim() ? { note: note.trim() } : {}), ...(trainingProgramId !== "none" ? { trainingProgramId: Number(trainingProgramId) } : {}) });
  const departments = Array.from(new Map((data?.employees ?? []).flatMap(employee => employee.department ? [[String(employee.department.id), employee.department.name] as const] : [])).entries());
  const filteredGoals = (data?.goals ?? []).filter(goal => { const employee = data?.employees.find(item => item.id === goal.employeeUserId); if (departmentId !== "all" && String(employee?.department?.id ?? "") !== departmentId) return false; const target = goal.targetAt ? new Date(goal.targetAt) : null; if (dateFrom && (!target || target < new Date(`${dateFrom}T00:00:00`))) return false; if (dateTo && (!target || target > new Date(`${dateTo}T23:59:59`))) return false; return true; });
  const activeGoals = filteredGoals.filter(goal => !["completed", "cancelled"].includes(goal.status));
  const completedGoals = filteredGoals.filter(goal => goal.status === "completed");
  const averageProgress = activeGoals.length ? Math.round(activeGoals.reduce((total, goal) => total + goal.progressPercent, 0) / activeGoals.length) : 0;
  const now = new Date();
  const overdueGoals = activeGoals.filter(goal => goal.targetAt && new Date(goal.targetAt) < now);
  const soonGoals = activeGoals.filter(goal => { if (!goal.targetAt) return false; const remaining = new Date(goal.targetAt).getTime() - now.getTime(); return remaining >= 0 && remaining <= 7 * 24 * 60 * 60 * 1000; });
  const exportRows = filteredGoals.map(goal => { const employee = data?.employees.find(item => item.id === goal.employeeUserId); return { title: goal.title, employee: employee?.name || "Employee", department: employee?.department?.name || "Unassigned", status: statusLabels[goal.status], progress: goal.progressPercent, targetAt: goal.targetAt ? new Intl.DateTimeFormat("en-CA", { dateStyle: "medium" }).format(new Date(goal.targetAt)) : "Not set" }; });
  const selectedColumns = (Object.keys(columns) as GoalExportColumn[]).filter(column => columns[column]);
  const timelineGoals = filteredGoals.filter(goal => goal.targetAt).sort((a, b) => new Date(a.targetAt!).getTime() - new Date(b.targetAt!).getTime());
  return <DashboardLayout><main dir="rtl" className="mx-auto max-w-6xl"><section className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold text-ds-brand-400">HR Core · نمو داخلي</p><h1 className="mt-2 text-3xl font-bold text-ds-brand-950">الأهداف والأداء</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-ds-neutral-600">أهداف تشغيلية وتحديثات تقدم مرتبطة بسياق التدريب. لا تمثل تقييماً مالياً أو قراراً وظيفياً أو بديلًا لسياسة أداء معتمدة.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => summarize.mutate({ ...(departmentId !== "all" ? { departmentId: Number(departmentId) } : {}), ...(dateFrom ? { dateFrom: new Date(`${dateFrom}T00:00:00`) } : {}), ...(dateTo ? { dateTo: new Date(`${dateTo}T23:59:59`) } : {}) })} disabled={!exportRows.length || summarize.isPending} className="rounded-xl border-ds-gold-soft text-ds-warning-strong"><Sparkles className="ml-2 size-4" />{summarize.isPending ? "جارٍ التلخيص" : "تلخيص ذكي"}</Button><Button variant="outline" onClick={() => setExportOpen(true)} disabled={!exportRows.length} className="rounded-xl border-ds-brand-300 text-ds-brand-700"><Download className="ml-2 size-4" />معاينة وتصدير</Button><Button onClick={() => setCreateOpen(true)} className="rounded-xl bg-ds-brand-800"><Plus className="ml-2 size-4" />إضافة هدف</Button></div></section>
    {!isLoading && !isError && data ? <><section aria-label="تصفية الأهداف" className="mt-7 grid gap-3 rounded-3xl border border-ds-neutral-200 bg-white p-4 md:grid-cols-3"><FormField label="القسم"><Select value={departmentId} onValueChange={setDepartmentId}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">كل الأقسام</SelectItem>{departments.map(([id, name]) => <SelectItem key={id} value={id}>{name}</SelectItem>)}</SelectContent></Select></FormField><FormField label="تاريخ الهدف من"><Input type="date" value={dateFrom} onChange={event => setDateFrom(event.target.value)} /></FormField><FormField label="تاريخ الهدف إلى"><Input type="date" value={dateTo} onChange={event => setDateTo(event.target.value)} /></FormField></section><section aria-label="ملخص تقدم الأهداف" className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><GoalMetric label="أهداف نشطة" value={activeGoals.length} hint="قيد المتابعة" tone="green" /><GoalMetric label="متوسط التقدم" value={`${averageProgress}%`} hint="للأهداف النشطة" tone="blue" /><GoalMetric label="أهداف مكتملة" value={completedGoals.length} hint="ضمن التصفية" tone="gold" /><GoalMetric label="تحتاج متابعة" value={overdueGoals.length + soonGoals.length} hint="متأخرة أو قريبة" tone="rose" /></section>{(overdueGoals.length || soonGoals.length) ? <section aria-live="polite" className="mt-5 rounded-3xl border border-ds-warning-border bg-ds-ivory p-5"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 size-5 text-ds-warning" /><div><h2 className="font-bold text-ds-warning-strong">تنبيهات متابعة الأهداف</h2><p className="mt-1 text-sm leading-6 text-ds-warning-strong">عرض إرشادي داخل اللوحة فقط؛ لا ينشئ إشعاراً تلقائياً ولا يترتب عليه أثر مالي أو إداري.</p><div className="mt-3 flex flex-wrap gap-2">{overdueGoals.map(goal => <span key={goal.id} className="rounded-full bg-white px-3 py-1 text-xs font-bold text-ds-warning">متأخر: {goal.title}</span>)}{soonGoals.map(goal => <span key={goal.id} className="rounded-full bg-white px-3 py-1 text-xs font-bold text-ds-warning">قريب: {goal.title}</span>)}</div></div></div></section> : null}</> : null}
    {isLoading ? <div className="mt-8 grid gap-4 md:grid-cols-2"><div className="h-64 animate-pulse rounded-3xl bg-ds-brand-50" /><div className="h-64 animate-pulse rounded-3xl bg-ds-brand-50" /></div> : isError ? <State title="تعذر تحميل الأهداف" text={error.message} /> : <section className="mt-8 grid gap-5 lg:grid-cols-2">{filteredGoals.length ? filteredGoals.map(goal => { const updates = data?.updates.filter(update => update.goalId === goal.id) ?? []; return <article key={goal.id} className="rounded-3xl border border-ds-neutral-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-ds-neutral-950">{goal.title}</p><p className="mt-1 text-xs text-ds-neutral-600">{employeeName(data?.employees ?? [], goal.employeeUserId)} · {goal.targetAt ? `الهدف: ${new Intl.DateTimeFormat("ar-SA", { dateStyle: "medium" }).format(new Date(goal.targetAt))}` : "دون تاريخ مستهدف"}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${goal.status === "completed" ? "bg-ds-brand-100 text-ds-brand-600" : "bg-ds-brand-50 text-ds-neutral-700"}`}>{statusLabels[goal.status]}</span></div>{goal.description && <p className="mt-4 text-sm leading-6 text-ds-neutral-700">{goal.description}</p>}<div className="mt-5"><div className="flex items-center justify-between text-xs font-bold text-ds-neutral-700"><span>التقدم</span><span>{goal.progressPercent}%</span></div><div className="mt-2 h-2.5 overflow-hidden rounded-full bg-ds-neutral-100"><div className="h-full rounded-full bg-ds-brand-600" style={{ width: `${goal.progressPercent}%` }} /></div></div><div className="mt-5 flex items-center justify-between gap-3"><p className="text-xs text-ds-neutral-600">{updates.length} تحديثات تقدم</p><Button size="sm" variant="outline" onClick={() => beginProgress(goal.id, goal.progressPercent)} disabled={goal.status === "cancelled"} className="rounded-xl border-ds-brand-200 text-ds-brand-700"><CircleGauge className="ml-1.5 size-3.5" />تحديث التقدم</Button></div>{updates.length ? <div className="mt-4 border-t border-ds-neutral-100 pt-3 text-xs text-ds-neutral-600">آخر تحديث: {updates[0]?.progressPercent}%{updates[0]?.trainingProgramId ? ` · ${data?.programs.find(program => program.id === updates[0]?.trainingProgramId)?.title || "تدريب مرتبط"}` : ""}</div> : null}</article>; }) : <State title="لا توجد أهداف مطابقة للتصفية" text="عدّل التاريخ أو القسم لعرض الأهداف المتاحة ضمن الشركة." />}</section>}
    {aiSummary ? <section aria-live="polite" className="mt-6 rounded-3xl border border-ds-warning-border bg-ds-ivory p-5"><div className="flex items-center gap-2 text-ds-warning-strong"><Sparkles className="size-4" /><h2 className="font-bold">ملخص ذكي للأهداف المفلترة</h2></div><p className="mt-3 whitespace-pre-line text-sm leading-7 text-ds-warning-tan">{aiSummary}</p><p className="mt-3 text-xs text-ds-warning-tan">يستند الملخص إلى بيانات التصفية الحالية ولا يمثل تقييماً أو قراراً وظيفياً.</p></section> : null}
    <section aria-label="الخط الزمني للأهداف" className="mt-8 rounded-3xl border border-ds-neutral-200 bg-white p-6"><div className="flex items-center justify-between gap-4"><div><h2 className="font-bold text-ds-neutral-950">الخط الزمني للاستحقاقات</h2><p className="mt-1 text-xs text-ds-neutral-600">يعرض فقط الأهداف ذات التاريخ المستهدف بعد تطبيق تصفية القسم والتاريخ.</p></div><span className="rounded-full bg-ds-success-soft px-3 py-1 text-xs font-bold text-ds-brand-600">{timelineGoals.length} أهداف مجدولة</span></div>{timelineGoals.length ? <div className="mt-5 space-y-4 border-r-2 border-ds-neutral-200 pr-5">{timelineGoals.map(goal => { const due = new Date(goal.targetAt!); const overdue = due < now && goal.status !== "completed"; const soon = !overdue && due.getTime() - now.getTime() <= 7 * 24 * 60 * 60 * 1000; return <article key={goal.id} title={`التقدم: ${goal.progressPercent}% | الاستحقاق: ${new Intl.DateTimeFormat("ar-SA", { dateStyle: "medium" }).format(due)} | الحالة: ${overdue ? "متأخر" : soon ? "قريب" : "مجدول"}`} className={`relative rounded-2xl bg-ds-neutral-50 p-4 ${overdue ? "ring-1 ring-ds-danger-border" : soon ? "ring-1 ring-ds-warning-border" : ""}`}><span className={`absolute -right-[1.85rem] top-5 size-3 rounded-full ${overdue ? "bg-ds-danger" : soon ? "bg-ds-warning-bright" : "bg-ds-brand-600"}`} /><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-bold text-ds-brand-900">{goal.title}</p><p className="mt-1 text-xs text-ds-neutral-600">{employeeName(data?.employees ?? [], goal.employeeUserId)} · {new Intl.DateTimeFormat("ar-SA", { dateStyle: "medium" }).format(due)}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${overdue ? "bg-ds-danger-soft text-ds-danger" : soon ? "bg-ds-warning-soft text-ds-warning" : "bg-ds-brand-100 text-ds-brand-600"}`}>{overdue ? "متأخر" : soon ? "قريب" : "مجدول"} · {goal.progressPercent}%</span></div></article>; })}</div> : <p className="mt-5 rounded-2xl bg-ds-neutral-50 p-4 text-sm text-ds-neutral-600">لا توجد أهداف بتاريخ مستهدف ضمن التصفية الحالية.</p>}</section>
    <Dialog open={exportOpen} onOpenChange={setExportOpen}><DialogContent dir="rtl" className="max-h-[85vh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>معاينة تقرير الأهداف</DialogTitle><DialogDescription>يعرض التقرير الصفوف المفلترة ضمن الشركة فقط. اختر الأعمدة قبل تأكيد التنزيل.</DialogDescription></DialogHeader><div className="grid gap-2 py-3 sm:grid-cols-3">{(Object.keys(columns) as GoalExportColumn[]).map(column => <label key={column} className="flex items-center gap-2 rounded-xl border border-ds-neutral-200 px-3 py-2 text-sm text-ds-brand-900"><input type="checkbox" checked={columns[column]} onChange={() => setColumns(current => ({ ...current, [column]: !current[column] }))} />{goalExportLabels[column]}</label>)}</div><div className="overflow-x-auto rounded-2xl border border-ds-neutral-200"><table className="min-w-full text-right text-xs"><thead className="bg-ds-brand-50"><tr>{selectedColumns.map(column => <th key={column} className="px-3 py-3 font-bold text-ds-neutral-900">{goalExportLabels[column]}</th>)}</tr></thead><tbody>{exportRows.slice(0, 5).map((row, index) => <tr key={`${row.title}-${index}`} className="border-t border-ds-neutral-100">{selectedColumns.map(column => <td key={column} className="px-3 py-3 text-ds-neutral-700">{column === "progress" ? `${row.progress}%` : row[column]}</td>)}</tr>)}</tbody></table></div><p className="text-xs text-ds-neutral-600">يعرض الجدول أول خمسة صفوف من أصل {exportRows.length} صفاً مطابقاً للتصفية.</p><DialogFooter><Button variant="outline" onClick={() => setExportOpen(false)}>إلغاء</Button><Button variant="outline" onClick={() => exportGoalsCsv(exportRows, `${departmentId}-${dateFrom}-${dateTo}`, selectedColumns)} disabled={!selectedColumns.length} className="border-ds-brand-300 text-ds-brand-700"><Download className="ml-2 size-4" />CSV</Button><Button onClick={() => exportGoalsPdf(exportRows, `${departmentId}-${dateFrom}-${dateTo}`, selectedColumns)} disabled={!selectedColumns.length} className="bg-ds-brand-800"><Download className="ml-2 size-4" />PDF</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent dir="rtl" className="sm:max-w-lg"><DialogHeader><DialogTitle>إضافة هدف داخلي</DialogTitle><DialogDescription>هدف تشغيلي للمتابعة والتطوير فقط، وليس تقييماً مالياً أو قراراً وظيفياً.</DialogDescription></DialogHeader><div className="grid gap-4 py-3"><FormField label="الموظف"><Select value={employeeId} onValueChange={setEmployeeId}><SelectTrigger><SelectValue placeholder="اختر موظفاً" /></SelectTrigger><SelectContent>{data?.employees.map(employee => <SelectItem key={employee.id} value={String(employee.id)}>{employee.name || "موظف"}</SelectItem>)}</SelectContent></Select></FormField><FormField label="عنوان الهدف"><Input value={title} onChange={event => setTitle(event.target.value)} placeholder="مثال: إتمام مسار تطوير داخلي" /></FormField><FormField label="وصف مختصر (اختياري)"><Textarea value={description} onChange={event => setDescription(event.target.value)} placeholder="نطاق تشغيلي موجز" /></FormField><FormField label="تاريخ مستهدف (اختياري)"><Input type="date" value={targetAt} onChange={event => setTargetAt(event.target.value)} /></FormField></div><DialogFooter><Button variant="outline" onClick={() => setCreateOpen(false)}>إلغاء</Button><Button onClick={create} disabled={createGoal.isPending || employeeId === "none" || title.trim().length < 2} className="bg-ds-brand-800">حفظ الهدف</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={progressOpen} onOpenChange={setProgressOpen}><DialogContent dir="rtl" className="sm:max-w-lg"><DialogHeader><DialogTitle>تحديث تقدم الهدف</DialogTitle><DialogDescription>{selectedGoal?.title || ""} — يسجل التحديث ضمن المتابعة الداخلية فقط.</DialogDescription></DialogHeader><div className="grid gap-4 py-3"><FormField label="نسبة التقدم"><Input type="number" min="0" max="100" value={progress} onChange={event => setProgress(event.target.value)} /></FormField><FormField label="ربط بمسار تدريب (اختياري)"><Select value={trainingProgramId} onValueChange={setTrainingProgramId}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">دون ربط</SelectItem>{data?.programs.map(program => <SelectItem key={program.id} value={String(program.id)}>{program.title}</SelectItem>)}</SelectContent></Select></FormField><FormField label="ملاحظة متابعة (اختيارية)"><Textarea value={note} onChange={event => setNote(event.target.value)} placeholder="ملخص موجز للتقدم" /></FormField></div><DialogFooter><Button variant="outline" onClick={() => setProgressOpen(false)}>إلغاء</Button><Button onClick={saveProgress} disabled={addProgress.isPending || !selectedGoalId || Number(progress) < 0 || Number(progress) > 100} className="bg-ds-brand-800"><CheckCircle2 className="ml-2 size-4" />حفظ التقدم</Button></DialogFooter></DialogContent></Dialog>
  </main></DashboardLayout>;
}

function GoalMetric({ label, value, hint, tone }: { label: string; value: string | number; hint: string; tone: "green" | "blue" | "gold" | "rose" }) { const tones = { green: "bg-ds-success-soft text-ds-brand-600", blue: "bg-ds-info-soft text-ds-info", gold: "bg-ds-warning-soft text-ds-warning", rose: "bg-ds-danger-soft text-ds-danger" }; return <article className={`rounded-3xl p-5 ${tones[tone]}`}><p className="text-xs font-bold opacity-75">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p><p className="mt-1 text-xs opacity-80">{hint}</p></article>; }
function State({ title, text }: { title: string; text: string }) { return <div className="col-span-full flex min-h-64 flex-col items-center justify-center rounded-3xl border border-ds-neutral-200 bg-white px-6 text-center"><Flag className="size-8 text-ds-brand-400" /><h2 className="mt-4 font-bold text-ds-neutral-950">{title}</h2><p className="mt-2 max-w-md text-sm leading-6 text-ds-neutral-600">{text}</p></div>; }
