import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { BarChart3, CalendarDays, ReceiptText, ShieldCheck, UsersRound } from "lucide-react";
import { useState } from "react";

export default function HrReports() {
  const [month, setMonth] = useState(() => new Date().toISOString().slice(0, 7));
  const { data, isLoading, isError, refetch } = trpc.reports.monthly.useQuery({ month });
  return <DashboardLayout><div dir="rtl" className="mx-auto max-w-6xl"><section className="relative overflow-hidden rounded-[2rem] bg-[#1f4d39] p-7 text-white md:p-9"><div className="absolute -left-16 -top-20 size-56 rounded-full border-[24px] border-[#e7c89c]/15" /><div className="relative"><p className="flex items-center gap-2 text-xs font-bold text-[#e7c89c]"><BarChart3 className="size-4" />تقارير تشغيلية</p><h1 className="mt-3 text-3xl font-bold">مركز تقارير الإجازات والمصروفات</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-[#d7e8dc]">مؤشرات شهرية ومقارنة آمنة بالشهر السابق ضمن نطاق الصلاحيات الممنوحة لك.</p><label className="mt-5 flex w-fit items-center gap-3 rounded-2xl bg-white/10 px-3 py-2 text-xs font-semibold"><span>الشهر</span><Input aria-label="اختيار شهر التقرير" type="month" value={month} onChange={event => setMonth(event.target.value)} className="h-8 w-36 border-white/20 bg-white text-[#294535]" /></label></div></section>{isLoading ? <Loading /> : isError || !data ? <section className="mt-6 rounded-3xl border border-[#f0d3d0] bg-[#fff6f5] p-7 text-center"><h2 className="font-bold text-[#8f4641]">تعذر تحميل التقرير</h2><Button onClick={() => refetch()} variant="outline" className="mt-4 rounded-xl">إعادة المحاولة</Button></section> : <ReportContent report={data} />}</div></DashboardLayout>;
}

type MonthlyReport = { scope: "company" | "team"; selectedMonth: string; leaveDays: { current: number; previous: number; delta: number; percentChange: number | null; byType: Record<string, number> }; expensesSar: { current: number; previous: number; delta: number; percentChange: number | null; byType: Record<string, number> } };
function ReportContent({ report }: { report: MonthlyReport }) { return <><section className="mt-6 grid gap-4 md:grid-cols-3"><Metric icon={CalendarDays} title="أيام الإجازات" value={report.leaveDays.current} helper={`السابق ${report.leaveDays.previous} · ${compare(report.leaveDays)}`} /><Metric icon={ReceiptText} title="المصروفات (ر.س)" value={report.expensesSar.current.toLocaleString("ar-SA")} helper={`السابق ${report.expensesSar.previous.toLocaleString("ar-SA")} · ${compare(report.expensesSar)}`} /><Metric icon={UsersRound} title="نطاق البيانات" value={report.scope === "team" ? "فريقي المباشر" : "الشركة"} helper={`تقرير ${report.selectedMonth} ضمن نطاقك المصرح.`} /></section><section className="mt-6 grid gap-4 lg:grid-cols-2"><Breakdown title="أيام الإجازات حسب النوع" values={report.leaveDays.byType} empty="لا توجد إجازات ضمن الشهر المختار." /><Breakdown title="المصروفات حسب النوع (ر.س)" values={report.expensesSar.byType} empty="لا توجد مصروفات ضمن الشهر المختار." /></section><section className="mt-6 rounded-3xl border border-[#e0e9e2] bg-white p-6"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-2xl bg-[#eaf5ec] text-[#337a53]"><ShieldCheck className="size-5" /></span><div><h2 className="font-bold text-[#294535]">المقارنة الشهرية</h2><p className="mt-1 text-xs leading-6 text-[#728077]">عند عدم وجود بيانات للشهر السابق، تظهر المقارنة باعتبارها غير متاحة بدلاً من نسبة مضللة.</p></div></div></section></>; }
function Metric({ icon: Icon, title, value, helper }: { icon: typeof BarChart3; title: string; value: string | number; helper: string }) { return <article className="rounded-3xl border border-[#e0e9e2] bg-white p-5"><span className="flex size-10 items-center justify-center rounded-2xl bg-[#eaf5ec] text-[#347b53]"><Icon className="size-5" /></span><h2 className="mt-4 text-sm font-bold text-[#294535]">{title}</h2><p className="mt-2 text-3xl font-bold text-[#1f5b45]">{value}</p><p className="mt-2 text-[11px] leading-5 text-[#748178]">{helper}</p></article>; }
function Breakdown({ title, values, empty }: { title: string; values: Record<string, number>; empty: string }) { const items = Object.entries(values); return <section className="rounded-3xl border border-[#e0e9e2] bg-white p-6"><h2 className="font-bold text-[#294535]">{title}</h2><div className="mt-4 space-y-3">{items.length ? items.map(([label, value]) => <div key={label} className="flex items-center justify-between rounded-2xl bg-[#f7faf7] p-3 text-sm"><span className="font-semibold text-[#566a5d]">{label}</span><span className="font-bold text-[#286f49]">{value}</span></div>) : <p className="rounded-2xl bg-[#f7faf7] p-4 text-xs leading-6 text-[#77857c]">{empty}</p>}</div></section>; }
function Loading() { return <section className="mt-6 grid gap-4 md:grid-cols-3">{[1, 2, 3].map(item => <div key={item} className="h-44 animate-pulse rounded-3xl bg-[#edf3ee]" />)}</section>; }
function compare(metric: { delta: number; percentChange: number | null }) { return metric.percentChange === null ? "لا توجد مقارنة سابقة" : `${metric.delta >= 0 ? "+" : ""}${metric.delta} · ${metric.percentChange >= 0 ? "+" : ""}${metric.percentChange}%`; }
