import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { BarChart3, CalendarDays, ReceiptText, ShieldCheck, UsersRound } from "lucide-react";

export default function HrReports() {
  return <DashboardLayout><div dir="rtl" className="mx-auto max-w-6xl"><section className="relative overflow-hidden rounded-[2rem] bg-[#1f4d39] p-7 text-white md:p-9"><div className="absolute -left-16 -top-20 size-56 rounded-full border-[24px] border-[#e7c89c]/15" /><div className="relative"><p className="flex items-center gap-2 text-xs font-bold text-[#e7c89c]"><BarChart3 className="size-4" />تقارير تشغيلية</p><h1 className="mt-3 text-3xl font-bold">مركز تقارير الإجازات والمصروفات</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-[#d7e8dc]">يعرض هذا المركز مؤشرات شهرية للإجازات والمصروفات ومقارنة آمنة بالشهر السابق ضمن نطاق الصلاحيات الممنوحة لك.</p></div></section><section className="mt-6 grid gap-4 md:grid-cols-3"><Insight icon={CalendarDays} title="أيام الإجازات" text="إجمالي الأيام ونوع الإجازة للشهر المختار." /><Insight icon={ReceiptText} title="المصروفات" text="مصروفات السفر والتشغيل بالريال السعودي." /><Insight icon={UsersRound} title="نطاق الفريق" text="يظهر المدير بيانات فريقه المباشر فقط." /></section><section className="mt-6 rounded-3xl border border-[#e0e9e2] bg-white p-7 text-center shadow-sm"><span className="mx-auto flex size-12 items-center justify-center rounded-2xl bg-[#eaf5ec] text-[#337a53]"><ShieldCheck className="size-6" /></span><h2 className="mt-4 text-lg font-bold text-[#294535]">التقرير الشهري قيد الربط بالبيانات الحية</h2><p className="mx-auto mt-2 max-w-xl text-sm leading-7 text-[#728077]">تم تجهيز حسابات الأيام والمبالغ والمقارنة الشهرية. ستظهر المؤشرات تلقائياً فور توافر بيانات الإجازات والمصروفات ضمن نطاق شركتك أو فريقك.</p><Button variant="outline" className="mt-5 rounded-xl border-[#cfe0d2] text-[#397b55]">اختيار الشهر</Button></section></div></DashboardLayout>;
}

function Insight({ icon: Icon, title, text }: { icon: typeof BarChart3; title: string; text: string }) { return <article className="rounded-3xl border border-[#e0e9e2] bg-white p-5"><span className="flex size-10 items-center justify-center rounded-2xl bg-[#eaf5ec] text-[#347b53]"><Icon className="size-5" /></span><h2 className="mt-4 font-bold text-[#294535]">{title}</h2><p className="mt-2 text-xs leading-6 text-[#748178]">{text}</p></article>; }
