import DashboardLayout from "@/components/DashboardLayout";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { BarChart3, Target, UsersRound } from "lucide-react";

export default function ManagerDashboard() {
  const { data, isLoading, isError, error } = trpc.managerDashboard.overview.useQuery();
  return <DashboardLayout><div dir="rtl" className="mx-auto max-w-6xl"><p className="text-xs font-bold text-ds-brand-400">متابعة الفريق المباشر</p><h1 className="mt-2 text-3xl font-bold text-ds-brand-950">لوحة المديرين</h1><p className="mt-3 text-sm leading-7 text-ds-neutral-600">ملخص أهداف الموظفين الذين يشير ملفهم التنظيمي إلى أنك مديرهم المباشر فقط.</p>{isLoading ? <div className="mt-8 grid gap-5 md:grid-cols-3">{[1,2,3].map(item => <Skeleton key={item} className="h-36 rounded-3xl" />)}</div> : isError ? <div className="mt-8 rounded-3xl bg-ds-danger-soft p-6 text-sm text-ds-danger">تعذر تحميل لوحة الفريق: {error.message}</div> : <><section className="mt-8 grid gap-5 md:grid-cols-3"><Stat icon={<UsersRound />} label="أعضاء الفريق المباشر" value={data?.summary.memberCount ?? 0} /><Stat icon={<Target />} label="أهداف نشطة أو مكتملة" value={data?.summary.goalCount ?? 0} /><Stat icon={<BarChart3 />} label="متوسط التقدم" value={`${data?.summary.averageProgress ?? 0}%`} /></section><section className="mt-8 rounded-3xl border border-ds-neutral-200 bg-white"><header className="border-b border-ds-neutral-100 p-6"><h2 className="font-bold text-ds-neutral-950">تقدم الأهداف حسب الموظف</h2><p className="mt-1 text-xs text-ds-neutral-600">عرض تشغيلي للفريق المباشر؛ لا يمثل تقييماً رسمياً أو قراراً وظيفياً.</p></header>{data?.goals.length ? <div className="divide-y divide-ds-neutral-100">{data.goals.map(item => <article key={item.goal.id} className="p-6"><div className="flex items-start justify-between gap-4"><div><p className="font-bold text-ds-brand-900">{item.goal.title}</p><p className="mt-1 text-xs text-ds-neutral-600">{item.employeeName || item.employeeEmail || "موظف"}{item.departmentName ? ` · ${item.departmentName}` : ""}</p></div><span className="rounded-full bg-ds-brand-50 px-3 py-1 text-xs font-bold text-ds-brand-700">{item.goal.progressPercent}%</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-ds-neutral-100"><div className="h-full rounded-full bg-ds-brand-500" style={{ width: `${item.goal.progressPercent}%` }} /></div><p className="mt-2 text-xs text-ds-neutral-600">{item.goal.status === "completed" ? "مكتمل" : item.goal.status === "in_progress" ? "قيد المتابعة" : "لم يبدأ"}{item.goal.targetAt ? ` · الاستحقاق ${new Intl.DateTimeFormat("ar-SA", { dateStyle: "medium" }).format(new Date(item.goal.targetAt))}` : ""}</p></article>)}</div> : <div className="p-12 text-center text-sm text-ds-neutral-600">لا توجد أهداف مسجلة للفريق المباشر حالياً.</div>}</section></>}</div></DashboardLayout>;
}

function Stat({ icon, label, value }: { icon: React.ReactNode; label: string; value: string | number }) { return <article className="rounded-3xl border border-ds-neutral-200 bg-white p-6"><span className="inline-flex rounded-2xl bg-ds-success-soft p-3 text-ds-brand-600">{icon}</span><p className="mt-5 text-xs font-bold text-ds-neutral-600">{label}</p><p className="mt-2 text-3xl font-bold text-ds-brand-950">{value}</p></article>; }
