import DashboardLayout from "@/components/DashboardLayout";
import { ArrowLeft, BadgeCheck, BarChart3, CheckCircle2, ClipboardList, Compass, Layers3, LayoutTemplate, Map, Route, ShieldCheck, Sparkles, Target, UsersRound } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";

type Tab = "governance" | "journeys" | "positioning" | "architecture";
const tabs: { id: Tab; label: string; icon: typeof Target }[] = [{ id: "governance", label: "الحوكمة", icon: Target }, { id: "journeys", label: "رحلات المستخدم", icon: UsersRound }, { id: "positioning", label: "تموضع المنتج", icon: Compass }, { id: "architecture", label: "بنية المعلومات", icon: Layers3 }];
const mvpStages = [{ n: 1, title: "الحوكمة", output: "فريق ومؤشرات وملاك قرار", state: "معتمدة" }, { n: 2, title: "التميّز", output: "مبادئ تجربة أصلية", state: "قيد العمل" }, { n: 3, title: "المستخدمون", output: "رحلات الموظف والمدير والعمليات", state: "معتمدة" }, { n: 4, title: "التموضع", output: "رسالة القيمة ومقاييس التحويل", state: "معتمدة" }, { n: 5, title: "البنية", output: "خريطة صفحات وتنقل", state: "معتمدة" }];

export default function MvpStudio() {
  const [tab, setTab] = useState<Tab>("governance");
  return <DashboardLayout><div dir="rtl" className="mx-auto max-w-7xl"><section className="relative overflow-hidden rounded-[2rem] bg-[#214937] px-6 py-8 text-white md:px-9"><div className="absolute -left-14 -top-14 size-56 rounded-full border-[22px] border-[#e7c89c]/15" /><div className="relative flex flex-wrap items-start justify-between gap-5"><div className="max-w-3xl"><p className="flex items-center gap-2 text-xs font-bold text-[#e7c89c]"><Sparkles className="size-4" />إصدار MVP · المراحل 1–5</p><h1 className="mt-3 text-3xl font-bold tracking-tight md:text-4xl">مساحة تصميم الإصدار الأولي.</h1><p className="mt-4 text-sm leading-7 text-[#d9e9dc]">حوّلنا أساس البرنامج إلى واجهات قابلة للمراجعة: حوكمة واضحة، شرائح مستخدمين، رسالة قيمة، وخريطة تنقل قبل التوسع في الوحدات التشغيلية.</p></div><div className="rounded-2xl border border-white/15 bg-white/10 px-4 py-3 text-xs leading-6 text-[#e8f1ea]"><p className="font-bold text-[#e7c89c]">بوابة القبول</p><p>تجربة متجاوبة · تنقل واضح · مخرجات مرئية</p></div></div></section><section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{mvpStages.map(stage => <article key={stage.n} className={`rounded-2xl border p-4 ${stage.state === "قيد العمل" ? "border-[#8eb79a] bg-[#edf6ee]" : "border-[#e0e9e1] bg-white"}`}><div className="flex items-center justify-between"><span className="flex size-7 items-center justify-center rounded-xl bg-[#e8f3e9] text-xs font-bold text-[#367d55]">{stage.n}</span><span className={`text-[10px] font-bold ${stage.state === "قيد العمل" ? "text-[#27724c]" : "text-[#58816a]"}`}>{stage.state}</span></div><h2 className="mt-4 text-sm font-bold text-[#294535]">{stage.title}</h2><p className="mt-1 text-[11px] leading-5 text-[#748178]">{stage.output}</p></article>)}</section><section className="mt-7 rounded-3xl border border-[#e0e9e1] bg-white shadow-[0_10px_28px_rgba(21,50,35,.04)]"><div className="flex flex-wrap gap-2 border-b border-[#edf1ed] p-4">{tabs.map(item => { const Icon = item.icon; return <button key={item.id} onClick={() => setTab(item.id)} className={`flex items-center gap-2 rounded-xl px-4 py-2.5 text-xs font-bold transition ${tab === item.id ? "bg-[#1f5b45] text-white" : "text-[#607369] hover:bg-[#f0f6f0]"}`}><Icon className="size-4" />{item.label}</button>; })}</div><div className="p-5 md:p-7">{tab === "governance" && <Governance />}{tab === "journeys" && <Journeys />}{tab === "positioning" && <Positioning />}{tab === "architecture" && <Architecture />}</div></section></div></DashboardLayout>;
}

function Governance() { return <div><SectionIntro eyebrow="المرحلة 1–2" title="لوحة الحوكمة ومؤشرات القرار" text="واجهة مرجعية تجمع ما يحتاجه فريق البرنامج لاتخاذ قرار واضح قبل بناء وحدات جديدة." /><div className="mt-6 grid gap-4 lg:grid-cols-[1.25fr_.75fr]"><div className="rounded-3xl bg-[#f7faf7] p-5"><div className="flex items-center justify-between"><h3 className="font-bold text-[#284535]">معايير قبول MVP</h3><BadgeCheck className="size-5 text-[#3b8058]" /></div><div className="mt-5 space-y-3">{["عرض حوكمة وملاك قرار لكل مسار أساسي.", "رحلات منفصلة للموظف والمدير وفريق العمليات.", "رسالة قيمة وتنقل مفهوم من الموقع إلى المنتج.", "تجربة متجاوبة تعمل من لوحة الإدارة الداخلية."].map((item, index) => <div key={item} className="flex gap-3 rounded-2xl bg-white p-4"><span className="flex size-6 shrink-0 items-center justify-center rounded-full bg-[#e5f2e8] text-[11px] font-bold text-[#31774f]">{index + 1}</span><p className="text-xs leading-6 text-[#52695a]">{item}</p></div>)}</div></div><div className="space-y-4"><Metric value="5/5" label="مخرجات MVP المعتمدة" tone="green" /><Metric value="3" label="رحلات مستخدم أساسية" tone="sand" /><Metric value="1" label="خريطة تنقل موحدة" tone="blue" /></div></div></div>; }
function Journeys() { const journeys = [{ title: "الموظف", icon: UsersRound, tone: "bg-[#e7f3e9] text-[#29754e]", steps: ["يدخل المنصة", "يختار الخدمة", "يتابع حالة الطلب", "يتلقى التحديث"] }, { title: "المدير", icon: Target, tone: "bg-[#eef0fb] text-[#5e61a6]", steps: ["يرى ما ينتظر المراجعة", "يتحقق من السياق", "يوافق أو يعيد الطلب", "يتابع الالتزامات"] }, { title: "فريق العمليات", icon: ClipboardList, tone: "bg-[#fff1df] text-[#a26623]", steps: ["يستقبل الطلبات", "يحدد المالك", "ينفذ المعالجة", "يوثق الإغلاق"] }]; return <div><SectionIntro eyebrow="المرحلة 3" title="رحلات المستخدمين الأساسية" text="كل رحلة تصف المسار الذي سيُقاس عليه وضوح الواجهة واكتمال التدفق في الإصدارات التالية." /><div className="mt-6 grid gap-4 lg:grid-cols-3">{journeys.map(journey => <article key={journey.title} className="rounded-3xl border border-[#e1e9e2] p-5"><div className={`flex size-11 items-center justify-center rounded-2xl ${journey.tone}`}><journey.icon className="size-5" /></div><h3 className="mt-5 font-bold text-[#294535]">رحلة {journey.title}</h3><div className="mt-5 space-y-4">{journey.steps.map((step, index) => <div key={step} className="relative flex gap-3"><span className="flex size-6 shrink-0 items-center justify-center rounded-full border border-[#cfe0d2] text-[10px] font-bold text-[#3c8058]">{index + 1}</span>{index < journey.steps.length - 1 && <span className="absolute right-3 top-6 h-5 w-px bg-[#dce8de]" />}<p className="pt-1 text-xs text-[#61746a]">{step}</p></div>)}</div></article>)}</div></div>; }
function Positioning() { return <div><SectionIntro eyebrow="المرحلة 4" title="تموضع المنتج ورسالة القيمة" text="تتحول القيمة من وعود عامة إلى نقاط يمكن توضيحها في الموقع وقياسها لاحقاً داخل المنتج." /><div className="mt-6 grid gap-4 lg:grid-cols-[1.1fr_.9fr]"><article className="rounded-3xl bg-[#1d4936] p-7 text-white"><p className="text-xs font-bold text-[#e7c89c]">رسالة MVP</p><h3 className="mt-3 text-2xl font-bold leading-tight">عمليات الموظفين والعلاقات الحكومية في مسار واحد واضح.</h3><p className="mt-4 text-sm leading-7 text-[#d5e5d8]">تجمع حلول الغد الخدمة الذاتية، المراجعة التشغيلية، والذكاء المساعد في منصة عربية قابلة للتوسع حسب الشركة.</p><div className="mt-6 flex flex-wrap gap-2">{["وضوح الطلب", "سرعة المتابعة", "قرار مدعوم بالسياق"].map(item => <span key={item} className="rounded-full bg-white/10 px-3 py-1.5 text-xs font-bold text-[#e6f1e8]">{item}</span>)}</div></article><article className="rounded-3xl border border-[#e1e9e2] p-6"><h3 className="font-bold text-[#294535]">كيف سنقيس التبنّي؟</h3><div className="mt-5 space-y-4">{[["التحويل", "إكمال طلب العرض دون مغادرة الصفحة"], ["التشغيل", "إتمام الطلب عبر مسار واضح"], ["الذكاء", "تحسن اكتمال المسودات قبل إرسالها"]].map(([label, text]) => <div key={label} className="rounded-2xl bg-[#f7faf7] p-4"><p className="text-xs font-bold text-[#3d7656]">{label}</p><p className="mt-1 text-xs leading-6 text-[#6c7d72]">{text}</p></div>)}</div></article></div></div>; }
function Architecture() { const [, setLocation] = useLocation(); const nodes = [{ title: "الموقع", text: "الصفحة الرئيسية وطلب العرض", path: "/" }, { title: "الدخول", text: "المصادقة وبدء مساحة العمل", path: "/app" }, { title: "الخدمات", text: "طلبات الموظفين والمساعد الذكي", path: "/requests/new" }, { title: "الإدارة", text: "العمليات وطلبات العروض وخارطة التطوير", path: "/operations" }]; return <div><SectionIntro eyebrow="المرحلة 5" title="بنية المعلومات وخريطة التنقل" text="مسارات قليلة وواضحة تربط زيارة الموقع بالمستخدم الداخلي دون تشتيت." /><div className="mt-6 grid gap-4 lg:grid-cols-4">{nodes.map((node, index) => <article key={node.title} className="relative rounded-3xl border border-[#e1e9e2] p-5"><div className="flex items-center justify-between"><span className="flex size-8 items-center justify-center rounded-xl bg-[#e8f3e9] text-xs font-bold text-[#367d55]">{index + 1}</span>{index < nodes.length - 1 && <ArrowLeft className="hidden size-4 text-[#7d9b88] lg:block" />}</div><h3 className="mt-5 font-bold text-[#294535]">{node.title}</h3><p className="mt-2 text-xs leading-6 text-[#728077]">{node.text}</p><button onClick={() => setLocation(node.path)} className="mt-5 flex items-center gap-1 text-xs font-bold text-[#397d57]">فتح المسار <ArrowLeft className="size-3" /></button></article>)}</div><div className="mt-6 rounded-2xl border border-[#d9e8dc] bg-[#eff7f0] p-5"><div className="flex items-start gap-3"><LayoutTemplate className="mt-0.5 size-5 text-[#398157]" /><p className="text-sm leading-7 text-[#526b5a]">تُضاف الصفحات الجديدة في الإصدارات التالية ضمن هذه البنية بدلاً من بناء مسارات منعزلة. يحافظ ذلك على طريقة انتقال مفهومة من التسويق إلى الخدمة الذاتية ثم الإدارة.</p></div></div></div>; }
function SectionIntro({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <div><p className="text-xs font-bold text-[#5c8c70]">{eyebrow}</p><h2 className="mt-2 text-2xl font-bold text-[#1d4532]">{title}</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-[#728077]">{text}</p></div>; }
function Metric({ value, label, tone }: { value: string; label: string; tone: "green" | "sand" | "blue" }) { const styles = { green: "bg-[#e7f3e9] text-[#286f49]", sand: "bg-[#fff0dd] text-[#9a6121]", blue: "bg-[#e8eef9] text-[#446c99]" }; return <article className={`rounded-3xl p-5 ${styles[tone]}`}><p className="text-3xl font-bold">{value}</p><p className="mt-2 text-xs font-semibold opacity-80">{label}</p></article>; }
