import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { ClipboardList, Plus, RefreshCw } from "lucide-react";
import { useMemo } from "react";
import { useLocation } from "wouter";

const statusInfo = { submitted: ["تم الاستلام", "bg-ds-warning-soft text-ds-warning"], in_review: ["قيد المراجعة", "bg-ds-info-soft text-ds-info"], approved: ["تمت الموافقة", "bg-ds-brand-100 text-ds-brand-600"], rejected: ["مرفوض", "bg-ds-danger-soft text-ds-danger"], completed: ["مكتمل", "bg-ds-success-soft text-ds-brand-600"] } as const;
const leaveLabels = { annual: "إجازة سنوية", sick: "إجازة مرضية", emergency: "إجازة طارئة" } as const;
const expenseLabels = { travel: "مصروف سفر", operating: "مصروف تشغيل" } as const;

export default function MyRequests() {
  const [, setLocation] = useLocation();
  const filters = useMemo(() => ({}), []);
  const { data: requests, isLoading, isError, refetch } = trpc.requests.mine.useQuery(filters);
  return <DashboardLayout><div dir="rtl" className="mx-auto w-full min-w-0 max-w-6xl"><div className="flex min-w-0 flex-wrap items-end justify-between gap-4"><div className="min-w-0"><p className="text-xs font-bold text-ds-brand-400">سجل الموظف</p><h1 className="mt-2 text-3xl font-bold text-ds-brand-1000">طلباتي</h1><p className="mt-3 text-sm text-ds-neutral-600">تابع حالة طلباتك وملخصات الإجازات والمصروفات وسجل التحديثات.</p></div><Button onClick={() => setLocation("/employee-requests")} className="h-10 shrink-0 rounded-xl bg-ds-brand-800 hover:bg-ds-brand-950"><Plus className="ml-2 size-4" />طلب جديد</Button></div><section className="mt-8 w-full min-w-0 overflow-hidden rounded-3xl border border-ds-neutral-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-ds-neutral-100 px-5 py-4 md:px-6"><p className="text-sm font-bold text-ds-neutral-950">قائمة الطلبات</p><button onClick={() => refetch()} className="rounded-lg p-1.5 text-ds-brand-400 hover:bg-ds-brand-50" aria-label="تحديث القائمة"><RefreshCw className="size-4" /></button></div>{isLoading ? <div className="space-y-3 p-6">{[1, 2, 3].map(item => <Skeleton key={item} className="h-20 w-full rounded-2xl" />)}</div> : isError ? <EmptyState error onRetry={() => refetch()} /> : requests?.length ? <div className="divide-y divide-ds-neutral-100">{requests.map(entry => { const { request, leave, expense } = entry; const [status, tone] = statusInfo[request.status]; const summary = leave ? `${leaveLabels[leave.leaveType]} · ${leave.startDate} إلى ${leave.endDate}` : expense ? `${expenseLabels[expense.expenseType]} · ${Number(expense.amountSar).toLocaleString("ar-SA")} ر.س` : request.category; return <button key={request.id} onClick={() => setLocation(`/requests/${request.id}`)} className="grid w-full grid-cols-[minmax(0,1fr)_auto] gap-3 p-5 text-right transition hover:bg-ds-neutral-50 md:grid-cols-[1.4fr_1fr_0.7fr_auto] md:items-center md:px-6"><div className="min-w-0"><p className="truncate font-bold text-ds-neutral-950">{request.subject}</p><p className="mt-1 truncate text-xs text-ds-neutral-600">{request.reference} · {summary}</p></div><p className="hidden text-xs text-ds-neutral-700 md:block">{request.type === "hr" ? "الموارد البشرية" : "العلاقات الحكومية"}</p><p className="hidden text-xs text-ds-neutral-700 md:block">آخر تحديث {new Date(request.updatedAt).toLocaleDateString("ar-SA")}</p><span className={`self-start rounded-full px-3 py-1 text-xs font-bold md:self-auto ${tone}`}>{status}</span></button>; })}</div> : <EmptyState onRetry={() => setLocation("/employee-requests")} />}</section></div></DashboardLayout>;
}

function EmptyState({ error, onRetry }: { error?: boolean; onRetry: () => void }) { return <div className="flex flex-col items-center justify-center px-6 py-20 text-center"><div className="flex size-14 items-center justify-center rounded-3xl bg-ds-success-soft text-ds-brand-600"><ClipboardList className="size-6" /></div><h2 className="mt-5 font-bold text-ds-neutral-950">{error ? "تعذر تحميل الطلبات" : "لا يوجد سجل طلبات بعد"}</h2><p className="mt-2 max-w-sm text-sm leading-6 text-ds-neutral-600">{error ? "حاول تحديث الصفحة أو تواصل مع فريق الدعم إذا استمرت المشكلة." : "ستعرض هذه المساحة رقم الطلب وملخصه وحالته فور تقديم طلبك الأول."}</p><Button onClick={onRetry} variant="outline" className="mt-5 rounded-xl border-ds-brand-200 text-ds-brand-600">{error ? "إعادة المحاولة" : "تقديم طلب جديد"}</Button></div>; }
