import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { ClipboardList, Plus, RefreshCw } from "lucide-react";
import { useMemo } from "react";
import { useLocation } from "wouter";

const statusInfo = { submitted: ["تم الاستلام", "bg-[#f8eddc] text-[#9b651d]"], in_review: ["قيد المراجعة", "bg-[#e5edf9] text-[#376b9b]"], approved: ["تمت الموافقة", "bg-[#e3f2e7] text-[#2d774a]"], rejected: ["مرفوض", "bg-[#f9e7e7] text-[#a94442]"], completed: ["مكتمل", "bg-[#e6f2ec] text-[#23734f]"] } as const;

export default function MyRequests() {
  const [, setLocation] = useLocation();
  const filters = useMemo(() => ({}), []);
  const { data: requests, isLoading, isError, refetch } = trpc.requests.mine.useQuery(filters);
  return <DashboardLayout><div dir="rtl" className="mx-auto w-full min-w-0 max-w-6xl"><div className="flex min-w-0 flex-wrap items-end justify-between gap-4"><div className="min-w-0"><p className="text-xs font-bold text-[#5e8970]">سجل الموظف</p><h1 className="mt-2 text-3xl font-bold text-[#173e30]">طلباتي</h1><p className="mt-3 text-sm text-[#748279]">تابع حالة طلباتك وسجل التحديثات المرتبط بكل طلب.</p></div><Button onClick={() => setLocation("/requests/new")} className="h-10 shrink-0 rounded-xl bg-[#1f5b45] hover:bg-[#174735]"><Plus className="ml-2 size-4" />طلب جديد</Button></div><section className="mt-8 w-full min-w-0 overflow-hidden rounded-3xl border border-[#e3e9e3] bg-white shadow-sm"><div className="flex items-center justify-between border-b border-[#edf0ed] px-5 py-4 md:px-6"><p className="text-sm font-bold text-[#233e31]">قائمة الطلبات</p><button onClick={() => refetch()} className="rounded-lg p-1.5 text-[#60826d] hover:bg-[#edf4ed]" aria-label="تحديث القائمة"><RefreshCw className="size-4" /></button></div>{isLoading ? <div className="space-y-3 p-6">{[1, 2, 3].map(item => <Skeleton key={item} className="h-16 w-full rounded-2xl" />)}</div> : isError ? <EmptyState error onRetry={() => refetch()} /> : requests?.length ? <div className="divide-y divide-[#edf0ed]">{requests.map(request => { const [status, tone] = statusInfo[request.status]; return <button key={request.id} onClick={() => setLocation(`/requests/${request.id}`)} className="grid w-full grid-cols-[minmax(0,1fr)_auto] gap-3 p-5 text-right transition hover:bg-[#fbfcfa] md:grid-cols-[1.4fr_0.8fr_0.7fr_auto] md:items-center md:px-6"><div className="min-w-0"><p className="truncate font-bold text-[#294435]">{request.subject}</p><p className="mt-1 truncate text-xs text-[#7a877f]">{request.reference} · {request.category}</p></div><p className="hidden text-xs text-[#65766b] md:block">{request.type === "hr" ? "الموارد البشرية" : "العلاقات الحكومية"}</p><p className="hidden text-xs text-[#65766b] md:block">آخر تحديث {new Date(request.updatedAt).toLocaleDateString("ar-SA")}</p><span className={`self-start rounded-full px-3 py-1 text-xs font-bold md:self-auto ${tone}`}>{status}</span></button>; })}</div> : <EmptyState onRetry={() => setLocation("/requests/new")} />}</section></div></DashboardLayout>;
}

function EmptyState({ error, onRetry }: { error?: boolean; onRetry: () => void }) { return <div className="flex flex-col items-center justify-center px-6 py-20 text-center"><div className="flex size-14 items-center justify-center rounded-3xl bg-[#eaf3eb] text-[#327756]"><ClipboardList className="size-6" /></div><h2 className="mt-5 font-bold text-[#233e31]">{error ? "تعذر تحميل الطلبات" : "لا يوجد سجل طلبات بعد"}</h2><p className="mt-2 max-w-sm text-sm leading-6 text-[#7d897f]">{error ? "حاول تحديث الصفحة أو تواصل مع فريق الدعم إذا استمرت المشكلة." : "ستعرض هذه المساحة رقم الطلب ونوعه وحالته وآخر تحديث، فور تقديم طلبك الأول."}</p><Button onClick={onRetry} variant="outline" className="mt-5 rounded-xl border-[#d5e2d7] text-[#2b704d]">{error ? "إعادة المحاولة" : "تقديم طلب جديد"}</Button></div>; }
