import { KeyRound, RefreshCw, ShieldAlert, UserCheck, UsersRound } from "lucide-react";

import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";

export default function OAuthAcceptanceReadiness() {
  const { data, isLoading, isError, error, refetch, isFetching } = trpc.system.oauthAcceptanceReadiness.useQuery();

  return <DashboardLayout><div dir="rtl" className="mx-auto max-w-5xl">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold text-ds-brand-400">بوابة القبول الحي</p><h1 className="mt-2 text-3xl font-bold text-ds-brand-1000">جاهزية قبول OAuth</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-ds-neutral-600">مؤشرات مجمّعة للمسؤول للتأكد من توفر أدوار الاختبار والارتباط المباشر، من دون عرض أسماء أو عناوين أو إنشاء جلسات بديلة.</p></div><Button variant="outline" onClick={() => refetch()} disabled={isFetching} className="h-10 rounded-xl border-ds-brand-200 text-ds-brand-700"><RefreshCw className={`ml-2 size-4 ${isFetching ? "animate-spin" : ""}`} />تحديث المؤشرات</Button></div>
    {isLoading ? <div className="mt-8 grid gap-4 md:grid-cols-4">{[1, 2, 3, 4].map(item => <Skeleton key={item} className="h-44 rounded-3xl" />)}</div> : isError ? <section className="mt-8 rounded-3xl border border-ds-danger-border bg-ds-white p-7 text-center"><ShieldAlert className="mx-auto size-9 text-ds-danger" /><h2 className="mt-4 text-lg font-bold text-ds-danger-strong">تعذر قراءة جاهزية القبول</h2><p className="mt-2 text-sm text-ds-danger-muted">{error.message}</p></section> : data ? <><div className="mt-8 flex flex-wrap items-center justify-between gap-3 border-y border-ds-neutral-200 py-4"><div className="flex items-center gap-3"><span className={`size-3 rounded-full ${data.overall === "ready" ? "bg-ds-brand-500" : "bg-ds-warning-bright"}`} /><strong className="text-lg text-ds-neutral-950">{data.overall === "ready" ? "جاهزة لتنفيذ القبول الحي" : "بانتظار استكمال الجاهزية"}</strong></div><span className="text-xs text-ds-neutral-600">آخر فحص: {new Date(data.checkedAt).toLocaleString("ar-SA")}</span></div><div className="mt-6 grid gap-4 md:grid-cols-4">{data.checks.map(check => <article key={check.id} className="rounded-3xl border border-ds-neutral-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between"><span className={`flex size-10 items-center justify-center rounded-2xl ${check.ready ? "bg-ds-success-soft text-ds-brand-600" : "bg-ds-warning-soft text-ds-warning"}`}>{check.id === "relationship" ? <UsersRound className="size-5" /> : check.id === "specialist" ? <KeyRound className="size-5" /> : <UserCheck className="size-5" />}</span><Badge className={check.ready ? "bg-ds-success-soft text-ds-brand-600 hover:bg-ds-success-soft" : "bg-ds-warning-soft text-ds-warning hover:bg-ds-warning-soft"}>{check.ready ? "متاح" : "مطلوب"}</Badge></div><h2 className="mt-6 font-bold text-ds-neutral-950">{check.label}</h2><p className="mt-2 text-sm leading-6 text-ds-neutral-600">{check.detail}</p></article>)}</div><p className="mt-6 rounded-2xl bg-ds-neutral-50 px-5 py-4 text-sm leading-7 text-ds-neutral-700">هذه الصفحة لا تنفذ قبولاً تلقائياً ولا تفعّل حسابات أو تغيّر أدواراً. عند اكتمال المؤشرات، يظل الاختبار الحي يدوياً وبجلسات OAuth مستقلة.</p></> : null}
  </div></DashboardLayout>;
}
