import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, ClipboardList, FileText, Landmark, Plus, ShieldAlert } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const taskIcons = { contracts_review: Landmark, documents_review: FileText, access_review: ShieldAlert, handover_review: ClipboardList } as const;
const statusLabels = { in_progress: "قيد التنفيذ", completed: "مكتملة", cancelled: "ملغاة" } as const;

export default function Offboarding() {
  const utils = trpc.useUtils(); const { data, isLoading, isError, error } = trpc.offboarding.overview.useQuery();
  const [open, setOpen] = useState(false); const [employeeId, setEmployeeId] = useState("none"); const [lastWorkingAt, setLastWorkingAt] = useState("");
  const start = trpc.offboarding.start.useMutation({ onSuccess: () => { toast.success("تم بدء قائمة إنهاء الخدمة"); setOpen(false); setEmployeeId("none"); setLastWorkingAt(""); utils.offboarding.overview.invalidate(); }, onError: issue => toast.error("تعذر بدء القائمة", { description: issue.message }) });
  const setTask = trpc.offboarding.setTask.useMutation({ onSuccess: () => utils.offboarding.overview.invalidate(), onError: issue => toast.error("تعذر تحديث المهمة", { description: issue.message }) });
  const begin = () => start.mutate({ employeeUserId: Number(employeeId), ...(lastWorkingAt ? { lastWorkingAt: new Date(`${lastWorkingAt}T00:00:00`) } : {}) });
  return <DashboardLayout><main dir="rtl" className="mx-auto max-w-6xl"><section className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold text-[#5d8d70]">HR Core · إكمال تشغيلي</p><h1 className="mt-2 text-3xl font-bold text-[#1d4532]">إنهاء الخدمة</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-[#748178]">قائمة تحقق داخلية تربط مراجعة العقود والوثائق والتسليم. لا تحسب تسويات أو رواتب، ولا تنشئ مستندات قانونية.</p></div><Button onClick={() => setOpen(true)} className="rounded-xl bg-[#1f5b45]"><Plus className="ml-2 size-4" />بدء قائمة</Button></section>
    {isLoading ? <div className="mt-8 grid gap-4 md:grid-cols-2">{[1, 2].map(item => <Skeleton key={item} className="h-64 rounded-3xl" />)}</div> : isError ? <State title="تعذر تحميل قوائم إنهاء الخدمة" text={error.message} /> : <section className="mt-8 grid gap-5 lg:grid-cols-2">{data?.offboardings.length ? data.offboardings.map(item => { const employee = data.employees.find(person => person.id === item.employeeUserId); const tasks = data.tasks.filter(task => task.offboardingId === item.id); const completed = tasks.filter(task => task.status === "completed").length; const contracts = data.contracts.filter(contract => contract.employeeUserId === item.employeeUserId).length; const documents = data.documents.filter(documentItem => documentItem.employeeUserId === item.employeeUserId).length; return <article key={item.id} className="rounded-3xl border border-[#dfe9e1] bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-[#294535]">{employee?.name || "موظف"}</p><p className="mt-1 text-xs text-[#718075]">آخر يوم عمل: {item.lastWorkingAt ? new Intl.DateTimeFormat("ar-SA", { dateStyle: "medium" }).format(new Date(item.lastWorkingAt)) : "غير محدد"}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${item.status === "completed" ? "bg-[#e5f4e8] text-[#367850]" : "bg-[#fff5df] text-[#946a1a]"}`}>{statusLabels[item.status]}</span></div><div className="mt-4 grid grid-cols-3 gap-2"><Metric label="المهام" value={`${completed}/${tasks.length}`} /><Metric label="العقود" value={String(contracts)} /><Metric label="الوثائق" value={String(documents)} /></div><div className="mt-5 space-y-2">{tasks.map(task => { const Icon = taskIcons[task.taskKey as keyof typeof taskIcons] || ClipboardList; const done = task.status === "completed"; return <button key={task.id} type="button" onClick={() => setTask.mutate({ taskId: task.id, completed: !done })} disabled={setTask.isPending} className={`flex w-full items-center justify-between rounded-2xl border px-3 py-3 text-right transition ${done ? "border-[#cfe5d2] bg-[#f0f8f1]" : "border-[#edf1ed] bg-white hover:bg-[#f8fbf8]"}`}><span className="flex items-center gap-2 text-sm font-medium text-[#3b5545]"><Icon className={`size-4 ${done ? "text-[#3c8a58]" : "text-[#8a9b90]"}`} />{task.label}</span>{done ? <CheckCircle2 className="size-5 text-[#3c8a58]" /> : <span className="size-5 rounded-full border border-[#cddbd0]" />}</button>; })}</div></article>; }) : <State title="لا توجد قوائم إنهاء خدمة" text="ابدأ قائمة داخلية عند الحاجة، ثم راجع العقود والوثائق والتسليم دون احتساب تسويات." />}</section>}
    <Dialog open={open} onOpenChange={setOpen}><DialogContent dir="rtl" className="sm:max-w-md"><DialogHeader><DialogTitle>بدء قائمة إنهاء الخدمة</DialogTitle><DialogDescription>تنشئ قائمة مراجعة داخلية فقط، ولا تغيّر حالة الموظف أو تعطل الوصول تلقائياً.</DialogDescription></DialogHeader><div className="grid gap-4 py-3"><div><label className="mb-2 block text-xs font-bold text-[#61756a]">الموظف</label><Select value={employeeId} onValueChange={setEmployeeId}><SelectTrigger><SelectValue placeholder="اختر موظفاً" /></SelectTrigger><SelectContent>{data?.employees.map(employee => <SelectItem key={employee.id} value={String(employee.id)}>{employee.name || "موظف"}</SelectItem>)}</SelectContent></Select></div><div><label className="mb-2 block text-xs font-bold text-[#61756a]">آخر يوم عمل (اختياري)</label><Input type="date" value={lastWorkingAt} onChange={event => setLastWorkingAt(event.target.value)} /></div></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>إلغاء</Button><Button onClick={begin} disabled={start.isPending || employeeId === "none"} className="bg-[#1f5b45]">إنشاء القائمة</Button></DialogFooter></DialogContent></Dialog>
  </main></DashboardLayout>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-[#f7faf7] p-3 text-center"><p className="text-[11px] text-[#7a897f]">{label}</p><p className="mt-1 font-bold text-[#2e543d]">{value}</p></div>; }
function State({ title, text }: { title: string; text: string }) { return <div className="col-span-full flex min-h-64 flex-col items-center justify-center rounded-3xl border border-[#dfe9e1] bg-white px-6 text-center"><ClipboardList className="size-8 text-[#5b8a6c]" /><h2 className="mt-4 font-bold text-[#294535]">{title}</h2><p className="mt-2 max-w-md text-sm leading-6 text-[#748178]">{text}</p></div>; }
