import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { BarChart3, ClipboardCheck, Filter, RefreshCw, ShieldAlert } from "lucide-react";
import { useMemo, useState } from "react";
import { useLocation } from "wouter";

const statusInfo = { submitted: ["تم الاستلام", "bg-ds-warning-soft text-ds-warning"], in_review: ["قيد المراجعة", "bg-ds-info-soft text-ds-info"], approved: ["تمت الموافقة", "bg-ds-brand-100 text-ds-brand-600"], rejected: ["مرفوض", "bg-ds-danger-soft text-ds-danger"], completed: ["مكتمل", "bg-ds-success-soft text-ds-brand-600"] } as const;

export default function Operations() {
  const [, setLocation] = useLocation();
  const [type, setType] = useState("all");
  const [status, setStatus] = useState("all");
  const filters = useMemo(() => ({ ...(type !== "all" ? { type: type as "hr" | "government" } : {}), ...(status !== "all" ? { status: status as keyof typeof statusInfo } : {}) }), [type, status]);
  const { data: modulePermissions } = trpc.accounts.myModulePermissions.useQuery();
  const { data: items, isLoading, isError, error, refetch } = trpc.requests.operations.useQuery(filters);
  const moduleOptions = useMemo(() => [["all", "كل الأنواع"], ...(modulePermissions || []).filter(permission => permission.canView).map(permission => [permission.module, permission.module === "hr" ? "الموارد البشرية" : "العلاقات الحكومية"])], [modulePermissions]);
  const allItems = items || [];
  const submittedCount = allItems.filter(item => item.request.status === "submitted").length;
  const reviewCount = allItems.filter(item => item.request.status === "in_review").length;
  const completedCount = allItems.filter(item => ["approved", "completed"].includes(item.request.status)).length;

  return <DashboardLayout><div dir="rtl" className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold text-ds-brand-400">إدارة المعاملات</p><h1 className="mt-2 text-3xl font-bold text-ds-brand-1000">مركز العمليات</h1><p className="mt-3 text-sm text-ds-neutral-600">راجع الطلبات المصرح لك بها، وحدّث مسارها، وثّق كل إجراء ضمن سجل واضح.</p></div><Button variant="outline" onClick={() => refetch()} className="h-10 rounded-xl border-ds-brand-200 text-ds-brand-700"><RefreshCw className="ml-2 size-4" />تحديث البيانات</Button></div><div className="mt-7 grid gap-4 md:grid-cols-3"><Metric label="بانتظار المراجعة" value={submittedCount} tone="bg-ds-warning-soft text-ds-warning" /><Metric label="قيد المعالجة" value={reviewCount} tone="bg-ds-info-soft text-ds-info" /><Metric label="مكتملة أو معتمدة" value={completedCount} tone="bg-ds-brand-100 text-ds-brand-600" /></div><section className="mt-6 overflow-hidden rounded-3xl border border-ds-neutral-200 bg-white shadow-sm"><div className="border-b border-ds-neutral-100 p-5 md:p-6"><div className="flex items-center gap-2 text-sm font-bold text-ds-neutral-950"><BarChart3 className="size-4 text-ds-brand-400" />طابور الطلبات</div><div className="mt-5 grid gap-3 sm:grid-cols-2"><FilterSelect label="نوع الطلب" value={type} onChange={setType} options={moduleOptions} /><FilterSelect label="الحالة" value={status} onChange={setStatus} options={[["all", "كل الحالات"], ["submitted", "تم الاستلام"], ["in_review", "قيد المراجعة"], ["approved", "تمت الموافقة"], ["rejected", "مرفوض"], ["completed", "مكتمل"]]} /></div></div>{isLoading ? <div className="space-y-3 p-6">{[1, 2, 3].map(item => <Skeleton key={item} className="h-20 w-full rounded-2xl" />)}</div> : isError ? <AccessState message={error.message} /> : allItems.length ? <div className="divide-y divide-ds-neutral-100">{allItems.map(({ request, employee }) => { const [label, tone] = statusInfo[request.status]; return <button key={request.id} onClick={() => setLocation(`/requests/${request.id}`)} className="grid w-full grid-cols-[1fr_auto] gap-4 p-5 text-right transition hover:bg-ds-neutral-50 md:grid-cols-[1.3fr_0.8fr_0.7fr_auto] md:items-center md:px-6"><div><p className="font-bold text-ds-neutral-950">{request.subject}</p><p className="mt-1 text-xs text-ds-neutral-600">{request.reference} · مقدّم من {employee.name || employee.email || "موظف"}</p></div><div className="hidden md:block"><p className="text-xs font-bold text-ds-neutral-800">{request.type === "hr" ? "الموارد البشرية" : "العلاقات الحكومية"}</p><p className="mt-1 text-[11px] text-ds-neutral-500">{request.category}</p></div><p className="hidden text-xs text-ds-neutral-700 md:block">{new Date(request.updatedAt).toLocaleDateString("ar-SA")}</p><span className={`self-start rounded-full px-3 py-1 text-xs font-bold md:self-auto ${tone}`}>{label}</span></button>; })}</div> : <QueueEmpty />}</section></div></DashboardLayout>;
}

function FilterSelect({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[][] }) { return <div><label className="mb-2 block text-xs font-bold text-ds-neutral-700">{label}</label><Select value={value} onValueChange={onChange}><SelectTrigger className="h-10 rounded-xl border-ds-neutral-200"><SelectValue /></SelectTrigger><SelectContent>{options.map(([optionValue, optionLabel]) => <SelectItem key={optionValue} value={optionValue}>{optionLabel}</SelectItem>)}</SelectContent></Select></div>; }
function Metric({ label, value, tone }: { label: string; value: number; tone: string }) { return <article className={`rounded-3xl p-5 ${tone}`}><p className="text-xs font-semibold opacity-75">{label}</p><p className="mt-4 text-3xl font-bold">{value}</p></article>; }
function QueueEmpty() { return <div className="flex flex-col items-center justify-center px-5 py-16 text-center"><div className="flex size-12 items-center justify-center rounded-2xl bg-ds-brand-50 text-ds-brand-700"><ClipboardCheck className="size-6" /></div><p className="mt-4 text-sm font-bold text-ds-neutral-900">لا توجد معاملات ضمن هذه الفلاتر</p><p className="mt-2 max-w-sm text-xs leading-6 text-ds-neutral-500">ستظهر الطلبات المتاحة حسب نوعها وحالتها والصلاحيات الممنوحة لحسابك.</p></div>; }
function AccessState({ message }: { message: string }) { return <div className="flex flex-col items-center justify-center px-5 py-16 text-center"><div className="flex size-12 items-center justify-center rounded-2xl bg-ds-danger-soft text-ds-danger"><ShieldAlert className="size-6" /></div><p className="mt-4 text-sm font-bold text-ds-neutral-900">تعذر فتح مركز العمليات</p><p className="mt-2 max-w-sm text-xs leading-6 text-ds-neutral-500">{message}</p></div>; }
