import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { BriefcaseBusiness, CheckCircle2, ClipboardCheck, Plus, ShieldAlert, UserPlus, UsersRound } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const openingStatusLabels = { draft: "مسودة", open: "مفتوح", closed: "مغلق" } as const;
const employmentTypeLabels = { full_time: "دوام كامل", part_time: "دوام جزئي", contract: "تعاقد" } as const;
const candidateStatusLabels = { applied: "جديد", screening: "فرز", interview: "مقابلة", offer: "عرض", accepted: "مقبول", rejected: "مرفوض", withdrawn: "منسحب" } as const;
type CandidateStatus = keyof typeof candidateStatusLabels;

export default function RecruitmentOnboarding() {
  const utils = trpc.useUtils();
  const { data, isLoading, isError, error } = trpc.recruitment.overview.useQuery();
  const { data: departments } = trpc.employees.departments.useQuery();
  const { data: employees } = trpc.employees.list.useQuery();
  const [openingDialog, setOpeningDialog] = useState(false);
  const [candidateDialog, setCandidateDialog] = useState(false);
  const [taskDialog, setTaskDialog] = useState(false);
  const [openingTitle, setOpeningTitle] = useState(""); const [openingDepartment, setOpeningDepartment] = useState("none"); const [openingManager, setOpeningManager] = useState("none"); const [openingType, setOpeningType] = useState<keyof typeof employmentTypeLabels>("full_time"); const [openingHeadcount, setOpeningHeadcount] = useState("1"); const [openingDescription, setOpeningDescription] = useState(""); const [openingStatus, setOpeningStatus] = useState<keyof typeof openingStatusLabels>("open");
  const [candidateOpening, setCandidateOpening] = useState("none"); const [candidateName, setCandidateName] = useState(""); const [candidateEmail, setCandidateEmail] = useState(""); const [candidateNote, setCandidateNote] = useState(""); const [candidateStart, setCandidateStart] = useState("");
  const [taskCandidate, setTaskCandidate] = useState("none"); const [taskOwner, setTaskOwner] = useState("none"); const [taskTitle, setTaskTitle] = useState(""); const [taskDue, setTaskDue] = useState("");
  const refresh = () => utils.recruitment.overview.invalidate();
  const createOpening = trpc.recruitment.createOpening.useMutation({ onSuccess: () => { toast.success("تم حفظ الشاغر"); setOpeningDialog(false); setOpeningTitle(""); setOpeningDescription(""); refresh(); }, onError: issue => toast.error("تعذر حفظ الشاغر", { description: issue.message }) });
  const createCandidate = trpc.recruitment.createCandidate.useMutation({ onSuccess: () => { toast.success("تمت إضافة المرشح"); setCandidateDialog(false); setCandidateName(""); setCandidateEmail(""); setCandidateNote(""); refresh(); }, onError: issue => toast.error("تعذر إضافة المرشح", { description: issue.message }) });
  const updateCandidate = trpc.recruitment.updateCandidate.useMutation({ onSuccess: () => { toast.success("تم تحديث حالة المرشح"); refresh(); }, onError: issue => toast.error("تعذر تحديث المرشح", { description: issue.message }) });
  const createTask = trpc.recruitment.createOnboardingTask.useMutation({ onSuccess: () => { toast.success("تمت إضافة مهمة التهيئة"); setTaskDialog(false); setTaskTitle(""); refresh(); }, onError: issue => toast.error("تعذر حفظ المهمة", { description: issue.message }) });
  const completeTask = trpc.recruitment.completeOnboardingTask.useMutation({ onSuccess: () => { toast.success("اكتملت مهمة التهيئة"); refresh(); }, onError: issue => toast.error("تعذر إكمال المهمة", { description: issue.message }) });
  const acceptedCandidates = data?.candidates.filter(item => item.candidate.status === "accepted") ?? [];

  const submitOpening = () => createOpening.mutate({ title: openingTitle.trim(), employmentType: openingType, headcount: Number(openingHeadcount), status: openingStatus, ...(openingDepartment !== "none" ? { departmentId: Number(openingDepartment) } : {}), ...(openingManager !== "none" ? { hiringManagerUserId: Number(openingManager) } : {}), ...(openingDescription.trim() ? { description: openingDescription.trim() } : {}) });
  const submitCandidate = () => createCandidate.mutate({ openingId: Number(candidateOpening), fullName: candidateName.trim(), ...(candidateEmail.trim() ? { email: candidateEmail.trim() } : {}), ...(candidateNote.trim() ? { internalNote: candidateNote.trim() } : {}), ...(candidateStart ? { expectedStartAt: new Date(`${candidateStart}T00:00:00`) } : {}) });
  const submitTask = () => createTask.mutate({ candidateId: Number(taskCandidate), title: taskTitle.trim(), ...(taskOwner !== "none" ? { ownerUserId: Number(taskOwner) } : {}), ...(taskDue ? { dueAt: new Date(`${taskDue}T00:00:00`) } : {}) });

  return <DashboardLayout><div dir="rtl" className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold text-[#5d8d70]">المرحلة 13 · القوى العاملة</p><h1 className="mt-2 text-3xl font-bold text-[#1d4532]">التوظيف والتهيئة</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-[#748178]">إدارة داخلية للشواغر والمرشحين ومهام تهيئة المقبولين، ضمن شركتك وفريق الموارد البشرية فقط.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setCandidateDialog(true)} disabled={!data?.openings.length} className="rounded-xl border-[#d5e3d7] text-[#386f50]"><UserPlus className="ml-2 size-4" />مرشح جديد</Button><Button onClick={() => setOpeningDialog(true)} className="rounded-xl bg-[#1f5b45]"><Plus className="ml-2 size-4" />شاغر جديد</Button></div></div>
    {isLoading ? <div className="mt-8 grid gap-4 md:grid-cols-3">{[1,2,3].map(item => <Skeleton key={item} className="h-36 rounded-3xl" />)}</div> : isError ? <StateCard title="تعذر تحميل التوظيف والتهيئة" text={error.message} error /> : <><section className="mt-7 grid gap-4 sm:grid-cols-3"><Stat label="الشواغر المفتوحة" value={data?.openings.filter(item => item.opening.status === "open").length ?? 0} /><Stat label="المرشحون النشطون" value={data?.candidates.filter(item => !["rejected", "withdrawn"].includes(item.candidate.status)).length ?? 0} /><Stat label="مهام التهيئة المعلقة" value={data?.onboardingTasks.filter(item => item.task.status === "pending").length ?? 0} /></section>
      <section className="mt-8 grid gap-6 xl:grid-cols-2"><Panel title="الشواغر" icon={BriefcaseBusiness} action={<Button size="sm" variant="outline" onClick={() => setOpeningDialog(true)} className="rounded-xl border-[#d5e3d7] text-[#386f50]"><Plus className="ml-1 size-4" />إضافة</Button>}>{data?.openings.length ? <div className="grid gap-3">{data.openings.map(item => <article key={item.opening.id} className="rounded-2xl border border-[#e4ebe5] p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold text-[#294535]">{item.opening.title}</h2><p className="mt-1 text-xs text-[#718075]">{item.department?.name || "دون قسم"} · {employmentTypeLabels[item.opening.employmentType]} · {item.opening.headcount} مقعد</p></div><StatusPill label={openingStatusLabels[item.opening.status]} tone={item.opening.status === "open" ? "green" : "neutral"} /></div><p className="mt-3 text-xs leading-6 text-[#748178]">مدير التوظيف: {item.manager?.name || "غير محدد"}</p></article>)}</div> : <CompactEmpty text="أضف شاغراً لتبدأ إدارة الترشيحات." />}</Panel>
        <Panel title="المرشحون" icon={UsersRound} action={<Button size="sm" variant="outline" onClick={() => setCandidateDialog(true)} disabled={!data?.openings.length} className="rounded-xl border-[#d5e3d7] text-[#386f50]"><UserPlus className="ml-1 size-4" />إضافة</Button>}>{data?.candidates.length ? <div className="grid gap-3">{data.candidates.map(item => <article key={item.candidate.id} className="rounded-2xl border border-[#e4ebe5] p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold text-[#294535]">{item.candidate.fullName}</h2><p className="mt-1 text-xs text-[#718075]">{item.opening.title}{item.candidate.email ? ` · ${item.candidate.email}` : ""}</p></div><StatusPill label={candidateStatusLabels[item.candidate.status]} tone={item.candidate.status === "accepted" ? "green" : item.candidate.status === "rejected" ? "red" : "neutral"} /></div><div className="mt-3 flex gap-2"><Select value={item.candidate.status} onValueChange={value => updateCandidate.mutate({ candidateId: item.candidate.id, status: value as CandidateStatus })}><SelectTrigger className="h-9"><SelectValue /></SelectTrigger><SelectContent>{Object.entries(candidateStatusLabels).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></div></article>)}</div> : <CompactEmpty text="أضف مرشحاً بعد إنشاء شاغر مفتوح." />}</Panel></section>
      <section className="mt-6"><Panel title="تهيئة المقبولين" icon={ClipboardCheck} action={<Button size="sm" variant="outline" onClick={() => setTaskDialog(true)} disabled={!acceptedCandidates.length} className="rounded-xl border-[#d5e3d7] text-[#386f50]"><Plus className="ml-1 size-4" />مهمة تهيئة</Button>}>{data?.onboardingTasks.length ? <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.onboardingTasks.map(item => <article key={item.task.id} className="rounded-2xl border border-[#e4ebe5] p-4"><div className="flex items-start justify-between"><div><h2 className="font-bold text-[#294535]">{item.task.title}</h2><p className="mt-1 text-xs text-[#718075]">{item.candidate.fullName} · {item.owner?.name || "دون مالك"}</p></div><StatusPill label={item.task.status === "completed" ? "مكتملة" : "بانتظار التنفيذ"} tone={item.task.status === "completed" ? "green" : "neutral"} /></div>{item.task.status === "pending" && <Button size="sm" variant="outline" onClick={() => completeTask.mutate({ taskId: item.task.id })} disabled={completeTask.isPending} className="mt-4 h-8 w-full rounded-lg border-[#cfe0d2] text-[#367850]"><CheckCircle2 className="ml-1 size-4" />إكمال المهمة</Button>}</article>)}</div> : <CompactEmpty text="بعد قبول مرشح، أنشئ مهام تهيئة قبل تاريخ بدء العمل." />}</Panel></section></>}

    <Dialog open={openingDialog} onOpenChange={setOpeningDialog}><DialogContent dir="rtl" className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>شاغر وظيفي جديد</DialogTitle><DialogDescription>البيانات مرئية لفريق الموارد البشرية والمسؤولين في الشركة فقط.</DialogDescription></DialogHeader><div className="grid gap-4 py-3"><Field label="المسمى الوظيفي"><Input value={openingTitle} onChange={event => setOpeningTitle(event.target.value)} placeholder="مثال: أخصائي موارد بشرية" /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="القسم"><Select value={openingDepartment} onValueChange={setOpeningDepartment}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">دون قسم</SelectItem>{departments?.map(item => <SelectItem key={item.id} value={String(item.id)}>{item.name}</SelectItem>)}</SelectContent></Select></Field><Field label="مدير التوظيف"><Select value={openingManager} onValueChange={setOpeningManager}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">غير محدد</SelectItem>{employees?.map(item => <SelectItem key={item.id} value={String(item.id)}>{item.name || "موظف"}</SelectItem>)}</SelectContent></Select></Field></div><div className="grid gap-4 sm:grid-cols-3"><Field label="نوع التعاقد"><Select value={openingType} onValueChange={value => setOpeningType(value as keyof typeof employmentTypeLabels)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{Object.entries(employmentTypeLabels).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></Field><Field label="عدد المقاعد"><Input type="number" min="1" max="100" value={openingHeadcount} onChange={event => setOpeningHeadcount(event.target.value)} /></Field><Field label="الحالة"><Select value={openingStatus} onValueChange={value => setOpeningStatus(value as keyof typeof openingStatusLabels)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{Object.entries(openingStatusLabels).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></Field></div><Field label="وصف داخلي"><Textarea value={openingDescription} onChange={event => setOpeningDescription(event.target.value)} /></Field></div><DialogFooter><Button variant="outline" onClick={() => setOpeningDialog(false)}>إلغاء</Button><Button onClick={submitOpening} disabled={createOpening.isPending || openingTitle.trim().length < 2 || Number(openingHeadcount) < 1} className="bg-[#1f5b45]">حفظ الشاغر</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={candidateDialog} onOpenChange={setCandidateDialog}><DialogContent dir="rtl"><DialogHeader><DialogTitle>مرشح جديد</DialogTitle><DialogDescription>تُحفظ بيانات الاتصال للاستخدام الداخلي في عملية التوظيف فقط.</DialogDescription></DialogHeader><div className="grid gap-4 py-3"><Field label="الشاغر"><Select value={candidateOpening} onValueChange={setCandidateOpening}><SelectTrigger><SelectValue placeholder="اختر شاغراً" /></SelectTrigger><SelectContent>{data?.openings.filter(item => item.opening.status === "open").map(item => <SelectItem key={item.opening.id} value={String(item.opening.id)}>{item.opening.title}</SelectItem>)}</SelectContent></Select></Field><Field label="الاسم الكامل"><Input value={candidateName} onChange={event => setCandidateName(event.target.value)} /></Field><Field label="البريد الإلكتروني"><Input type="email" value={candidateEmail} onChange={event => setCandidateEmail(event.target.value)} /></Field><Field label="تاريخ البدء المتوقع"><Input type="date" value={candidateStart} onChange={event => setCandidateStart(event.target.value)} /></Field><Field label="ملاحظة داخلية"><Textarea value={candidateNote} onChange={event => setCandidateNote(event.target.value)} /></Field></div><DialogFooter><Button variant="outline" onClick={() => setCandidateDialog(false)}>إلغاء</Button><Button onClick={submitCandidate} disabled={createCandidate.isPending || candidateOpening === "none" || candidateName.trim().length < 2} className="bg-[#1f5b45]">حفظ المرشح</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={taskDialog} onOpenChange={setTaskDialog}><DialogContent dir="rtl"><DialogHeader><DialogTitle>مهمة تهيئة</DialogTitle><DialogDescription>لا تُنشأ إلا للمرشحين المقبولين، وتبقى داخل الشركة الحالية.</DialogDescription></DialogHeader><div className="grid gap-4 py-3"><Field label="المرشح المقبول"><Select value={taskCandidate} onValueChange={setTaskCandidate}><SelectTrigger><SelectValue placeholder="اختر مرشحاً" /></SelectTrigger><SelectContent>{acceptedCandidates.map(item => <SelectItem key={item.candidate.id} value={String(item.candidate.id)}>{item.candidate.fullName}</SelectItem>)}</SelectContent></Select></Field><Field label="مالك المهمة"><Select value={taskOwner} onValueChange={setTaskOwner}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">غير محدد</SelectItem>{employees?.map(item => <SelectItem key={item.id} value={String(item.id)}>{item.name || "موظف"}</SelectItem>)}</SelectContent></Select></Field><Field label="عنوان المهمة"><Input value={taskTitle} onChange={event => setTaskTitle(event.target.value)} placeholder="مثال: تجهيز حساب المنصة" /></Field><Field label="تاريخ الاستحقاق"><Input type="date" value={taskDue} onChange={event => setTaskDue(event.target.value)} /></Field></div><DialogFooter><Button variant="outline" onClick={() => setTaskDialog(false)}>إلغاء</Button><Button onClick={submitTask} disabled={createTask.isPending || taskCandidate === "none" || taskTitle.trim().length < 2} className="bg-[#1f5b45]">إضافة المهمة</Button></DialogFooter></DialogContent></Dialog>
  </div></DashboardLayout>;
}

function Panel({ title, icon: Icon, action, children }: { title: string; icon: typeof BriefcaseBusiness; action: React.ReactNode; children: React.ReactNode }) { return <section className="rounded-3xl border border-[#dfe9e1] bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><span className="flex size-9 items-center justify-center rounded-xl bg-[#e9f4eb] text-[#347950]"><Icon className="size-4" /></span><h2 className="font-bold text-[#294535]">{title}</h2></div>{action}</div><div className="mt-5">{children}</div></section>; }
function Stat({ label, value }: { label: string; value: number }) { return <article className="rounded-3xl border border-[#dfe9e1] bg-white p-5"><p className="text-xs font-bold text-[#758278]">{label}</p><p className="mt-3 text-3xl font-bold text-[#1f5b45]">{value}</p></article>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div><label className="mb-2 block text-xs font-bold text-[#61756a]">{label}</label>{children}</div>; }
function StatusPill({ label, tone }: { label: string; tone: "green" | "red" | "neutral" }) { const styles = { green: "bg-[#e7f4ea] text-[#30774e]", red: "bg-[#fdecea] text-[#a94e48]", neutral: "bg-[#f1f3f1] text-[#65736a]" }; return <span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${styles[tone]}`}>{label}</span>; }
function CompactEmpty({ text }: { text: string }) { return <div className="rounded-2xl bg-[#f7f9f7] px-4 py-7 text-center text-sm text-[#758178]">{text}</div>; }
function StateCard({ title, text, error = false }: { title: string; text: string; error?: boolean }) { return <div className="mt-8 flex min-h-72 flex-col items-center justify-center rounded-3xl border border-[#dfe9e1] bg-white px-6 text-center"><span className={`flex size-14 items-center justify-center rounded-3xl ${error ? "bg-[#fdecea] text-[#a94e48]" : "bg-[#eaf3eb] text-[#357b53]"}`}>{error ? <ShieldAlert className="size-6" /> : <UsersRound className="size-6" />}</span><h2 className="mt-5 font-bold text-[#294535]">{title}</h2><p className="mt-2 max-w-md text-sm leading-6 text-[#748178]">{text}</p></div>; }
