import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { BriefcaseBusiness, CalendarDays, CheckCircle2, ClipboardCheck, FileCheck2, MessageSquareText, Plus, ShieldAlert, UserPlus, UsersRound, type LucideIcon } from "lucide-react";
import { useState, type ReactNode } from "react";
import { toast } from "sonner";

const openingStatusLabels = { draft: "مسودة", open: "مفتوح", closed: "مغلق" } as const;
const employmentTypeLabels = { full_time: "دوام كامل", part_time: "دوام جزئي", contract: "تعاقد" } as const;
const candidateStatusLabels = { applied: "جديد", screening: "فرز", interview: "مقابلة", offer: "عرض", accepted: "مقبول", rejected: "مرفوض", withdrawn: "منسحب" } as const;
const interviewStatusLabels = { scheduled: "مجدولة", completed: "مكتملة", cancelled: "ملغاة" } as const;
const interviewChannelLabels = { in_person: "حضورية", video: "مرئية", phone: "هاتفية" } as const;
const offerStatusLabels = { draft: "مسودة داخلية", issued: "جاهز للعرض", accepted: "مقبول", declined: "مرفوض", withdrawn: "مسحوب" } as const;
type CandidateStatus = keyof typeof candidateStatusLabels;
type InterviewStatus = keyof typeof interviewStatusLabels;
type InterviewChannel = keyof typeof interviewChannelLabels;
type OfferStatus = keyof typeof offerStatusLabels;

const candidateTransitions: Record<CandidateStatus, CandidateStatus[]> = { applied: ["applied", "screening", "interview", "rejected", "withdrawn"], screening: ["screening", "interview", "rejected", "withdrawn"], interview: ["interview", "offer", "rejected", "withdrawn"], offer: ["offer", "accepted", "rejected", "withdrawn"], accepted: ["accepted"], rejected: ["rejected"], withdrawn: ["withdrawn"] };
const interviewTransitions: Record<InterviewStatus, InterviewStatus[]> = { scheduled: ["scheduled", "completed", "cancelled"], completed: ["completed"], cancelled: ["cancelled"] };
const offerTransitions: Record<OfferStatus, OfferStatus[]> = { draft: ["draft", "issued", "withdrawn"], issued: ["issued", "accepted", "declined", "withdrawn"], accepted: ["accepted"], declined: ["declined"], withdrawn: ["withdrawn"] };

const dateTime = (value: Date | null) => value ? new Intl.DateTimeFormat("ar-SA", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "غير محدد";
const dateOnly = (value: Date | null) => value ? new Intl.DateTimeFormat("ar-SA", { dateStyle: "medium" }).format(new Date(value)) : "غير محدد";

export default function RecruitmentOnboarding() {
  const utils = trpc.useUtils();
  const { data, isLoading, isError, error } = trpc.recruitment.overview.useQuery();
  const { data: departments } = trpc.employees.departments.useQuery();
  const { data: employees } = trpc.employees.list.useQuery();
  const [openingDialog, setOpeningDialog] = useState(false);
  const [candidateDialog, setCandidateDialog] = useState(false);
  const [interviewDialog, setInterviewDialog] = useState(false);
  const [offerDialog, setOfferDialog] = useState(false);
  const [taskDialog, setTaskDialog] = useState(false);
  const [templateDialog, setTemplateDialog] = useState(false);
  const [applyTemplateDialog, setApplyTemplateDialog] = useState(false);
  const [openingTitle, setOpeningTitle] = useState(""); const [openingDepartment, setOpeningDepartment] = useState("none"); const [openingManager, setOpeningManager] = useState("none"); const [openingType, setOpeningType] = useState<keyof typeof employmentTypeLabels>("full_time"); const [openingHeadcount, setOpeningHeadcount] = useState("1"); const [openingDescription, setOpeningDescription] = useState(""); const [openingStatus, setOpeningStatus] = useState<keyof typeof openingStatusLabels>("open");
  const [candidateOpening, setCandidateOpening] = useState("none"); const [candidateName, setCandidateName] = useState(""); const [candidateEmail, setCandidateEmail] = useState(""); const [candidateNote, setCandidateNote] = useState(""); const [candidateStart, setCandidateStart] = useState("");
  const [interviewCandidate, setInterviewCandidate] = useState("none"); const [interviewInterviewer, setInterviewInterviewer] = useState("none"); const [interviewScheduledAt, setInterviewScheduledAt] = useState(""); const [interviewChannel, setInterviewChannel] = useState<InterviewChannel>("video"); const [interviewSummary, setInterviewSummary] = useState("");
  const [offerCandidate, setOfferCandidate] = useState("none"); const [offerStart, setOfferStart] = useState(""); const [offerResponseDue, setOfferResponseDue] = useState(""); const [offerNote, setOfferNote] = useState("");
  const [taskCandidate, setTaskCandidate] = useState("none"); const [taskOwner, setTaskOwner] = useState("none"); const [taskTitle, setTaskTitle] = useState(""); const [taskDue, setTaskDue] = useState("");
  const [templateTitle, setTemplateTitle] = useState(""); const [templateOwner, setTemplateOwner] = useState("none"); const [templateOffset, setTemplateOffset] = useState("0");
  const [selectedTemplate, setSelectedTemplate] = useState("none"); const [templateCandidate, setTemplateCandidate] = useState("none");
  const refresh = () => utils.recruitment.overview.invalidate();
  const createOpening = trpc.recruitment.createOpening.useMutation({ onSuccess: () => { toast.success("تم حفظ الشاغر"); setOpeningDialog(false); setOpeningTitle(""); setOpeningDescription(""); refresh(); }, onError: issue => toast.error("تعذر حفظ الشاغر", { description: issue.message }) });
  const createCandidate = trpc.recruitment.createCandidate.useMutation({ onSuccess: () => { toast.success("تمت إضافة المرشح"); setCandidateDialog(false); setCandidateName(""); setCandidateEmail(""); setCandidateNote(""); refresh(); }, onError: issue => toast.error("تعذر إضافة المرشح", { description: issue.message }) });
  const updateCandidate = trpc.recruitment.updateCandidate.useMutation({ onSuccess: () => { toast.success("تم تحديث مرحلة المرشح"); refresh(); }, onError: issue => toast.error("تعذر تحديث المرشح", { description: issue.message }) });
  const createInterview = trpc.recruitment.createInterview.useMutation({ onSuccess: () => { toast.success("تمت جدولة المقابلة"); setInterviewDialog(false); setInterviewScheduledAt(""); setInterviewSummary(""); refresh(); }, onError: issue => toast.error("تعذر جدولة المقابلة", { description: issue.message }) });
  const updateInterview = trpc.recruitment.updateInterview.useMutation({ onSuccess: () => { toast.success("تم تحديث حالة المقابلة"); refresh(); }, onError: issue => toast.error("تعذر تحديث المقابلة", { description: issue.message }) });
  const createOffer = trpc.recruitment.createOffer.useMutation({ onSuccess: () => { toast.success("تم حفظ العرض الداخلي"); setOfferDialog(false); setOfferStart(""); setOfferResponseDue(""); setOfferNote(""); refresh(); }, onError: issue => toast.error("تعذر حفظ العرض الداخلي", { description: issue.message }) });
  const updateOffer = trpc.recruitment.updateOffer.useMutation({ onSuccess: () => { toast.success("تم تحديث حالة العرض"); refresh(); }, onError: issue => toast.error("تعذر تحديث العرض", { description: issue.message }) });
  const createTask = trpc.recruitment.createOnboardingTask.useMutation({ onSuccess: () => { toast.success("تمت إضافة مهمة التهيئة"); setTaskDialog(false); setTaskTitle(""); refresh(); }, onError: issue => toast.error("تعذر حفظ المهمة", { description: issue.message }) });
  const createTemplate = trpc.recruitment.createOnboardingTemplate.useMutation({ onSuccess: () => { toast.success("تم حفظ قالب التهيئة"); setTemplateDialog(false); setTemplateTitle(""); setTemplateOffset("0"); refresh(); }, onError: issue => toast.error("تعذر حفظ قالب التهيئة", { description: issue.message }) });
  const applyTemplate = trpc.recruitment.applyOnboardingTemplate.useMutation({ onSuccess: () => { toast.success("تم تطبيق قالب التهيئة"); setApplyTemplateDialog(false); refresh(); }, onError: issue => toast.error("تعذر تطبيق قالب التهيئة", { description: issue.message }) });
  const completeTask = trpc.recruitment.completeOnboardingTask.useMutation({ onSuccess: () => { toast.success("اكتملت مهمة التهيئة"); refresh(); }, onError: issue => toast.error("تعذر إكمال المهمة", { description: issue.message }) });
  const acceptedCandidates = data?.candidates.filter(item => item.candidate.status === "accepted") ?? [];
  const interviewCandidates = data?.candidates.filter(item => ["applied", "screening", "interview"].includes(item.candidate.status)) ?? [];
  const offerCandidates = data?.candidates.filter(item => item.candidate.status === "interview") ?? [];

  const submitOpening = () => createOpening.mutate({ title: openingTitle.trim(), employmentType: openingType, headcount: Number(openingHeadcount), status: openingStatus, ...(openingDepartment !== "none" ? { departmentId: Number(openingDepartment) } : {}), ...(openingManager !== "none" ? { hiringManagerUserId: Number(openingManager) } : {}), ...(openingDescription.trim() ? { description: openingDescription.trim() } : {}) });
  const submitCandidate = () => createCandidate.mutate({ openingId: Number(candidateOpening), fullName: candidateName.trim(), ...(candidateEmail.trim() ? { email: candidateEmail.trim() } : {}), ...(candidateNote.trim() ? { internalNote: candidateNote.trim() } : {}), ...(candidateStart ? { expectedStartAt: new Date(`${candidateStart}T00:00:00`) } : {}) });
  const submitInterview = () => createInterview.mutate({ candidateId: Number(interviewCandidate), interviewerUserId: Number(interviewInterviewer), scheduledAt: new Date(interviewScheduledAt), channel: interviewChannel, ...(interviewSummary.trim() ? { internalSummary: interviewSummary.trim() } : {}) });
  const submitOffer = () => createOffer.mutate({ candidateId: Number(offerCandidate), ...(offerStart ? { proposedStartAt: new Date(`${offerStart}T00:00:00`) } : {}), ...(offerResponseDue ? { responseDueAt: new Date(`${offerResponseDue}T00:00:00`) } : {}), ...(offerNote.trim() ? { internalNote: offerNote.trim() } : {}) });
  const submitTask = () => createTask.mutate({ candidateId: Number(taskCandidate), title: taskTitle.trim(), ...(taskOwner !== "none" ? { ownerUserId: Number(taskOwner) } : {}), ...(taskDue ? { dueAt: new Date(`${taskDue}T00:00:00`) } : {}) });
  const submitTemplate = () => createTemplate.mutate({ title: templateTitle.trim(), dueOffsetDays: Number(templateOffset), ...(templateOwner !== "none" ? { defaultOwnerUserId: Number(templateOwner) } : {}) });
  const submitApplyTemplate = () => applyTemplate.mutate({ templateId: Number(selectedTemplate), candidateId: Number(templateCandidate) });

  return <DashboardLayout><div dir="rtl" className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold text-[#5d8d70]">المرحلة 13 · القوى العاملة</p><h1 className="mt-2 text-3xl font-bold text-[#1d4532]">التوظيف والتهيئة</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-[#748178]">إدارة داخلية للشواغر والمرشحين والمقابلات والعروض غير المالية ومهام التهيئة، ضمن شركتك وفريق الموارد البشرية فقط.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setCandidateDialog(true)} disabled={!data?.openings.length} className="rounded-xl border-[#d5e3d7] text-[#386f50]"><UserPlus className="ml-2 size-4" />مرشح جديد</Button><Button variant="outline" onClick={() => setInterviewDialog(true)} disabled={!interviewCandidates.length || !employees?.length} className="rounded-xl border-[#d5e3d7] text-[#386f50]"><CalendarDays className="ml-2 size-4" />مقابلة</Button><Button variant="outline" onClick={() => setOfferDialog(true)} disabled={!offerCandidates.length} className="rounded-xl border-[#d5e3d7] text-[#386f50]"><FileCheck2 className="ml-2 size-4" />عرض داخلي</Button><Button onClick={() => setOpeningDialog(true)} className="rounded-xl bg-[#1f5b45]"><Plus className="ml-2 size-4" />شاغر جديد</Button></div></div>
    {isLoading ? <div className="mt-8 grid gap-4 md:grid-cols-3">{[1,2,3].map(item => <Skeleton key={item} className="h-36 rounded-3xl" />)}</div> : isError ? <StateCard title="تعذر تحميل التوظيف والتهيئة" text={error.message} error /> : <><section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Stat label="الشواغر المفتوحة" value={data?.openings.filter(item => item.opening.status === "open").length ?? 0} /><Stat label="المرشحون النشطون" value={data?.candidates.filter(item => !["rejected", "withdrawn"].includes(item.candidate.status)).length ?? 0} /><Stat label="المقابلات المجدولة" value={data?.interviews.filter(item => item.interview.status === "scheduled").length ?? 0} /><Stat label="العروض الجاهزة" value={data?.offers.filter(item => item.offer.status === "issued").length ?? 0} /><Stat label="مهام التهيئة المعلقة" value={data?.onboardingTasks.filter(item => item.task.status === "pending").length ?? 0} /></section>
      <section className="mt-8 grid gap-6 xl:grid-cols-2"><Panel title="الشواغر" icon={BriefcaseBusiness} action={<Button size="sm" variant="outline" onClick={() => setOpeningDialog(true)} className="rounded-xl border-[#d5e3d7] text-[#386f50]"><Plus className="ml-1 size-4" />إضافة</Button>}>{data?.openings.length ? <div className="grid gap-3">{data.openings.map(item => <article key={item.opening.id} className="rounded-2xl border border-[#e4ebe5] p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold text-[#294535]">{item.opening.title}</h2><p className="mt-1 text-xs text-[#718075]">{item.department?.name || "دون قسم"} · {employmentTypeLabels[item.opening.employmentType]} · {item.opening.headcount} مقعد</p></div><StatusPill label={openingStatusLabels[item.opening.status]} tone={item.opening.status === "open" ? "green" : "neutral"} /></div><p className="mt-3 text-xs leading-6 text-[#748178]">مدير التوظيف: {item.manager?.name || "غير محدد"}</p></article>)}</div> : <CompactEmpty text="أضف شاغراً لتبدأ إدارة الترشيحات." />}</Panel>
        <Panel title="المرشحون" icon={UsersRound} action={<Button size="sm" variant="outline" onClick={() => setCandidateDialog(true)} disabled={!data?.openings.length} className="rounded-xl border-[#d5e3d7] text-[#386f50]"><UserPlus className="ml-1 size-4" />إضافة</Button>}>{data?.candidates.length ? <div className="grid gap-3">{data.candidates.map(item => <article key={item.candidate.id} className="rounded-2xl border border-[#e4ebe5] p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold text-[#294535]">{item.candidate.fullName}</h2><p className="mt-1 text-xs text-[#718075]">{item.opening.title}{item.candidate.email ? ` · ${item.candidate.email}` : ""}</p></div><StatusPill label={candidateStatusLabels[item.candidate.status]} tone={item.candidate.status === "accepted" ? "green" : item.candidate.status === "rejected" ? "red" : "neutral"} /></div><div className="mt-3 flex gap-2"><Select value={item.candidate.status} onValueChange={value => updateCandidate.mutate({ candidateId: item.candidate.id, status: value as CandidateStatus })}><SelectTrigger className="h-9"><SelectValue /></SelectTrigger><SelectContent>{candidateTransitions[item.candidate.status].map(value => <SelectItem key={value} value={value}>{candidateStatusLabels[value]}</SelectItem>)}</SelectContent></Select></div></article>)}</div> : <CompactEmpty text="أضف مرشحاً بعد إنشاء شاغر مفتوح." />}</Panel></section>
      <section className="mt-6 grid gap-6 xl:grid-cols-2"><Panel title="المقابلات" icon={MessageSquareText} action={<Button size="sm" variant="outline" onClick={() => setInterviewDialog(true)} disabled={!interviewCandidates.length || !employees?.length} className="rounded-xl border-[#d5e3d7] text-[#386f50]"><Plus className="ml-1 size-4" />جدولة</Button>}>{data?.interviews.length ? <div className="grid gap-3">{data.interviews.map(item => <article key={item.interview.id} className="rounded-2xl border border-[#e4ebe5] p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold text-[#294535]">{item.candidate.fullName}</h2><p className="mt-1 text-xs text-[#718075]">{item.opening.title} · {item.interviewer.name || "محاور"}</p></div><StatusPill label={interviewStatusLabels[item.interview.status]} tone={item.interview.status === "completed" ? "green" : item.interview.status === "cancelled" ? "red" : "neutral"} /></div><p className="mt-3 text-xs text-[#748178]">{interviewChannelLabels[item.interview.channel]} · {dateTime(item.interview.scheduledAt)}</p>{item.interview.internalSummary && <p className="mt-2 text-xs leading-6 text-[#61756a]">{item.interview.internalSummary}</p>}<Select value={item.interview.status} onValueChange={value => updateInterview.mutate({ interviewId: item.interview.id, status: value as InterviewStatus })}><SelectTrigger className="mt-3 h-9"><SelectValue /></SelectTrigger><SelectContent>{interviewTransitions[item.interview.status].map(value => <SelectItem key={value} value={value}>{interviewStatusLabels[value]}</SelectItem>)}</SelectContent></Select></article>)}</div> : <CompactEmpty text="جدول مقابلة لبدء مرحلة التقييم الداخلية." />}</Panel>
        <Panel title="العروض الداخلية" icon={FileCheck2} action={<Button size="sm" variant="outline" onClick={() => setOfferDialog(true)} disabled={!offerCandidates.length} className="rounded-xl border-[#d5e3d7] text-[#386f50]"><Plus className="ml-1 size-4" />عرض</Button>}>{data?.offers.length ? <div className="grid gap-3">{data.offers.map(item => <article key={item.offer.id} className="rounded-2xl border border-[#e4ebe5] p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold text-[#294535]">{item.candidate.fullName}</h2><p className="mt-1 text-xs text-[#718075]">{item.opening.title}</p></div><StatusPill label={offerStatusLabels[item.offer.status]} tone={item.offer.status === "accepted" ? "green" : ["declined", "withdrawn"].includes(item.offer.status) ? "red" : "neutral"} /></div><p className="mt-3 text-xs text-[#748178]">بدء مقترح: {dateOnly(item.offer.proposedStartAt)} · مهلة الرد: {dateOnly(item.offer.responseDueAt)}</p>{item.offer.internalNote && <p className="mt-2 text-xs leading-6 text-[#61756a]">{item.offer.internalNote}</p>}<Select value={item.offer.status} onValueChange={value => updateOffer.mutate({ offerId: item.offer.id, status: value as OfferStatus })}><SelectTrigger className="mt-3 h-9"><SelectValue /></SelectTrigger><SelectContent>{offerTransitions[item.offer.status].map(value => <SelectItem key={value} value={value}>{offerStatusLabels[value]}</SelectItem>)}</SelectContent></Select></article>)}</div> : <CompactEmpty text="بعد اكتمال المقابلة، أنشئ عرضاً داخلياً غير مالي." />}</Panel></section>
      <section className="mt-6"><Panel title="تهيئة المقبولين" icon={ClipboardCheck} action={<Button size="sm" variant="outline" onClick={() => setTaskDialog(true)} disabled={!acceptedCandidates.length} className="rounded-xl border-[#d5e3d7] text-[#386f50]"><Plus className="ml-1 size-4" />مهمة تهيئة</Button>}>{data?.onboardingTasks.length ? <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.onboardingTasks.map(item => <article key={item.task.id} className="rounded-2xl border border-[#e4ebe5] p-4"><div className="flex items-start justify-between"><div><h2 className="font-bold text-[#294535]">{item.task.title}</h2><p className="mt-1 text-xs text-[#718075]">{item.candidate.fullName} · {item.owner?.name || "دون مالك"}</p></div><StatusPill label={item.task.status === "completed" ? "مكتملة" : "بانتظار التنفيذ"} tone={item.task.status === "completed" ? "green" : "neutral"} /></div>{item.task.status === "pending" && <Button size="sm" variant="outline" onClick={() => completeTask.mutate({ taskId: item.task.id })} disabled={completeTask.isPending} className="mt-4 h-8 w-full rounded-lg border-[#cfe0d2] text-[#367850]"><CheckCircle2 className="ml-1 size-4" />إكمال المهمة</Button>}</article>)}</div> : <CompactEmpty text="بعد قبول عرض داخلي، أنشئ مهام تهيئة قبل تاريخ بدء العمل." />}</Panel></section>
      <section className="mt-6"><Panel title="قوالب مهام التهيئة" icon={ClipboardCheck} action={<div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => setApplyTemplateDialog(true)} disabled={!data?.onboardingTemplates.length || !acceptedCandidates.length} className="rounded-xl border-[#d5e3d7] text-[#386f50]"><CheckCircle2 className="ml-1 size-4" />تطبيق</Button><Button size="sm" variant="outline" onClick={() => setTemplateDialog(true)} className="rounded-xl border-[#d5e3d7] text-[#386f50]"><Plus className="ml-1 size-4" />قالب</Button></div>}>{data?.onboardingTemplates.length ? <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.onboardingTemplates.map(item => <article key={item.template.id} className="rounded-2xl border border-[#e4ebe5] p-4"><h2 className="font-bold text-[#294535]">{item.template.title}</h2><p className="mt-2 text-xs leading-6 text-[#718075]">المالك الافتراضي: {item.owner?.name || "غير محدد"}</p><p className="text-xs leading-6 text-[#718075]">الاستحقاق: بعد {item.template.dueOffsetDays} يوم من تاريخ البدء المتوقع.</p></article>)}</div> : <CompactEmpty text="أنشئ قالباً داخلياً لتكرار مهام تهيئة متسقة للمرشحين المقبولين." />}</Panel></section></>}

    <Dialog open={openingDialog} onOpenChange={setOpeningDialog}><DialogContent dir="rtl" className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>شاغر وظيفي جديد</DialogTitle><DialogDescription>البيانات مرئية لفريق الموارد البشرية والمسؤولين في الشركة فقط.</DialogDescription></DialogHeader><div className="grid gap-4 py-3"><Field label="المسمى الوظيفي"><Input value={openingTitle} onChange={event => setOpeningTitle(event.target.value)} placeholder="مثال: أخصائي موارد بشرية" /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="القسم"><Select value={openingDepartment} onValueChange={setOpeningDepartment}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">دون قسم</SelectItem>{departments?.map(item => <SelectItem key={item.id} value={String(item.id)}>{item.name}</SelectItem>)}</SelectContent></Select></Field><Field label="مدير التوظيف"><Select value={openingManager} onValueChange={setOpeningManager}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">غير محدد</SelectItem>{employees?.map(item => <SelectItem key={item.id} value={String(item.id)}>{item.name || "موظف"}</SelectItem>)}</SelectContent></Select></Field></div><div className="grid gap-4 sm:grid-cols-3"><Field label="نوع التعاقد"><Select value={openingType} onValueChange={value => setOpeningType(value as keyof typeof employmentTypeLabels)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{Object.entries(employmentTypeLabels).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></Field><Field label="عدد المقاعد"><Input type="number" min="1" max="100" value={openingHeadcount} onChange={event => setOpeningHeadcount(event.target.value)} /></Field><Field label="الحالة"><Select value={openingStatus} onValueChange={value => setOpeningStatus(value as keyof typeof openingStatusLabels)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{Object.entries(openingStatusLabels).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></Field></div><Field label="وصف داخلي"><Textarea value={openingDescription} onChange={event => setOpeningDescription(event.target.value)} /></Field></div><DialogFooter><Button variant="outline" onClick={() => setOpeningDialog(false)}>إلغاء</Button><Button onClick={submitOpening} disabled={createOpening.isPending || openingTitle.trim().length < 2 || Number(openingHeadcount) < 1} className="bg-[#1f5b45]">حفظ الشاغر</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={candidateDialog} onOpenChange={setCandidateDialog}><DialogContent dir="rtl"><DialogHeader><DialogTitle>مرشح جديد</DialogTitle><DialogDescription>تُحفظ بيانات الاتصال للاستخدام الداخلي في عملية التوظيف فقط.</DialogDescription></DialogHeader><div className="grid gap-4 py-3"><Field label="الشاغر"><Select value={candidateOpening} onValueChange={setCandidateOpening}><SelectTrigger><SelectValue placeholder="اختر شاغراً" /></SelectTrigger><SelectContent>{data?.openings.filter(item => item.opening.status === "open").map(item => <SelectItem key={item.opening.id} value={String(item.opening.id)}>{item.opening.title}</SelectItem>)}</SelectContent></Select></Field><Field label="الاسم الكامل"><Input value={candidateName} onChange={event => setCandidateName(event.target.value)} /></Field><Field label="البريد الإلكتروني"><Input type="email" value={candidateEmail} onChange={event => setCandidateEmail(event.target.value)} /></Field><Field label="تاريخ البدء المتوقع"><Input type="date" value={candidateStart} onChange={event => setCandidateStart(event.target.value)} /></Field><Field label="ملاحظة داخلية"><Textarea value={candidateNote} onChange={event => setCandidateNote(event.target.value)} /></Field></div><DialogFooter><Button variant="outline" onClick={() => setCandidateDialog(false)}>إلغاء</Button><Button onClick={submitCandidate} disabled={createCandidate.isPending || candidateOpening === "none" || candidateName.trim().length < 2} className="bg-[#1f5b45]">حفظ المرشح</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={interviewDialog} onOpenChange={setInterviewDialog}><DialogContent dir="rtl"><DialogHeader><DialogTitle>جدولة مقابلة داخلية</DialogTitle><DialogDescription>لا تُرسل دعوات أو بيانات إلى خدمة خارجية في هذه الدفعة.</DialogDescription></DialogHeader><div className="grid gap-4 py-3"><Field label="المرشح"><Select value={interviewCandidate} onValueChange={setInterviewCandidate}><SelectTrigger><SelectValue placeholder="اختر مرشحاً" /></SelectTrigger><SelectContent>{interviewCandidates.map(item => <SelectItem key={item.candidate.id} value={String(item.candidate.id)}>{item.candidate.fullName} · {item.opening.title}</SelectItem>)}</SelectContent></Select></Field><Field label="محاور من الشركة"><Select value={interviewInterviewer} onValueChange={setInterviewInterviewer}><SelectTrigger><SelectValue placeholder="اختر محاوراً" /></SelectTrigger><SelectContent>{employees?.map(item => <SelectItem key={item.id} value={String(item.id)}>{item.name || "موظف"}</SelectItem>)}</SelectContent></Select></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="الموعد"><Input type="datetime-local" value={interviewScheduledAt} onChange={event => setInterviewScheduledAt(event.target.value)} /></Field><Field label="قناة المقابلة"><Select value={interviewChannel} onValueChange={value => setInterviewChannel(value as InterviewChannel)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{Object.entries(interviewChannelLabels).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></Field></div><Field label="ملخص أو تحضير داخلي"><Textarea value={interviewSummary} onChange={event => setInterviewSummary(event.target.value)} /></Field></div><DialogFooter><Button variant="outline" onClick={() => setInterviewDialog(false)}>إلغاء</Button><Button onClick={submitInterview} disabled={createInterview.isPending || interviewCandidate === "none" || interviewInterviewer === "none" || !interviewScheduledAt} className="bg-[#1f5b45]">جدولة المقابلة</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={offerDialog} onOpenChange={setOfferDialog}><DialogContent dir="rtl"><DialogHeader><DialogTitle>عرض داخلي غير مالي</DialogTitle><DialogDescription>هذا سجل تشغيلي داخلي فقط؛ لا يتضمن راتباً أو عقداً أو توقيعاً أو مرفقات.</DialogDescription></DialogHeader><div className="grid gap-4 py-3"><Field label="مرشح في مرحلة المقابلة"><Select value={offerCandidate} onValueChange={setOfferCandidate}><SelectTrigger><SelectValue placeholder="اختر مرشحاً" /></SelectTrigger><SelectContent>{offerCandidates.map(item => <SelectItem key={item.candidate.id} value={String(item.candidate.id)}>{item.candidate.fullName} · {item.opening.title}</SelectItem>)}</SelectContent></Select></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="تاريخ البدء المقترح"><Input type="date" value={offerStart} onChange={event => setOfferStart(event.target.value)} /></Field><Field label="مهلة الرد"><Input type="date" value={offerResponseDue} onChange={event => setOfferResponseDue(event.target.value)} /></Field></div><Field label="ملاحظة داخلية"><Textarea value={offerNote} onChange={event => setOfferNote(event.target.value)} /></Field></div><DialogFooter><Button variant="outline" onClick={() => setOfferDialog(false)}>إلغاء</Button><Button onClick={submitOffer} disabled={createOffer.isPending || offerCandidate === "none"} className="bg-[#1f5b45]">حفظ العرض الداخلي</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={taskDialog} onOpenChange={setTaskDialog}><DialogContent dir="rtl"><DialogHeader><DialogTitle>مهمة تهيئة</DialogTitle><DialogDescription>لا تُنشأ إلا للمرشحين المقبولين، وتبقى داخل الشركة الحالية.</DialogDescription></DialogHeader><div className="grid gap-4 py-3"><Field label="المرشح المقبول"><Select value={taskCandidate} onValueChange={setTaskCandidate}><SelectTrigger><SelectValue placeholder="اختر مرشحاً" /></SelectTrigger><SelectContent>{acceptedCandidates.map(item => <SelectItem key={item.candidate.id} value={String(item.candidate.id)}>{item.candidate.fullName}</SelectItem>)}</SelectContent></Select></Field><Field label="مالك المهمة"><Select value={taskOwner} onValueChange={setTaskOwner}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">غير محدد</SelectItem>{employees?.map(item => <SelectItem key={item.id} value={String(item.id)}>{item.name || "موظف"}</SelectItem>)}</SelectContent></Select></Field><Field label="عنوان المهمة"><Input value={taskTitle} onChange={event => setTaskTitle(event.target.value)} placeholder="مثال: تجهيز حساب المنصة" /></Field><Field label="تاريخ الاستحقاق"><Input type="date" value={taskDue} onChange={event => setTaskDue(event.target.value)} /></Field></div><DialogFooter><Button variant="outline" onClick={() => setTaskDialog(false)}>إلغاء</Button><Button onClick={submitTask} disabled={createTask.isPending || taskCandidate === "none" || taskTitle.trim().length < 2} className="bg-[#1f5b45]">إضافة المهمة</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={templateDialog} onOpenChange={setTemplateDialog}><DialogContent dir="rtl"><DialogHeader><DialogTitle>قالب مهمة تهيئة</DialogTitle><DialogDescription>يحفظ القالب داخل الشركة الحالية ولا ينشئ مهمة أو يرسل إشعاراً حتى يتم تطبيقه صراحةً.</DialogDescription></DialogHeader><div className="grid gap-4 py-3"><Field label="عنوان القالب"><Input value={templateTitle} onChange={event => setTemplateTitle(event.target.value)} placeholder="مثال: تجهيز حساب المنصة" /></Field><Field label="المالك الافتراضي"><Select value={templateOwner} onValueChange={setTemplateOwner}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">غير محدد</SelectItem>{employees?.map(item => <SelectItem key={item.id} value={String(item.id)}>{item.name || "موظف"}</SelectItem>)}</SelectContent></Select></Field><Field label="إزاحة الاستحقاق بالأيام"><Input type="number" min="0" max="365" value={templateOffset} onChange={event => setTemplateOffset(event.target.value)} /></Field></div><DialogFooter><Button variant="outline" onClick={() => setTemplateDialog(false)}>إلغاء</Button><Button onClick={submitTemplate} disabled={createTemplate.isPending || templateTitle.trim().length < 2 || Number(templateOffset) < 0 || Number(templateOffset) > 365} className="bg-[#1f5b45]">حفظ القالب</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={applyTemplateDialog} onOpenChange={setApplyTemplateDialog}><DialogContent dir="rtl"><DialogHeader><DialogTitle>تطبيق قالب تهيئة</DialogTitle><DialogDescription>ينشئ التطبيق مهمة واحدة للمرشح المقبول فقط، ويمنع تكرار القالب نفسه على المرشح.</DialogDescription></DialogHeader><div className="grid gap-4 py-3"><Field label="القالب"><Select value={selectedTemplate} onValueChange={setSelectedTemplate}><SelectTrigger><SelectValue placeholder="اختر قالباً" /></SelectTrigger><SelectContent>{data?.onboardingTemplates.map(item => <SelectItem key={item.template.id} value={String(item.template.id)}>{item.template.title}</SelectItem>)}</SelectContent></Select></Field><Field label="المرشح المقبول"><Select value={templateCandidate} onValueChange={setTemplateCandidate}><SelectTrigger><SelectValue placeholder="اختر مرشحاً" /></SelectTrigger><SelectContent>{acceptedCandidates.map(item => <SelectItem key={item.candidate.id} value={String(item.candidate.id)}>{item.candidate.fullName} · {item.opening.title}</SelectItem>)}</SelectContent></Select></Field></div><DialogFooter><Button variant="outline" onClick={() => setApplyTemplateDialog(false)}>إلغاء</Button><Button onClick={submitApplyTemplate} disabled={applyTemplate.isPending || selectedTemplate === "none" || templateCandidate === "none"} className="bg-[#1f5b45]">تطبيق القالب</Button></DialogFooter></DialogContent></Dialog>
  </div></DashboardLayout>;
}

function Panel({ title, icon: Icon, action, children }: { title: string; icon: LucideIcon; action: ReactNode; children: ReactNode }) { return <section className="rounded-3xl border border-[#dfe9e1] bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><span className="flex size-9 items-center justify-center rounded-xl bg-[#e9f4eb] text-[#347950]"><Icon className="size-4" /></span><h2 className="font-bold text-[#294535]">{title}</h2></div>{action}</div><div className="mt-5">{children}</div></section>; }
function Stat({ label, value }: { label: string; value: number }) { return <article className="rounded-3xl border border-[#dfe9e1] bg-white p-5"><p className="text-xs font-bold text-[#758278]">{label}</p><p className="mt-3 text-3xl font-bold text-[#1f5b45]">{value}</p></article>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <div><label className="mb-2 block text-xs font-bold text-[#61756a]">{label}</label>{children}</div>; }
function StatusPill({ label, tone }: { label: string; tone: "green" | "red" | "neutral" }) { const styles = { green: "bg-[#e7f4ea] text-[#30774e]", red: "bg-[#fdecea] text-[#a94e48]", neutral: "bg-[#f1f3f1] text-[#65736a]" }; return <span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${styles[tone]}`}>{label}</span>; }
function CompactEmpty({ text }: { text: string }) { return <div className="rounded-2xl bg-[#f7f9f7] px-4 py-7 text-center text-sm text-[#758178]">{text}</div>; }
function StateCard({ title, text, error = false }: { title: string; text: string; error?: boolean }) { return <div className="mt-8 flex min-h-72 flex-col items-center justify-center rounded-3xl border border-[#dfe9e1] bg-white px-6 text-center"><span className={`flex size-14 items-center justify-center rounded-3xl ${error ? "bg-[#fdecea] text-[#a94e48]" : "bg-[#eaf3eb] text-[#357b53]"}`}>{error ? <ShieldAlert className="size-6" /> : <UsersRound className="size-6" />}</span><h2 className="mt-5 font-bold text-[#294535]">{title}</h2><p className="mt-2 max-w-md text-sm leading-6 text-[#748178]">{text}</p></div>; }
