import DashboardLayout from "@/components/DashboardLayout";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { BellRing, ClipboardCheck } from "lucide-react";
import { useLocation } from "wouter";

export default function Workboard() {
  const [, navigate] = useLocation();
  const { data, isLoading, isError, error } = trpc.workboard.overview.useQuery();
  return <DashboardLayout><div dir="rtl" className="mx-auto max-w-6xl"><div><p className="text-xs font-bold text-[#5d8d70]">المرحلة 20 · العمليات</p><h1 className="mt-2 text-3xl font-bold text-[#1d4532]">صندوق العمل الموحد</h1><p className="mt-3 text-sm leading-7 text-[#748178]">يجمع فقط ما يخص حسابك من إشعارات ومهام موافقة قابلة للتنفيذ، دون توسيع نطاق الصلاحيات.</p></div>{isLoading ? <div className="mt-8 grid gap-5 md:grid-cols-2"><Skeleton className="h-80 rounded-3xl"/><Skeleton className="h-80 rounded-3xl"/></div> : isError ? <div className="mt-8 rounded-3xl bg-[#fdecea] p-6 text-sm text-[#9a4741]">تعذر تحميل صندوق العمل: {error.message}</div> : <div className="mt-8 grid gap-5 md:grid-cols-2"><section className="overflow-hidden rounded-3xl border border-[#dfe9e1] bg-white"><header className="flex items-center gap-3 border-b border-[#edf1ed] p-5"><span className="rounded-xl bg-[#e8f3e9] p-2 text-[#347950]"><ClipboardCheck className="size-5"/></span><div><h2 className="font-bold text-[#294535]">قرارات بانتظارك</h2><p className="text-xs text-[#748178]">{data?.approvals.length ?? 0} مهام ضمن دورك</p></div></header>{data?.approvals.length ? <div className="divide-y divide-[#edf1ed]">{data.approvals.map(item => <button key={item.id} onClick={() => navigate(`/requests/${item.requestId}`)} className="w-full p-5 text-right hover:bg-[#fbfcfa]"><p className="font-bold text-[#385545]">{item.subject}</p><p className="mt-1 text-xs text-[#748178]">{item.reference} · مقدّم من {item.employeeName}</p></button>)}</div> : <Empty icon={<ClipboardCheck/>} text="لا توجد قرارات معلقة في نطاقك."/>}</section><section className="overflow-hidden rounded-3xl border border-[#dfe9e1] bg-white"><header className="flex items-center gap-3 border-b border-[#edf1ed] p-5"><span className="rounded-xl bg-[#eef2fb] p-2 text-[#4b6794]"><BellRing className="size-5"/></span><div><h2 className="font-bold text-[#294535]">أحدث الإشعارات</h2><p className="text-xs text-[#748178]">آخر 12 إشعاراً لك</p></div></header>{data?.notifications.length ? <div className="divide-y divide-[#edf1ed]">{data.notifications.map(item => <button key={item.id} onClick={() => item.relatedRequestId && navigate(`/requests/${item.relatedRequestId}`)} className="w-full p-5 text-right hover:bg-[#fbfcfa]"><p className="font-bold text-[#385545]">{item.title}</p><p className="mt-1 text-xs text-[#748178]">{item.body}</p></button>)}</div> : <Empty icon={<BellRing/>} text="لا توجد إشعارات جديدة."/>}</section></div>}</div></DashboardLayout>;
}
function Empty({ icon, text }: { icon: React.ReactNode; text: string }) { return <div className="flex min-h-48 flex-col items-center justify-center p-6 text-center text-sm text-[#748178]"><span className="mb-3 text-[#5d8d70]">{icon}</span>{text}</div>; }
